// ==========================================
// ACADEMIC & SUBJECT QUESTION BANK (Part 1)
// Contains: Exactly 300 Questions (Math, Logic, Verbal, Science, Humanities)
// Levels: 10th (School), Intermediate (College), Graduation (University)
// ==========================================

window.academicPart1 = (function() {
    // Ultra-compressed array format to bypass file size limits
    // Format: [Level(1=10th, 2=Inter, 3=Grad), Subject(1=Math, 2=Logic, 3=Verbal, 4=Sci, 5=GK), Question, Correct, Wrong1, Wrong2, Wrong3]
    const raw = [
        // ================================================
        // 10TH LEVEL (SCHOOL) - 100 Questions
        // ================================================
        // 10th Math (1-20)
        [1, 1, "15 + 25 = ?", "40", "30", "50", "45"],
        [1, 1, "Square root of 144?", "12", "14", "16", "10"],
        [1, 1, "If x + 5 = 12, x is?", "7", "5", "8", "6"],
        [1, 1, "LCM of 4 and 6?", "12", "24", "10", "8"],
        [1, 1, "10% of 500?", "50", "5", "100", "500"],
        [1, 1, "Cost of 1 apple if a dozen cost Rs 60?", "Rs 5", "Rs 6", "Rs 10", "Rs 12"],
        [1, 1, "Perimeter of a square with side 5cm?", "20 cm", "25 cm", "15 cm", "10 cm"],
        [1, 1, "3 cubed (3^3) is?", "27", "9", "81", "6"],
        [1, 1, "If 2x = 20, x is?", "10", "5", "40", "2"],
        [1, 1, "HCF of 8 and 12?", "4", "2", "8", "24"],
        [1, 1, "Simplify: 20 / 4 * 2", "10", "2.5", "5", "8"],
        [1, 1, "Triangle angles are 40° and 60°. 3rd angle?", "80°", "90°", "100°", "70°"],
        [1, 1, "Area of a 4cm by 6cm rectangle?", "24 sq cm", "20 sq cm", "10 sq cm", "12 sq cm"],
        [1, 1, "Convert 1/4 to a percentage.", "25%", "20%", "40%", "14%"],
        [1, 1, "If 5x - 5 = 20, x is?", "5", "4", "6", "10"],
        [1, 1, "Next prime number after 7?", "11", "9", "13", "10"],
        [1, 1, "Average of 2, 4, 6, 8?", "5", "4", "6", "20"],
        [1, 1, "15 * 12 = ?", "180", "160", "150", "120"],
        [1, 1, "100 divided by 0.5?", "200", "50", "500", "150"],
        [1, 1, "Which is a multiple of 9?", "27", "19", "29", "38"],
        
        // 10th Logic (21-40)
        [1, 2, "Next in series: 2, 4, 6, 8, ?", "10", "9", "12", "11"],
        [1, 2, "Next in series: A, C, E, G, ?", "I", "H", "J", "K"],
        [1, 2, "Odd one out: Car, Bus, Bike, Apple", "Apple", "Car", "Bus", "Bike"],
        [1, 2, "If DOG is 3, CAT is?", "3", "2", "4", "5"],
        [1, 2, "A's father is B. B is C's brother. How is A related to C?", "Nephew/Niece", "Son", "Brother", "Uncle"],
        [1, 2, "Next in series: 1, 4, 9, 16, ?", "25", "20", "24", "36"],
        [1, 2, "Sun is to Day as Moon is to?", "Night", "Star", "Sky", "Light"],
        [1, 2, "Odd one out: Pen, Pencil, Marker, Plate", "Plate", "Pen", "Pencil", "Marker"],
        [1, 2, "Bird is to Fly as Fish is to?", "Swim", "Walk", "Run", "Crawl"],
        [1, 2, "Missing number: 10, 20, 30, ?, 50", "40", "35", "45", "60"],
        [1, 2, "If Red means Stop, Green means?", "Go", "Wait", "Slow", "Reverse"],
        [1, 2, "Odd one out: Circle, Square, Triangle, Line", "Line", "Circle", "Square", "Triangle"],
        [1, 2, "A is taller than B. B is taller than C. Who is tallest?", "A", "B", "C", "Equal"],
        [1, 2, "Exact reverse of the word STAR?", "RATS", "TARS", "ARTS", "TSAR"],
        [1, 2, "If 1=A, 2=B, 3=C, letter 5 is?", "E", "D", "F", "G"],
        [1, 2, "Ice is to Cold as Fire is to?", "Hot", "Warm", "Burn", "Red"],
        [1, 2, "Next in series: 100, 90, 80, ?", "70", "60", "75", "85"],
        [1, 2, "Cat is to Kitten as Dog is to?", "Puppy", "Cub", "Calf", "Foal"],
        [1, 2, "Odd one out: East, West, North, Up", "Up", "East", "West", "North"],
        [1, 2, "Which of the following is a shape?", "Circle", "Red", "Soft", "Loud"],

        // 10th Verbal (41-60)
        [1, 3, "Synonym of HAPPY?", "Joyful", "Sad", "Angry", "Tired"],
        [1, 3, "Antonym of FAST?", "Slow", "Quick", "Rapid", "Swift"],
        [1, 3, "Past tense of GO?", "Went", "Gone", "Going", "Goes"],
        [1, 3, "Plural of Mouse?", "Mice", "Mouses", "Mouse", "Mooses"],
        [1, 3, "A person who bakes bread is a?", "Baker", "Cook", "Chef", "Butcher"],
        [1, 3, "Identify noun: 'The blue sky'", "Sky", "Blue", "The", "Is"],
        [1, 3, "Identify verb: 'He runs very fast'", "Runs", "He", "Fast", "Very"],
        [1, 3, "Correct spelling?", "Receive", "Recieve", "Recive", "Receve"],
        [1, 3, "Opposite of HOT?", "Cold", "Warm", "Boiling", "Mild"],
        [1, 3, "Meaning of 'A piece of cake'?", "Very easy", "Very hard", "Sweet", "Food"],
        [1, 3, "Synonym of BIG?", "Large", "Small", "Tiny", "Mini"],
        [1, 3, "Plural of Child?", "Children", "Childs", "Childes", "Childrens"],
        [1, 3, "Past participle of SEE?", "Seen", "Saw", "Seeing", "Sees"],
        [1, 3, "Identify adjective: 'A tall tree'", "Tall", "Tree", "A", "The"],
        [1, 3, "Word that rhymes with CAT?", "Hat", "Dog", "Car", "Cut"],
        [1, 3, "A group of fish is called a?", "School", "Herd", "Flock", "Pack"],
        [1, 3, "Word meaning 'Very small'?", "Tiny", "Huge", "Giant", "Big"],
        [1, 3, "Antonym of BEGIN?", "End", "Start", "Open", "Launch"],
        [1, 3, "He ___ to school every day.", "Goes", "Go", "Going", "Gone"],
        [1, 3, "Synonym of QUICK?", "Fast", "Slow", "Late", "Delay"],
        
        // 10th Science (61-80)
        [1, 4, "Chemical formula for water?", "H2O", "CO2", "O2", "H2O2"],
        [1, 4, "Planet closest to the Sun?", "Mercury", "Venus", "Earth", "Mars"],
        [1, 4, "Gas we breathe to survive?", "Oxygen", "Nitrogen", "Carbon Dioxide", "Helium"],
        [1, 4, "Powerhouse of the cell?", "Mitochondria", "Nucleus", "Ribosome", "Plasma"],
        [1, 4, "Force pushing objects down to Earth?", "Gravity", "Friction", "Magnetism", "Tension"],
        [1, 4, "Boiling point of water in Celsius?", "100", "90", "120", "80"],
        [1, 4, "Primary source of energy for Earth?", "Sun", "Moon", "Wind", "Water"],
        [1, 4, "Which of these is a mammal?", "Whale", "Shark", "Frog", "Snake"],
        [1, 4, "Chemical symbol for Iron?", "Fe", "Ir", "In", "I"],
        [1, 4, "Process by which plants make food?", "Photosynthesis", "Respiration", "Digestion", "Osmosis"],
        [1, 4, "Hardest natural substance on Earth?", "Diamond", "Gold", "Iron", "Quartz"],
        [1, 4, "Sound travels fastest in?", "Solid", "Liquid", "Gas", "Vacuum"],
        [1, 4, "Organ responsible for pumping blood?", "Heart", "Brain", "Lungs", "Liver"],
        [1, 4, "Bones in a normal adult human body?", "206", "208", "201", "210"],
        [1, 4, "Pigment that makes leaves green?", "Chlorophyll", "Melanin", "Carotene", "Plasma"],
        [1, 4, "Acid found in lemons?", "Citric acid", "Acetic acid", "Sulfuric acid", "Nitric acid"],
        [1, 4, "SI unit of Force?", "Newton", "Joule", "Watt", "Pascal"],
        [1, 4, "Largest organ of the human body?", "Skin", "Liver", "Brain", "Heart"],
        [1, 4, "Chemical formula for table salt?", "NaCl", "KCl", "NaOH", "HCl"],
        [1, 4, "Gas absorbed by plants during photosynthesis?", "Carbon dioxide", "Oxygen", "Nitrogen", "Hydrogen"],
        
        // 10th General Studies (81-100)
        [1, 5, "Capital of India?", "New Delhi", "Mumbai", "Kolkata", "Chennai"],
        [1, 5, "National Animal of India?", "Tiger", "Lion", "Elephant", "Leopard"],
        [1, 5, "First Prime Minister of India?", "Jawaharlal Nehru", "Mahatma Gandhi", "Sardar Patel", "Subhas Bose"],
        [1, 5, "When does India celebrate Independence Day?", "15 August", "26 January", "2 October", "1 May"],
        [1, 5, "Highest mountain peak in the world?", "Mount Everest", "K2", "Kanchenjunga", "Makalu"],
        [1, 5, "Longest river in the world?", "Nile", "Amazon", "Ganga", "Yangtze"],
        [1, 5, "Who wrote the Indian National Anthem?", "Rabindranath Tagore", "Bankim Chandra", "Sarojini Naidu", "Subhas Bose"],
        [1, 5, "Which century are we currently living in?", "21st", "20th", "19th", "22nd"],
        [1, 5, "How many states are there in India currently?", "28", "29", "27", "30"],
        [1, 5, "Indian festival known as the festival of lights?", "Diwali", "Holi", "Eid", "Christmas"],
        [1, 5, "National Flower of India?", "Lotus", "Rose", "Lily", "Sunflower"],
        [1, 5, "Who is the Father of the Nation in India?", "Mahatma Gandhi", "Jawaharlal Nehru", "Subhas Bose", "Bhagat Singh"],
        [1, 5, "Planet famous for its visible rings?", "Saturn", "Jupiter", "Mars", "Venus"],
        [1, 5, "Language primarily spoken in Maharashtra?", "Marathi", "Hindi", "Gujarati", "Tamil"],
        [1, 5, "Official currency of India?", "Rupee", "Dollar", "Euro", "Yen"],
        [1, 5, "Largest continent by land area?", "Asia", "Africa", "Europe", "North America"],
        [1, 5, "In which city is the Taj Mahal located?", "Agra", "New Delhi", "Jaipur", "Mumbai"],
        [1, 5, "Where is the Gateway of India located?", "Mumbai", "New Delhi", "Chennai", "Kolkata"],
        [1, 5, "National Bird of India?", "Peacock", "Parrot", "Pigeon", "Crow"],
        [1, 5, "Days in a Leap Year?", "366", "365", "364", "367"],

        // ================================================
        // INTERMEDIATE LEVEL (COLLEGE) - 100 Questions
        // ================================================
        // Inter Math (101-120)
        [2, 1, "Value of 5! (5 factorial)?", "120", "60", "24", "100"],
        [2, 1, "Probability of a fair coin landing Heads?", "0.5", "1", "0.25", "0.75"],
        [2, 1, "Log base 10 of 100 is?", "2", "10", "1", "3"],
        [2, 1, "Derivative of x^2?", "2x", "x", "2", "x^2"],
        [2, 1, "Integral of 2x dx?", "x^2", "2x^2", "x", "2"],
        [2, 1, "Value of Sin(90°)?", "1", "0", "-1", "0.5"],
        [2, 1, "Value of Cos(0°)?", "1", "0", "-1", "0.5"],
        [2, 1, "Determinant of 2x2 matrix with diagonal [2, 2] and off [0, 0]?", "4", "2", "0", "8"],
        [2, 1, "Sum of first 10 natural numbers?", "55", "50", "60", "45"],
        [2, 1, "Distance between (0,0) and (3,4)?", "5", "4", "3", "7"],
        [2, 1, "Volume of a cube with side length 3?", "27", "9", "18", "81"],
        [2, 1, "Roots of equation x^2 - 4 = 0?", "2, -2", "4, -4", "2, 0", "0, -2"],
        [2, 1, "Approximate value of Pi?", "3.14", "3.12", "3.16", "3.18"],
        [2, 1, "Degrees in a full circle?", "360", "180", "90", "270"],
        [2, 1, "If f(x) = 3x + 1, f(2) is?", "7", "6", "5", "8"],
        [2, 1, "Slope of the line y = 4x - 2?", "4", "-2", "2", "0"],
        [2, 1, "2 raised to the power of 5?", "32", "16", "64", "10"],
        [2, 1, "Value of tan(45°)?", "1", "0", "-1", "0.5"],
        [2, 1, "Surface area formula of a sphere?", "4*pi*r^2", "pi*r^2", "2*pi*r", "4/3*pi*r^3"],
        [2, 1, "10% of 20% of 100?", "2", "10", "5", "20"],
        
        // Inter Logic (121-140)
        [2, 2, "If A=1, B=2... Z=26, value of BAT?", "23", "22", "24", "21"],
        [2, 2, "Next in: 1, 1, 2, 3, 5, 8, ?", "13", "10", "12", "11"],
        [2, 2, "Face South, turn 90 deg clockwise. Which way now?", "West", "East", "North", "South"],
        [2, 2, "If all X are Y, and all Y are Z, then:", "All X are Z", "Some Z are X", "No X are Z", "All Z are X"],
        [2, 2, "Odd one out: 2, 3, 5, 9", "9", "2", "3", "5"],
        [2, 2, "Pointing to boy, man says 'He is son of my father's only son'. Boy is?", "Son", "Nephew", "Brother", "Himself"],
        [2, 2, "Next in: AZ, BY, CX, ?", "DW", "EV", "FU", "DX"],
        [2, 2, "If '+' means multiply, what is '3 + 4'?", "12", "7", "1", "10"],
        [2, 2, "Angle between hands at exactly 3:00?", "90°", "82.5°", "0°", "15°"],
        [2, 2, "If today is Monday, what day is it after 61 days?", "Saturday", "Sunday", "Monday", "Friday"],
        [2, 2, "Odd one out: Square, Cube, Sphere, Cylinder", "Square", "Cube", "Sphere", "Cylinder"],
        [2, 2, "Tree is to Forest as Soldier is to?", "Army", "War", "Gun", "Battle"],
        [2, 2, "Next in: 2, 5, 10, 17, ?", "26", "24", "25", "27"],
        [2, 2, "If RED=27, BLUE=? (A=1...)", "40", "35", "45", "38"],
        [2, 2, "Mirror image time of 9:00?", "3:00", "9:30", "6:00", "12:00"],
        [2, 2, "Water is to Pipe as Blood is to?", "Vein", "Heart", "Body", "Red"],
        [2, 2, "Next in: 10, 12, 15, 19, ?", "24", "22", "23", "25"],
        [2, 2, "Odd one out: Teacher, Doctor, Engineer, Student", "Student", "Teacher", "Doctor", "Engineer"],
        [2, 2, "If 'GO' = 32, 'SHE' = 49, 'SOME' = ?", "56", "50", "60", "52"],
        [2, 2, "A is East of B. C is North of B. C relative to A is?", "North-West", "North-East", "South-West", "South-East"],

        // Inter Verbal (141-160)
        [2, 3, "Synonym of METICULOUS?", "Careful", "Careless", "Messy", "Quick"],
        [2, 3, "Antonym of OBSCURE?", "Clear", "Hidden", "Dark", "Vague"],
        [2, 3, "Meaning of 'Bite the bullet'?", "Endure bravely", "Eat fast", "Shoot", "Run away"],
        [2, 3, "Correct spelling?", "Embarrass", "Embarass", "Embaras", "Emmbarrass"],
        [2, 3, "Preposition in 'The shoes are under the bed'", "Under", "The", "Bed", "Are"],
        [2, 3, "Plural of Phenomenon?", "Phenomena", "Phenomenons", "Phenomenon", "Phenomenas"],
        [2, 3, "Synonym of CANDID?", "Honest", "Fake", "Shy", "Quiet"],
        [2, 3, "Antonym of ARROGANT?", "Humble", "Proud", "Bold", "Rude"],
        [2, 3, "Meaning of 'Let the cat out of the bag'?", "Reveal a secret", "Buy pet", "Mistake", "Run fast"],
        [2, 3, "Adverb in 'She ran quickly'", "Quickly", "She", "Ran", "Store"],
        [2, 3, "Synonym of LUCID?", "Clear", "Confusing", "Dark", "Thick"],
        [2, 3, "Antonym of ZEALOUS?", "Apathetic", "Eager", "Passionate", "Active"],
        [2, 3, "'If I ___ a bird, I would fly.'", "were", "was", "am", "be"],
        [2, 3, "Meaning of 'A piece of cake'?", "Easy task", "Dessert", "Hard work", "Gift"],
        [2, 3, "Synonym of VAST?", "Immense", "Tiny", "Small", "Narrow"],
        [2, 3, "Antonym of DILIGENT?", "Lazy", "Hardworking", "Smart", "Active"],
        [2, 3, "Correct spelling?", "Accommodation", "Accomodation", "Acommodation", "Acomodation"],
        [2, 3, "'Break the ice' means?", "Start conversation", "Break glass", "Be cold", "End fight"],
        [2, 3, "Scientific study of stars?", "Astronomy", "Astrology", "Geology", "Biology"],
        [2, 3, "A person who hates mankind?", "Misanthrope", "Philanthropist", "Optimist", "Pessimist"],

        // Inter Science (161-180)
        [2, 4, "Atomic number of Carbon?", "6", "8", "12", "14"],
        [2, 4, "Valency of Oxygen?", "2", "1", "4", "3"],
        [2, 4, "Newton's Second Law equation?", "F=ma", "E=mc2", "v=u+at", "P=W/t"],
        [2, 4, "Hydrogen isotope with 1 proton, 1 neutron?", "Deuterium", "Tritium", "Protium", "Helium"],
        [2, 4, "Cells responsible for fighting infection?", "White Blood Cells", "Red Blood Cells", "Platelets", "Plasma"],
        [2, 4, "Standard gravity (g) on Earth?", "9.8 m/s^2", "10.5 m/s^2", "8.9 m/s^2", "9.0 m/s^2"],
        [2, 4, "pH value indicating strong acid?", "1", "7", "14", "9"],
        [2, 4, "Speed of sound in air?", "343 m/s", "300 m/s", "400 m/s", "150 m/s"],
        [2, 4, "Lens formula?", "1/f = 1/v - 1/u", "F=ma", "V=IR", "P=VI"],
        [2, 4, "Full form of DNA?", "Deoxyribonucleic Acid", "Ribonucleic Acid", "Dinucleic Acid", "Deoxynitric Acid"],
        [2, 4, "Most abundant gas in universe?", "Hydrogen", "Helium", "Oxygen", "Nitrogen"],
        [2, 4, "Formula for Ohm's Law?", "V=IR", "P=VI", "F=ma", "E=mc2"],
        [2, 4, "Charge of a cation?", "Positive", "Negative", "Neutral", "Variable"],
        [2, 4, "Eye part controlling light?", "Iris", "Retina", "Cornea", "Lens"],
        [2, 4, "Which is a Noble Gas?", "Neon", "Oxygen", "Chlorine", "Nitrogen"],
        [2, 4, "SI unit of Power?", "Watt", "Joule", "Ohm", "Volt"],
        [2, 4, "Avogadro's number?", "6.022x10^23", "3.14", "9.8", "3x10^8"],
        [2, 4, "Metal liquid at room temp?", "Mercury", "Gold", "Iron", "Lead"],
        [2, 4, "Basic structural unit of life?", "Cell", "Atom", "Molecule", "Tissue"],
        [2, 4, "Main gas in natural biogas?", "Methane", "Ethane", "Propane", "Butane"],

        // Inter GK (181-200)
        [2, 5, "Fundamental Rights are in which Part?", "Part III", "Part II", "Part IV", "Part V"],
        [2, 5, "Year of First War of Independence?", "1857", "1947", "1757", "1901"],
        [2, 5, "Longest bone in human body?", "Femur", "Tibia", "Radius", "Ulna"],
        [2, 5, "Capital of Australia?", "Canberra", "Sydney", "Melbourne", "Perth"],
        [2, 5, "Year RBI was established?", "1935", "1947", "1950", "1920"],
        [2, 5, "Largest ocean on Earth?", "Pacific", "Atlantic", "Indian", "Arctic"],
        [2, 5, "Inventor of telephone?", "Alexander Bell", "Thomas Edison", "Nikola Tesla", "Einstein"],
        [2, 5, "Hardest natural mineral?", "Diamond", "Topaz", "Corundum", "Quartz"],
        [2, 5, "Article for Right to Equality?", "Article 14", "Article 19", "Article 32", "Article 21"],
        [2, 5, "World Environment Day?", "5 June", "22 April", "1 May", "10 Dec"],
        [2, 5, "Currency of Japan?", "Yen", "Yuan", "Won", "Dollar"],
        [2, 5, "Iron Man of India?", "Sardar Patel", "Jawaharlal Nehru", "Subhas Bose", "Bhagat Singh"],
        [2, 5, "First Indian in space?", "Rakesh Sharma", "Kalpana Chawla", "Sunita Williams", "Kalam"],
        [2, 5, "Headquarters of UNO?", "New York", "Geneva", "Paris", "London"],
        [2, 5, "Smallest planet?", "Mercury", "Pluto", "Mars", "Venus"],
        [2, 5, "National Tree of India?", "Banyan", "Neem", "Peepal", "Mango"],
        [2, 5, "Author of 'Discovery of India'?", "Jawaharlal Nehru", "Mahatma Gandhi", "Tagore", "Ambedkar"],
        [2, 5, "Largest hot desert?", "Sahara", "Gobi", "Thar", "Kalahari"],
        [2, 5, "First female PM of India?", "Indira Gandhi", "Pratibha Patil", "Sarojini Naidu", "Sushma Swaraj"],
        [2, 5, "Ozone layer protects from?", "UV Rays", "Infrared", "Microwaves", "Radio"],

        // ================================================
        // GRADUATION LEVEL (UNIVERSITY) - 100 Questions
        // ================================================
        // Grad Math (201-220)
        [3, 1, "A and B finish in 10 days. A alone 15 days. B alone?", "30 days", "20 days", "25 days", "40 days"],
        [3, 1, "Money doubles in 5 years simple interest. Rate?", "20%", "10%", "15%", "25%"],
        [3, 1, "Train 100m passes pole in 10s. Speed in km/hr?", "36", "72", "54", "18"],
        [3, 1, "Cost price is 80% of selling price. Profit %?", "25%", "20%", "30%", "15%"],
        [3, 1, "A and B ratio 3:4. Sum 70. Value of A?", "30", "40", "20", "50"],
        [3, 1, "Average of 5 consecutive nums is 20. Sum is?", "100", "20", "80", "120"],
        [3, 1, "Compound interest on Rs 1000 at 10% for 2 yrs?", "Rs 210", "Rs 200", "Rs 100", "Rs 220"],
        [3, 1, "Volume of cylinder: r=2, h=5?", "20*pi", "10*pi", "40*pi", "15*pi"],
        [3, 1, "Probability of drawing an Ace from 52 cards?", "1/13", "1/52", "4/13", "1/4"],
        [3, 1, "A runs 5/3 times B. A gives B 80m start. Dead heat distance?", "200m", "150m", "180m", "250m"],
        [3, 1, "Two dice thrown. Probability of sum exactly 7?", "1/6", "1/12", "1/36", "1/4"],
        [3, 1, "Log2(8) + Log2(4) = ?", "5", "3", "2", "8"],
        [3, 1, "Integration of e^x dx?", "e^x", "x*e^x", "e^x/x", "e"],
        [3, 1, "Area of equilateral triangle side 'a'?", "(sqrt(3)/4)a^2", "(sqrt(3)/2)a^2", "a^2", "3a"],
        [3, 1, "Sin^2(x) + Cos^2(x) = ?", "1", "0", "-1", "2"],
        [3, 1, "Boat speed 15km/hr, stream 3km/hr. Downstream speed?", "18 km/hr", "12 km/hr", "15 km/hr", "3 km/hr"],
        [3, 1, "Value of 5P3?", "60", "120", "20", "10"],
        [3, 1, "10 men do work in 15 days. 15 men take?", "10 days", "5 days", "12 days", "20 days"],
        [3, 1, "What % of 50 is 2?", "4%", "2%", "5%", "10%"],
        [3, 1, "Simple interest on Rs 2000 at 5% for 4 yrs?", "Rs 400", "Rs 200", "Rs 500", "Rs 800"],

        // Grad Logic (221-240)
        [3, 2, "All A are B. Some B are C. Therefore Some A are C?", "Not necessarily", "Always True", "Always False", "Paradoxical"],
        [3, 2, "5 machines, 5 mins, 5 widgets. 100 machines, 100 widgets?", "5 mins", "100 mins", "1 min", "50 mins"],
        [3, 2, "Bat & ball = $1.10. Bat is $1.00 more than ball. Ball is?", "$0.05", "$0.10", "$0.15", "$0.50"],
        [3, 2, "Next prime: 2, 3, 5, 7, 11, ?", "13", "12", "15", "14"],
        [3, 2, "If SE becomes N, then NW becomes?", "S", "E", "W", "SW"],
        [3, 2, "Boy is son of daughter of father of my uncle. Girl says he is?", "Brother", "Nephew", "Son", "Uncle"],
        [3, 2, "Row of 20, A is 5th from left. Rank from right?", "16th", "15th", "17th", "14th"],
        [3, 2, "Angle between hands at 3:15?", "7.5°", "0°", "15°", "22.5°"],
        [3, 2, "Oct 1 is Sunday. Nov 1 is?", "Wednesday", "Tuesday", "Thursday", "Monday"],
        [3, 2, "Odd one: Iron, Copper, Zinc, Brass", "Brass", "Iron", "Copper", "Zinc"],
        [3, 2, "SOLID=HLOKW. LIQUID=?", "ORJXFW", "OQJXFW", "ORJYFW", "OQJYFW"],
        [3, 2, "A>B, C>A, D>E, B>D. Tallest?", "C", "A", "B", "D"],
        [3, 2, "3x3x3 painted cube cut to 1x1x1. Cubes with 0 painted faces?", "1", "8", "27", "6"],
        [3, 2, "Missing: 1, 8, 27, 64, ?", "125", "100", "144", "120"],
        [3, 2, "'Drink X to stay healthy'. Assumption: People want health?", "Implicit", "Not implicit", "False", "Irrelevant"],
        [3, 2, "DOCTOR:PATIENT as...", "Lawyer:Client", "Teacher:Chalk", "Driver:Car", "Shop:Buyer"],
        [3, 2, "400m race. A gives B 5s start, wins by 15m. A speed 8m/s. B speed?", "Cannot determine", "5 m/s", "8 m/s", "10 m/s"],
        [3, 2, "A+B=mother, A-B=bro, A%B=father, A*B=sis. P is uncle of Q?", "P-M+N*Q", "P+S-N*Q", "P-M%N*Q", "P+M*N*Q"],
        [3, 2, "Max triangles in pentagon with all diagonals?", "35", "25", "40", "30"],
        [3, 2, "Non-leap year calendar repeats in?", "11 years", "5 years", "4 years", "12 years"],

        // Grad Verbal (241-260)
        [3, 3, "OPPOSITE of EPHEMERAL?", "Permanent", "Transient", "Fleeting", "Brief"],
        [3, 3, "Antonym of MITIGATE?", "Aggravate", "Soothe", "Calm", "Reduce"],
        [3, 3, "Quid pro quo means?", "Something for something", "Nothing", "Everything", "Legal right"],
        [3, 3, "Correct spelling?", "Hierarchy", "Heirarchy", "Heirachy", "Hierachy"],
        [3, 3, "Person speaking many languages?", "Polyglot", "Linguist", "Introvert", "Extrovert"],
        [3, 3, "Synonym of UBIQUITOUS?", "Omnipresent", "Rare", "Scarce", "Hidden"],
        [3, 3, "Antonym of CACOPHONY?", "Harmony", "Noise", "Clamor", "Din"],
        [3, 3, "'Achilles heel' means?", "Fatal weakness", "Strong point", "Foot injury", "Myth"],
        [3, 3, "Fear of confined spaces?", "Claustrophobia", "Acrophobia", "Hydrophobia", "Agoraphobia"],
        [3, 3, "'Of the two brothers, he is the ___.'", "taller", "tallest", "more tall", "most tall"],
        [3, 3, "Synonym of INTRICATE?", "Complex", "Simple", "Basic", "Plain"],
        [3, 3, "Antonym of EXONERATE?", "Convict", "Free", "Clear", "Release"],
        [3, 3, "Study of coins?", "Numismatics", "Philately", "Epigraphy", "Archaeology"],
        [3, 3, "'Cross the Rubicon' means?", "Point of no return", "Swim river", "Win war", "Admit defeat"],
        [3, 3, "Correct spelling?", "Superintendent", "Suprintendent", "Superintendant", "Supperintendent"],
        [3, 3, "Synonym of PERNICIOUS?", "Harmful", "Helpful", "Kind", "Good"],
        [3, 3, "Antonym of GREGARIOUS?", "Introverted", "Sociable", "Outgoing", "Friendly"],
        [3, 3, "'De facto' means?", "In fact/reality", "By law", "In future", "In past"],
        [3, 3, "Person who collects stamps?", "Philatelist", "Numismatist", "Scientist", "Artist"],
        [3, 3, "'Pyrrhic victory' means?", "Victory at too great a cost", "Easy win", "Crushing defeat", "Mutual draw"],

        // Grad Science (261-280)
        [3, 4, "Einstein won Nobel Prize for?", "Photoelectric Effect", "Relativity", "Gravity", "Thermodynamics"],
        [3, 4, "Principle explaining aircraft lift?", "Bernoulli's", "Archimedes", "Newton 3rd", "Pascal's"],
        [3, 4, "DNA double helix co-discovered by Crick and?", "Watson", "Mendel", "Darwin", "Pasteur"],
        [3, 4, "Most abundant structural protein in human body?", "Collagen", "Keratin", "Hemoglobin", "Insulin"],
        [3, 4, "Logic gate outputting '1' ONLY if all inputs are '1'?", "AND", "OR", "XOR", "NAND"],
        [3, 4, "First satellite built entirely by India?", "Aryabhata", "Bhaskara", "Rohini", "Insat"],
        [3, 4, "Deficiency of B12 causes?", "Pernicious Anemia", "Scurvy", "Rickets", "Beriberi"],
        [3, 4, "Half-life of Carbon-14?", "5,730 yrs", "1,000 yrs", "10,000 yrs", "500 yrs"],
        [3, 4, "Chemical formula for Heavy Water?", "D2O", "H2O2", "H3O", "HO2"],
        [3, 4, "'Gaganyaan' project agency?", "ISRO", "NASA", "ESA", "SpaceX"],
        [3, 4, "SI derived unit of magnetic flux?", "Weber", "Tesla", "Gauss", "Oersted"],
        [3, 4, "Metal stored under kerosene due to reactivity?", "Sodium", "Iron", "Zinc", "Copper"],
        [3, 4, "Solid to gas process?", "Sublimation", "Evaporation", "Condensation", "Melting"],
        [3, 4, "Which is a scalar quantity?", "Speed", "Velocity", "Force", "Acceleration"],
        [3, 4, "Study of fungi?", "Mycology", "Phycology", "Virology", "Bacteriology"],
        [3, 4, "Acid in ant sting?", "Formic acid", "Acetic acid", "Citric acid", "Lactic acid"],
        [3, 4, "Earth's escape velocity?", "11.2 km/s", "9.8 km/s", "15.0 km/s", "10.0 km/s"],
        [3, 4, "Instrument measuring atmospheric pressure?", "Barometer", "Hygrometer", "Thermometer", "Anemometer"],
        [3, 4, "Lightest metal on periodic table?", "Lithium", "Osmium", "Aluminum", "Magnesium"],
        [3, 4, "First cloned mammal?", "Dolly the Sheep", "Mickey", "Polly", "Tom"],

        // Grad GK (281-300)
        [3, 5, "Heart and Soul of Constitution (Ambedkar)?", "Article 32", "Preamble", "Article 14", "Article 21"],
        [3, 5, "Who calculates GDP in India?", "NSO", "RBI", "Finance Min", "NITI Aayog"],
        [3, 5, "Repo Rate determined by?", "RBI", "SBI", "SEBI", "Finance Min"],
        [3, 5, "Number of Schedules in Constitution?", "12", "8", "10", "14"],
        [3, 5, "Ex-officio Chairman of NITI Aayog?", "Prime Minister", "President", "Finance Min", "Home Min"],
        [3, 5, "Panchayati Raj Amendment?", "73rd", "74th", "42nd", "44th"],
        [3, 5, "GST is which type of tax?", "Indirect", "Direct", "Income", "Corporate"],
        [3, 5, "Year First Five-Year Plan launched?", "1951", "1947", "1950", "1955"],
        [3, 5, "Article 360 declares?", "Financial Emergency", "National Emergency", "State Emergency", "Elections"],
        [3, 5, "SEBI given statutory powers in?", "1992", "1988", "1990", "1995"],
        [3, 5, "Longest-serving CM of an Indian state?", "Pawan Chamling", "Jyoti Basu", "Naveen Patnaik", "Nitish Kumar"],
        [3, 5, "Sector contributing most to India's GDP?", "Services", "Agriculture", "Manufacturing", "Mining"],
        [3, 5, "Minimum age for President of India?", "35", "30", "25", "40"],
        [3, 5, "Bretton Woods twins?", "World Bank & IMF", "WTO & WHO", "UN & UNICEF", "ADB & NDB"],
        [3, 5, "Five Year Plan borrowed from?", "USSR", "USA", "UK", "France"],
        [3, 5, "Writ meaning 'We Command'?", "Mandamus", "Habeas Corpus", "Quo Warranto", "Certiorari"],
        [3, 5, "NABARD regulates?", "Agri & Rural Dev", "Heavy Industry", "Foreign Trade", "Urban Housing"],
        [3, 5, "Who appoints Chief Justice of India?", "President", "Prime Minister", "Parliament", "Vice President"],
        [3, 5, "Inflation measured using?", "CPI & WPI", "GDP Growth", "GNP Deflator", "Repo Rate"],
        [3, 5, "RTE Act passed in?", "2009", "2010", "2005", "2008"],

        // ================================================
        // ADDITIONAL 100 QUESTIONS (Bringing Total to 400)
        // ================================================
        // --- 10th Level (33 Questions) ---
        [1, 1, "If 3x = 15, x is?", "5", "3", "10", "15"],
        [1, 1, "Area of a circle?", "pi*r^2", "2*pi*r", "pi*d", "2*r"],
        [1, 1, "Next even number after 14?", "16", "15", "18", "20"],
        [1, 1, "Half of 250?", "125", "100", "150", "200"],
        [1, 1, "7 * 7 = ?", "49", "42", "56", "35"],
        [1, 1, "LCM of 2 and 3?", "6", "5", "12", "8"],
        [1, 1, "Square of 9?", "81", "72", "99", "18"],
        [1, 2, "If A=1, B=2, C=?", "3", "4", "5", "6"],
        [1, 2, "Odd one out: Apple, Banana, Orange, Onion", "Onion", "Apple", "Banana", "Orange"],
        [1, 2, "Day after Tuesday?", "Wednesday", "Monday", "Thursday", "Friday"],
        [1, 2, "Next in: 5, 10, 15, 20, ?", "25", "30", "22", "35"],
        [1, 2, "Opposite of Up is?", "Down", "Left", "Right", "High"],
        [1, 2, "Finger is to Hand as Toe is to?", "Foot", "Leg", "Arm", "Nail"],
        [1, 2, "If 2+2=4, 3+3=?", "6", "5", "8", "9"],
        [1, 3, "Synonym of BEAUTIFUL?", "Pretty", "Ugly", "Bad", "Mad"],
        [1, 3, "Antonym of DAY?", "Night", "Morning", "Evening", "Sun"],
        [1, 3, "Past tense of EAT?", "Ate", "Eated", "Eating", "Eaten"],
        [1, 3, "Plural of Box?", "Boxes", "Boxs", "Boxen", "Boxies"],
        [1, 3, "Identify vowel: B, C, D, E", "E", "B", "C", "D"],
        [1, 3, "Synonym of SMALL?", "Tiny", "Huge", "Big", "Large"],
        [1, 3, "Antonym of GOOD?", "Bad", "Great", "Nice", "Well"],
        [1, 4, "Chemical symbol for Oxygen?", "O", "Ox", "O2", "Om"],
        [1, 4, "Water freezes at what Celsius?", "0", "100", "32", "50"],
        [1, 4, "Animals that eat plants are?", "Herbivores", "Carnivores", "Omnivores", "Insectivores"],
        [1, 4, "Center of our solar system?", "Sun", "Earth", "Moon", "Jupiter"],
        [1, 4, "Gas plants give off during photosynthesis?", "Oxygen", "Carbon Dioxide", "Nitrogen", "Helium"],
        [1, 4, "How many primary senses do humans have?", "5", "6", "4", "7"],
        [1, 5, "Capital of France?", "Paris", "London", "Rome", "Berlin"],
        [1, 5, "Number of colors in a rainbow?", "7", "6", "8", "9"],
        [1, 5, "Who built the Taj Mahal?", "Shah Jahan", "Akbar", "Babur", "Humayun"],
        [1, 5, "National game of India?", "Hockey", "Cricket", "Kabaddi", "Football"],
        [1, 5, "Fastest land animal?", "Cheetah", "Lion", "Tiger", "Leopard"],
        [1, 5, "Which is the current leap year?", "2024", "2025", "2026", "2027"],

        // --- Intermediate Level (33 Questions) ---
        [2, 1, "Log base 2 of 16?", "4", "8", "3", "2"],
        [2, 1, "Derivative of 3x?", "3", "x", "3x", "0"],
        [2, 1, "Value of Cos(90°)?", "0", "1", "-1", "0.5"],
        [2, 1, "Sum of interior angles in a triangle?", "180°", "360°", "90°", "270°"],
        [2, 1, "Probability of drawing a King from 52 cards?", "1/13", "1/4", "1/52", "4/13"],
        [2, 1, "15% of 600?", "90", "60", "45", "100"],
        [2, 1, "Roots of x^2 - 9 = 0?", "3, -3", "9, -9", "3, 0", "0, -3"],
        [2, 2, "If M=13, N=14, O=?", "15", "16", "12", "17"],
        [2, 2, "Next in: 2, 6, 12, 20, ?", "30", "28", "24", "32"],
        [2, 2, "Odd one: Circle, Ellipse, Sphere, Triangle", "Sphere", "Circle", "Ellipse", "Triangle"],
        [2, 2, "Clock hands overlap how many times a day?", "22", "24", "12", "48"],
        [2, 2, "A is B's wife. B is C's brother. A is C's?", "Sister-in-law", "Sister", "Wife", "Aunt"],
        [2, 2, "Next in: 100, 81, 64, 49, ?", "36", "25", "40", "30"],
        [2, 2, "If 5*5=25, 6*6=36, 7*7=?", "49", "48", "50", "42"],
        [2, 3, "Synonym of GIGANTIC?", "Colossal", "Tiny", "Minor", "Small"],
        [2, 3, "Antonym of COMPLICATED?", "Simple", "Hard", "Tough", "Intricate"],
        [2, 3, "Meaning of 'Under the weather'?", "Sick", "Raining", "Cold", "Happy"],
        [2, 3, "Plural of Syllabus?", "Syllabi", "Syllabuses", "Syllabise", "Syllabs"],
        [2, 3, "Correct spelling?", "Committee", "Comittee", "Commitee", "Comitee"],
        [2, 3, "A person who loves books?", "Bibliophile", "Philanthropist", "Misogynist", "Linguist"],
        [2, 3, "Synonym of ABUNDANT?", "Plentiful", "Scarce", "Rare", "Few"],
        [2, 4, "Chemical formula for Sulfuric Acid?", "H2SO4", "HCl", "HNO3", "H2O"],
        [2, 4, "Unit of Electric Current?", "Ampere", "Volt", "Ohm", "Watt"],
        [2, 4, "Which blood group is universal donor?", "O-", "AB+", "A+", "B-"],
        [2, 4, "Planet with the most moons in our solar system?", "Saturn", "Jupiter", "Uranus", "Neptune"],
        [2, 4, "Who discovered Penicillin?", "Alexander Fleming", "Louis Pasteur", "Marie Curie", "Isaac Newton"],
        [2, 4, "Study of insects is?", "Entomology", "Etymology", "Biology", "Zoology"],
        [2, 5, "Who wrote the Mahabharata?", "Vyasa", "Valmiki", "Tulsidas", "Kalidasa"],
        [2, 5, "Highest civilian award in India?", "Bharat Ratna", "Padma Vibhushan", "Padma Shri", "Param Vir Chakra"],
        [2, 5, "Capital of Canada?", "Ottawa", "Canberra", "Toronto", "Vancouver"],
        [2, 5, "World's largest hot desert?", "Sahara", "Antarctic", "Arctic", "Gobi"],
        [2, 5, "First President of India?", "Dr. Rajendra Prasad", "Jawaharlal Nehru", "S. Radhakrishnan", "Zakir Husain"],
        [2, 5, "Currency of the UK?", "Pound Sterling", "Euro", "Dollar", "Franc"],

        // --- Graduation Level (34 Questions) ---
        [3, 1, "Probability of drawing 2 aces from 52 cards?", "1/221", "1/169", "4/52", "2/52"],
        [3, 1, "Integral of 1/x dx?", "ln|x|", "x^2", "e^x", "1/x^2"],
        [3, 1, "Sum of infinite geometric series 1 + 1/2 + 1/4...?", "2", "Infinity", "1.5", "3"],
        [3, 1, "Eigenvalues of an identity matrix?", "1", "0", "-1", "Depends"],
        [3, 1, "Number of permutations of 'HELLO'?", "60", "120", "24", "100"],
        [3, 1, "A and B finish in 12 days. B and C in 15. C and A in 20. A,B,C together?", "10 days", "12 days", "8 days", "15 days"],
        [3, 1, "Find the derivative of sin(x).", "cos(x)", "-sin(x)", "-cos(x)", "tan(x)"],
        [3, 2, "If all A are B, and no B are C. Can A be C?", "No", "Yes", "Maybe", "Always"],
        [3, 2, "Clock shows 4:20. Angle between hands?", "10°", "0°", "20°", "15°"],
        [3, 2, "A man is 3x as old as son. In 10 years, he will be 2x. Son's age?", "10", "15", "20", "5"],
        [3, 2, "Find odd one out: 2, 3, 5, 7, 9, 11", "9", "2", "5", "11"],
        [3, 2, "Statement: 'Don't park here'. Assumption: People can read.", "Implicit", "Not implicit", "Irrelevant", "False"],
        [3, 2, "If day before yesterday was Thursday, what is day after tomorrow?", "Monday", "Tuesday", "Sunday", "Wednesday"],
        [3, 2, "Next in series: 2, 10, 30, 68, ?", "130", "120", "140", "110"],
        [3, 3, "Synonym of FORTUITY?", "Chance", "Fate", "Misfortune", "Design"],
        [3, 3, "Antonym of LUGUBRIOUS?", "Cheerful", "Sad", "Mournful", "Gloomy"],
        [3, 3, "Meaning of 'To play devil's advocate'?", "Argue against a cause for debate", "Be evil", "Support a bad person", "Lie in court"],
        [3, 3, "Identify the oxymoron:", "Deafening silence", "Loud noise", "Bright light", "Dark night"],
        [3, 3, "Synonym of MUNIFICENT?", "Generous", "Stingy", "Cruel", "Poor"],
        [3, 3, "Antonym of EQUIVOCAL?", "Clear", "Ambiguous", "Vague", "Doubtful"],
        [3, 3, "Meaning of 'Status quo'?", "Existing state of affairs", "High status", "Change", "Legal ruling"],
        [3, 4, "Boson particle is named after which Indian scientist?", "S. N. Bose", "J. C. Bose", "C. V. Raman", "Homi Bhabha"],
        [3, 4, "What is the Pauli Exclusion Principle related to?", "Quantum Mechanics", "Thermodynamics", "Relativity", "Fluid Dynamics"],
        [3, 4, "Which organelle is known as the 'suicide bag' of the cell?", "Lysosome", "Mitochondria", "Golgi body", "Ribosome"],
        [3, 4, "What is the most abundant element in the Earth's crust?", "Oxygen", "Silicon", "Aluminum", "Iron"],
        [3, 4, "Who formulated the Uncertainty Principle?", "Werner Heisenberg", "Niels Bohr", "Max Planck", "Albert Einstein"],
        [3, 4, "What is the pH of human blood roughly?", "7.4", "6.8", "8.2", "7.0"],
        [3, 4, "Which gas is used in the manufacturing of Vanaspati Ghee?", "Hydrogen", "Oxygen", "Nitrogen", "Carbon Dioxide"],
        [3, 5, "Who was the Viceroy of India during the Partition of Bengal (1905)?", "Lord Curzon", "Lord Mountbatten", "Lord Dalhousie", "Lord Ripon"],
        [3, 5, "Which schedule of the Indian Constitution contains languages?", "8th Schedule", "9th Schedule", "7th Schedule", "10th Schedule"],
        [3, 5, "Where is the headquarters of the International Court of Justice?", "The Hague", "Geneva", "New York", "Paris"],
        [3, 5, "Who wrote 'The Wealth of Nations'?", "Adam Smith", "Karl Marx", "John Maynard Keynes", "Amartya Sen"],
        [3, 5, "What is the capital of New Zealand?", "Wellington", "Ottawa", "Auckland", "Sydney"],
        [3, 5, "Which is the deepest lake in the world?", "Lake Baikal", "Lake Superior", "Caspian Sea", "Lake Victoria"],

        // ================================================
        // ADDITIONAL 100 QUESTIONS (Bringing Total to 500)
        // ================================================
        // --- 10th Level (33 Questions) ---
        [1, 1, "Find the value of 5^3", "125", "25", "15", "625"],
        [1, 1, "A triangle with 3 equal sides is called?", "Equilateral", "Isosceles", "Scalene", "Right-angled"],
        [1, 1, "0.5 expressed as a percentage?", "50%", "5%", "0.05%", "500%"],
        [1, 1, "What is 12 * 8?", "96", "84", "108", "92"],
        [1, 1, "Simplify: 10 + 5 * 2", "20", "30", "15", "25"],
        [1, 1, "Number of degrees in a right angle?", "90", "180", "45", "360"],
        [1, 1, "If 4x = 16, what is x?", "4", "2", "8", "12"],
        [1, 2, "Next in series: 3, 6, 9, 12, ?", "15", "14", "16", "18"],
        [1, 2, "Odd one out: Rose, Lily, Sunflower, Brick", "Brick", "Rose", "Lily", "Sunflower"],
        [1, 2, "If today is Friday, tomorrow is?", "Saturday", "Sunday", "Thursday", "Monday"],
        [1, 2, "Opposite of 'In' is?", "Out", "Under", "Above", "Beside"],
        [1, 2, "Book is to Read as Pen is to?", "Write", "Draw", "Ink", "Paper"],
        [1, 2, "If A=1, B=2, C=3, then D=?", "4", "5", "6", "7"],
        [1, 2, "Which is heavier: 1kg iron or 1kg cotton?", "Both equal", "Iron", "Cotton", "Depends"],
        [1, 3, "Synonym of START?", "Begin", "End", "Stop", "Pause"],
        [1, 3, "Antonym of UP?", "Down", "High", "Tall", "Above"],
        [1, 3, "Plural of Dog?", "Dogs", "Doges", "Dog", "Dogies"],
        [1, 3, "Identify the noun: 'The red car'", "Car", "The", "Red", "Is"],
        [1, 3, "Identify the verb: 'She sings sweetly'", "Sings", "She", "Sweetly", "The"],
        [1, 3, "Rhymes with BOAT?", "Coat", "Dog", "Bat", "Cat"],
        [1, 4, "What do bees produce?", "Honey", "Milk", "Silk", "Wool"],
        [1, 4, "Which part of plant absorbs water?", "Roots", "Leaves", "Stem", "Flower"],
        [1, 4, "What gas do humans exhale?", "Carbon Dioxide", "Oxygen", "Nitrogen", "Helium"],
        [1, 4, "What makes blood red?", "Hemoglobin", "Plasma", "Water", "Platelets"],
        [1, 4, "Ice melts into?", "Water", "Steam", "Gas", "Vapor"],
        [1, 4, "Sun is a?", "Star", "Planet", "Asteroid", "Comet"],
        [1, 5, "Capital of USA?", "Washington DC", "New York", "Los Angeles", "Chicago"],
        [1, 5, "Who built the Pyramids?", "Egyptians", "Romans", "Greeks", "Mayans"],
        [1, 5, "How many continents are there?", "7", "6", "5", "8"],
        [1, 5, "First man on the moon?", "Neil Armstrong", "Buzz Aldrin", "Yuri Gagarin", "Michael Collins"],
        [1, 5, "Largest mammal?", "Blue Whale", "Elephant", "Giraffe", "Shark"],
        [1, 5, "Colors in Indian Flag?", "3 plus navy blue wheel", "2", "4", "5"],
        [1, 5, "Independence day of USA?", "July 4", "July 14", "June 4", "August 15"],

        // --- Intermediate Level (33 Questions) ---
        [2, 1, "Log10(1000) = ?", "3", "2", "10", "4"],
        [2, 1, "Derivative of 5x^2?", "10x", "5x", "10", "x^2"],
        [2, 1, "Integral of 3x^2 dx?", "x^3", "3x^3", "x^2", "6x"],
        [2, 1, "sin^2(x) + cos^2(x) = ?", "1", "0", "-1", "2"],
        [2, 1, "Factorial of 4 (4!)?", "24", "12", "16", "20"],
        [2, 1, "Equation of a straight line?", "y = mx + c", "y = ax^2 + bx + c", "x^2 + y^2 = r^2", "y = 1/x"],
        [2, 1, "Probability of an impossible event?", "0", "1", "0.5", "-1"],
        [2, 2, "Next in series: 1, 8, 27, 64, ?", "125", "100", "216", "81"],
        [2, 2, "If Apple=5, Banana=6, Cherry=?", "6", "5", "7", "8"],
        [2, 2, "All birds can fly. Penguin is a bird. Conclusion: Penguin can fly. Valid?", "Yes, structurally", "No", "Maybe", "Invalid premises"],
        [2, 2, "Odd one out: Triangle, Square, Pentagon, Circle", "Circle", "Triangle", "Square", "Pentagon"],
        [2, 2, "If pointing to a man, a woman says 'He is my father's brother'. He is her?", "Uncle", "Father", "Cousin", "Brother"],
        [2, 2, "Angle between clock hands at 6:00?", "180°", "90°", "360°", "0°"],
        [2, 3, "Synonym of MELANCHOLY?", "Sad", "Happy", "Angry", "Excited"],
        [2, 3, "Antonym of BENIGN?", "Harmful", "Gentle", "Kind", "Safe"],
        [2, 3, "'Spill the beans' means?", "Reveal a secret", "Drop food", "Get angry", "Clean up"],
        [2, 3, "Plural of Crisis?", "Crises", "Crisises", "Crisi", "Crisises"],
        [2, 3, "A person who does not believe in God?", "Atheist", "Theist", "Agnostic", "Zealot"],
        [2, 3, "Synonym of ENORMOUS?", "Huge", "Tiny", "Average", "Small"],
        [2, 3, "Identify adjective: 'The fierce storm'", "Fierce", "The", "Storm", "None"],
        [2, 4, "Chemical formula for table sugar (Sucrose)?", "C12H22O11", "C6H12O6", "NaCl", "CH4"],
        [2, 4, "Unit of Capacitance?", "Farad", "Henry", "Tesla", "Ohm"],
        [2, 4, "What is the speed of light in vacuum?", "3x10^8 m/s", "3x10^5 m/s", "3x10^6 m/s", "3x10^10 m/s"],
        [2, 4, "Which planet rotates on its side?", "Uranus", "Venus", "Mars", "Jupiter"],
        [2, 4, "Who proposed the theory of evolution?", "Charles Darwin", "Isaac Newton", "Albert Einstein", "Gregor Mendel"],
        [2, 4, "Study of Earth's physical structure?", "Geology", "Biology", "Meteorology", "Astronomy"],
        [2, 4, "What is Avogadro's number roughly?", "6.022 x 10^23", "3.1415", "1.618", "9.81"],
        [2, 5, "Who painted the Mona Lisa?", "Leonardo da Vinci", "Vincent van Gogh", "Pablo Picasso", "Michelangelo"],
        [2, 5, "Capital of Japan?", "Tokyo", "Kyoto", "Osaka", "Seoul"],
        [2, 5, "Highest mountain in Africa?", "Mount Kilimanjaro", "Mount Kenya", "Mount Elgon", "Mount Everest"],
        [2, 5, "In which year did Titanic sink?", "1912", "1905", "1920", "1915"],
        [2, 5, "Who wrote 'Romeo and Juliet'?", "William Shakespeare", "Charles Dickens", "Jane Austen", "Mark Twain"],
        [2, 5, "Currency of Russia?", "Ruble", "Yen", "Euro", "Peso"],

        // --- Graduation Level (34 Questions) ---
        [3, 1, "Limit of (sin x)/x as x approaches 0?", "1", "0", "Infinity", "-1"],
        [3, 1, "Determinant of a 3x3 identity matrix?", "1", "0", "3", "9"],
        [3, 1, "Derivative of e^(2x)?", "2e^(2x)", "e^(2x)", "x*e^(2x)", "2xe^(2x)"],
        [3, 1, "Sum of interior angles in a hexagon?", "720°", "540°", "360°", "1080°"],
        [3, 1, "Value of 0! (0 factorial)?", "1", "0", "Undefined", "-1"],
        [3, 1, "Solve for x: log(x) = 2 (base 10)", "100", "10", "2", "1000"],
        [3, 1, "Variance of a uniform distribution (a,b)?", "(b-a)^2 / 12", "(b-a)/2", "(a+b)/2", "(b-a)^2 / 6"],
        [3, 2, "If all cats are animals, and some animals are dogs. Are some cats dogs?", "Not necessarily", "Yes", "No", "Always"],
        [3, 2, "A clock loses 5 mins every hour. Set right at 12 noon. What time will it show at 6 PM?", "5:30 PM", "6:30 PM", "5:00 PM", "5:45 PM"],
        [3, 2, "If 3 cats catch 3 mice in 3 minutes, how many cats to catch 100 mice in 100 minutes?", "3", "100", "33", "99"],
        [3, 2, "Missing in sequence: 1, 1, 2, 6, 24, ?", "120", "100", "96", "144"],
        [3, 2, "Statement: 'All cars are green'. Assumption: 'My car is green'.", "Valid", "Invalid", "Cannot determine", "Paradox"],
        [3, 2, "Find the next term: 2, 5, 11, 23, 47, ?", "95", "94", "96", "97"],
        [3, 2, "Odd one out: CPU, RAM, Hard Drive, Monitor", "Monitor", "CPU", "RAM", "Hard Drive"],
        [3, 3, "Synonym of 'SAGACIOUS'?", "Wise", "Foolish", "Angry", "Bitter"],
        [3, 3, "Antonym of 'OBDURATE'?", "Yielding", "Stubborn", "Firm", "Hard"],
        [3, 3, "Meaning of 'A blessing in disguise'?", "Good thing that seemed bad at first", "A curse", "A hidden enemy", "A magic trick"],
        [3, 3, "Which is a palindrome?", "Racecar", "Apple", "Table", "House"],
        [3, 3, "Identify the figure of speech: 'Jumbo shrimp'", "Oxymoron", "Simile", "Metaphor", "Hyperbole"],
        [3, 3, "Synonym of 'COGNIZANT'?", "Aware", "Ignorant", "Careless", "Blind"],
        [3, 3, "Antonym of 'TREPIDATION'?", "Bravery", "Fear", "Anxiety", "Dread"],
        [3, 4, "What is the principle of a hydrogen bomb?", "Nuclear Fusion", "Nuclear Fission", "Chemical Reaction", "Radioactivity"],
        [3, 4, "What does the Higgs mechanism explain?", "Origin of mass", "Speed of light", "Gravity", "Electromagnetism"],
        [3, 4, "What is the most common isotope of carbon?", "Carbon-12", "Carbon-14", "Carbon-13", "Carbon-10"],
        [3, 4, "Who discovered the electron?", "J.J. Thomson", "Ernest Rutherford", "Niels Bohr", "James Chadwick"],
        [3, 4, "What is the primary function of ribosomes?", "Protein synthesis", "Energy production", "DNA replication", "Lipid storage"],
        [3, 4, "Which phylum do insects belong to?", "Arthropoda", "Mollusca", "Annelida", "Chordata"],
        [3, 5, "Who was the first Secretary-General of the UN?", "Trygve Lie", "Dag Hammarskjöld", "Kofi Annan", "Ban Ki-moon"],
        [3, 5, "What is the capital of Argentina?", "Buenos Aires", "Wellington", "Santiago", "Lima"],
        [3, 5, "Which treaty ended World War I?", "Treaty of Versailles", "Treaty of Paris", "Treaty of Tordesillas", "Treaty of Ghent"],
        [3, 5, "Who developed the Polio vaccine?", "Jonas Salk", "Alexander Fleming", "Edward Jenner", "Louis Pasteur"],
        [3, 5, "In what year did the Soviet Union collapse?", "1991", "1989", "1993", "1985"],
        [3, 5, "Deepest known point in the Earth's oceans?", "Mariana Trench", "Tonga Trench", "Puerto Rico Trench", "Java Trench"],
        [3, 5, "Which economist wrote 'The General Theory of Employment, Interest and Money'?", "John Maynard Keynes", "Adam Smith", "Karl Marx", "Milton Friedman"]
    ];

    // --- Dynamic Data Expander Engine ---
    // Unrolls exactly 500 highly detailed questions into the format the engine needs!
    const levels = {1: "10th Level", 2: "Intermediate Level", 3: "Graduation Level"};
    const traits = {
        1: {m: "Numerical Ability", t: "numerical"},
        2: {m: "Logical Reasoning", t: "logical"},
        3: {m: "Verbal Ability", t: "verbal"},
        4: {m: "General Science", t: "general_awareness"},
        5: {m: "General Studies", t: "general_awareness"}
    };

    return raw.map(q => {
        let opts = [
            { text: String(q[3]), val: 5 }, // Correct answer
            { text: String(q[4]), val: 0 }, // Wrong answer 1
            { text: String(q[5]), val: 0 }, // Wrong answer 2
            { text: String(q[6]), val: 0 }  // Wrong answer 3
        ];
        
        // Advanced Feature: Automatically shuffle options
        for (let i = opts.length - 1; i > 0; i--) {
            const j = Math.floor(Math.random() * (i + 1));
            [opts[i], opts[j]] = [opts[j], opts[i]];
        }
        
        return {
            module: traits[q[1]].m, 
            text: String(q[2]), 
            trait: traits[q[1]].t,
            traitType: "aptitude", 
            type: "mcq", 
            qualifications: [levels[q[0]]], 
            options: opts
        };
    });
})();