const govtJobDatabase = [
    // === ORIGINAL 50 JOBS ===
    { title: "IAS Officer (UPSC)", desc: "Top-tier administration, policy-making, and district management.", reqs: { general_awareness: 90, logical: 85, enterprising: 90, social: 80, conscientiousness: 90 } },
    { title: "IPS Officer (UPSC)", desc: "Senior law enforcement, commanding police forces and public safety.", reqs: { logical: 80, realistic: 85, enterprising: 90, emotional_stability: 95 } },
    { title: "IFS Officer (Foreign Service)", desc: "Diplomacy, international relations, and representing India abroad.", reqs: { verbal: 90, general_awareness: 90, social: 85, enterprising: 80 } },
    { title: "IRS Officer (Customs/Tax)", desc: "Revenue management, tax administration, and financial investigations.", reqs: { numerical: 85, logical: 80, conventional: 90, investigative: 85 } },
    { title: "State PCS Officer (SDM/DSP)", desc: "State-level administration and law enforcement equivalent to IAS/IPS.", reqs: { general_awareness: 85, logical: 80, enterprising: 85, social: 80 } },
    { title: "SSC CGL Income Tax Inspector", desc: "Assessing tax returns, conducting raids, and anti-evasion work.", reqs: { numerical: 90, logical: 85, investigative: 85, conventional: 85 } },
    { title: "SSC CGL Examiner (Customs)", desc: "Examining cargo, preventing smuggling, stationed at ports/airports.", reqs: { numerical: 80, logical: 85, realistic: 80, conventional: 85 } },
    { title: "SSC CGL ASO (CSS/MEA)", desc: "Desk job in Central Secretariat or Ministry of External Affairs.", reqs: { verbal: 85, logical: 80, conventional: 90, conscientiousness: 85 } },
    { title: "SSC CGL Preventive Officer", desc: "Active field job to prevent smuggling and illegal trades.", reqs: { logical: 80, realistic: 85, investigative: 85, emotional_stability: 85 } },
    { title: "SSC CGL Auditor (CGDA)", desc: "Auditing government accounts and financial record keeping.", reqs: { numerical: 85, conventional: 95, conscientiousness: 90 } },
    { title: "SSC CHSL LDC/JSA", desc: "Clerical duties, data management, and file routing in ministries.", reqs: { numerical: 75, verbal: 75, conventional: 90, conscientiousness: 80 } },
    { title: "SSC CHSL Data Entry Operator", desc: "High-speed typing and maintaining critical government databases.", reqs: { logical: 70, conventional: 95, realistic: 75 } },
    { title: "SSC MTS (Multi-Tasking Staff)", desc: "General assisting roles, file maintenance, and daily operations.", reqs: { logical: 65, conventional: 80, realistic: 80 } },
    { title: "SBI Probationary Officer (PO)", desc: "Branch management, credit appraisal, and high-pressure banking.", reqs: { numerical: 90, logical: 90, enterprising: 85, conscientiousness: 85 } },
    { title: "IBPS Probationary Officer (PO)", desc: "Managing operations across nationalized public sector banks.", reqs: { numerical: 85, logical: 85, enterprising: 80, conventional: 80 } },
    { title: "RBI Grade B Officer", desc: "Policy drafting, economic regulation, and financial stability.", reqs: { numerical: 90, general_awareness: 90, investigative: 85, conventional: 85 } },
    { title: "NABARD Grade A Officer", desc: "Rural development, agriculture financing, and cooperative banking.", reqs: { general_awareness: 85, social: 85, investigative: 80, conventional: 80 } },
    { title: "SBI/IBPS Clerk", desc: "Customer interaction, cash handling, and daily banking operations.", reqs: { numerical: 85, verbal: 80, conventional: 90, social: 80 } },
    { title: "LIC Assistant Administrative Officer", desc: "Insurance policy processing, claims, and administrative work.", reqs: { numerical: 80, logical: 80, conventional: 85, enterprising: 75 } },
    { title: "RRB NTPC Station Master", desc: "Managing railway station operations, signals, and train movements.", reqs: { logical: 85, realistic: 85, conventional: 85, emotional_stability: 90 } },
    { title: "RRB NTPC Goods Guard", desc: "In-charge of freight trains, ensuring safe transit of goods.", reqs: { realistic: 90, conventional: 80, emotional_stability: 85 } },
    { title: "RRB Assistant Loco Pilot (ALP)", desc: "Driving passenger and freight trains with high technical focus.", reqs: { realistic: 95, logical: 80, conventional: 80, emotional_stability: 95 } },
    { title: "RRB Ticket Examiner (TTE)", desc: "Checking tickets, guiding passengers, handling fines on trains.", reqs: { verbal: 80, social: 85, enterprising: 80, conventional: 80 } },
    { title: "RRB Group D (Track Maintainer)", desc: "Heavy physical work maintaining railway tracks and infrastructure.", reqs: { realistic: 95, conventional: 75 } },
    { title: "NDA Army Officer (Lieutenant)", desc: "Leading combat troops, defense strategy, and national security.", reqs: { logical: 85, realistic: 95, enterprising: 95, emotional_stability: 95 } },
    { title: "CDS Defense Officer", desc: "Post-graduate entry into Armed Forces leading platoons/companies.", reqs: { logical: 85, realistic: 90, enterprising: 90, social: 80 } },
    { title: "Indian Navy Sailor / Air Force Airman", desc: "Technical and combat operations aboard ships or air bases.", reqs: { realistic: 95, conventional: 80, logical: 80 } },
    { title: "State Police Sub-Inspector (SI)", desc: "Investigating crimes, filing FIRs, and maintaining local law & order.", reqs: { logical: 80, realistic: 85, investigative: 85, enterprising: 85 } },
    { title: "State Police Constable", desc: "First response, patrolling, and ground-level security.", reqs: { realistic: 90, conventional: 80, social: 75 } },
    { title: "CAPF Assistant Commandant", desc: "Leading paramilitary forces (CRPF, BSF) in border/internal security.", reqs: { realistic: 90, enterprising: 90, logical: 80, emotional_stability: 90 } },
    { title: "BSF / CRPF Constable", desc: "Border guarding, riot control, and national security duties.", reqs: { realistic: 95, conventional: 85 } },
    { title: "Intelligence Bureau (IB) ACIO", desc: "Gathering intel, counter-terrorism, and deep undercover work.", reqs: { logical: 90, investigative: 95, general_awareness: 90, emotional_stability: 90 } },
    { title: "RAW Officer (Research & Analysis)", desc: "Foreign intelligence, espionage, and international threat analysis.", reqs: { logical: 95, investigative: 95, general_awareness: 95, emotional_stability: 95 } },
    { title: "CBI Officer (Sub-Inspector)", desc: "High-profile anti-corruption and special crime investigations.", reqs: { logical: 90, investigative: 90, realistic: 80, conscientiousness: 90 } },
    { title: "UGC NET Assistant Professor", desc: "Teaching at universities, conducting academic research.", reqs: { verbal: 90, general_awareness: 85, investigative: 90, social: 85 } },
    { title: "KVS PGT (Post Graduate Teacher)", desc: "Teaching senior secondary classes in central government schools.", reqs: { verbal: 85, social: 90, conventional: 80 } },
    { title: "KVS TGT (Trained Graduate Teacher)", desc: "Teaching middle school students with subject specialization.", reqs: { verbal: 80, social: 90, conventional: 80 } },
    { title: "Primary School Teacher (PRT)", desc: "Foundational education and child development.", reqs: { verbal: 80, social: 95, artistic: 75, agreeableness: 90 } },
    { title: "ISRO / DRDO Scientist", desc: "Advanced space and defense technology research and engineering.", reqs: { numerical: 90, logical: 95, investigative: 95, realistic: 85 } },
    { title: "SSC Junior Engineer (JE)", desc: "Supervising public works, civil/electrical government projects.", reqs: { numerical: 85, logical: 85, realistic: 90, conventional: 85 } },
    { title: "State Assistant Engineer (AE)", desc: "Managing state-level infrastructure and engineering developments.", reqs: { numerical: 85, logical: 80, realistic: 85, conventional: 85 } },
    { title: "Government Medical Officer (CMO)", desc: "Public health administration and clinical practice in govt hospitals.", reqs: { logical: 85, investigative: 90, social: 90, conscientiousness: 95 } },
    { title: "Military Nursing Service (MNS)", desc: "Providing healthcare to armed forces personnel and their families.", reqs: { realistic: 80, social: 95, emotional_stability: 90, agreeableness: 90 } },
    { title: "Railway Pharmacist", desc: "Dispensing medicines and maintaining pharmacy stocks for railways.", reqs: { logical: 80, conventional: 90, social: 80 } },
    { title: "Civil Judge (State Judiciary)", desc: "Presiding over civil and criminal cases in district courts.", reqs: { verbal: 90, logical: 90, investigative: 85, conscientiousness: 95 } },
    { title: "Public Prosecutor (APP)", desc: "Representing the state in criminal trials.", reqs: { verbal: 90, logical: 85, enterprising: 85, investigative: 80 } },
    { title: "Forest Ranger (State Forest Service)", desc: "Protecting wildlife, preventing poaching, and managing forests.", reqs: { realistic: 90, investigative: 80, conventional: 80 } },
    { title: "Patwari / Lekhpal", desc: "Maintaining village land records and agricultural data.", reqs: { numerical: 80, conventional: 95, realistic: 75 } },
    { title: "Village Development Officer (VDO)", desc: "Executing rural development schemes at the panchayat level.", reqs: { general_awareness: 80, social: 85, enterprising: 80, conventional: 80 } },
    { title: "EPFO Assistant", desc: "Managing provident fund claims, accounts, and employee benefits.", reqs: { numerical: 85, logical: 80, conventional: 90, conscientiousness: 85 } },

    // === 50 JOBS (Added 1-50: UPSC, State PSC, Banking, SSC, Subordinate) ===
    { title: "Indian Railway Traffic Service (IRTS)", desc: "Managing logistics, passenger transport, and vast railway networks.", reqs: { logical: 90, enterprising: 85, conventional: 85, general_awareness: 80 } },
    { title: "Indian Postal Service (IPoS)", desc: "Administration of the massive national postal and mail network.", reqs: { conventional: 90, enterprising: 80, conscientiousness: 85 } },
    { title: "Indian Audit and Accounts Service (IA&AS)", desc: "Supreme auditing of government accounts and state expenditures.", reqs: { numerical: 90, conventional: 95, conscientiousness: 95 } },
    { title: "Indian Corporate Law Service (ICLS)", desc: "Enforcing corporate laws and regulatory frameworks in business.", reqs: { verbal: 85, logical: 90, investigative: 80 } },
    { title: "State Excise Inspector", desc: "Regulating liquor, preventing illegal trade, and collecting state taxes.", reqs: { logical: 80, realistic: 80, investigative: 85, enterprising: 80 } },
    { title: "Block Development Officer (BDO)", desc: "Overseeing rural development programs at the block level.", reqs: { social: 85, enterprising: 85, general_awareness: 80 } },
    { title: "Regional Transport Officer (RTO)", desc: "Enforcing motor vehicle laws, issuing licenses, and collecting road tax.", reqs: { conventional: 85, realistic: 80, enterprising: 80 } },
    { title: "Tehsildar / Revenue Officer", desc: "Managing land records, dispute resolutions, and local tax collection.", reqs: { conventional: 90, numerical: 80, social: 80 } },
    { title: "Commercial Tax Officer", desc: "Ensuring business tax compliance and revenue collection for the state.", reqs: { numerical: 85, conventional: 90, investigative: 80 } },
    { title: "Municipal Commissioner", desc: "Urban planning, sanitation, and complete municipal administration.", reqs: { enterprising: 90, social: 85, logical: 85, conscientiousness: 90 } },
    { title: "RBI Assistant", desc: "Clerical duties, data entry, and record keeping at the central bank.", reqs: { numerical: 85, conventional: 90, conscientiousness: 85 } },
    { title: "SEBI Grade A Officer", desc: "Regulating the stock market and financial securities.", reqs: { numerical: 90, investigative: 90, logical: 85 } },
    { title: "IBPS Specialist Officer (IT)", desc: "Managing banking technology, servers, and cybersecurity.", reqs: { logical: 90, investigative: 85, realistic: 80 } },
    { title: "IBPS Specialist Officer (Law)", desc: "Handling legal compliance, suits, and contracts for banks.", reqs: { verbal: 90, logical: 85, conventional: 85 } },
    { title: "IBPS Specialist Officer (Agriculture)", desc: "Managing rural agricultural loans and farming schemes.", reqs: { realistic: 80, social: 80, investigative: 85 } },
    { title: "LIC Apprentice Development Officer (ADO)", desc: "Recruiting agents, driving insurance sales, and marketing.", reqs: { enterprising: 95, social: 85, verbal: 80 } },
    { title: "NIACL Administrative Officer (AO)", desc: "Managing general insurance claims, underwriting, and policies.", reqs: { numerical: 85, logical: 85, conventional: 85 } },
    { title: "EPFO Social Security Assistant (SSA)", desc: "Managing pension data entry, claim settlements, and queries.", reqs: { numerical: 80, conventional: 90, conscientiousness: 85 } },
    { title: "SIDBI Grade A Officer", desc: "Financing and promoting Micro, Small and Medium Enterprises (MSMEs).", reqs: { numerical: 85, investigative: 85, enterprising: 80 } },
    { title: "IPPB Executive (India Post)", desc: "Promoting digital banking and financial inclusion in rural areas.", reqs: { social: 85, enterprising: 80, conventional: 80 } },
    { title: "SSC CPO Sub-Inspector", desc: "Law enforcement and maintaining security in Delhi Police and CAPFs.", reqs: { realistic: 90, logical: 80, enterprising: 85, emotional_stability: 90 } },
    { title: "SSC GD Constable", desc: "Ground duty, border guarding, and internal security in paramilitary.", reqs: { realistic: 95, conventional: 80, emotional_stability: 85 } },
    { title: "SSC Stenographer", desc: "High-speed shorthand, transcription, and minister assistance.", reqs: { conventional: 95, verbal: 85, conscientiousness: 90 } },
    { title: "SSC Junior Hindi Translator (JHT)", desc: "Translating official documents between English and Hindi.", reqs: { verbal: 95, artistic: 75, conventional: 85 } },
    { title: "SSC Scientific Assistant (IMD)", desc: "Tracking weather patterns and climate data for the Met Department.", reqs: { logical: 90, investigative: 90, realistic: 80 } },
    { title: "Postal Assistant (PA/SA)", desc: "Sorting mail, handling customer queries, and post office management.", reqs: { conventional: 90, numerical: 75, conscientiousness: 80 } },
    { title: "IB Security Assistant", desc: "Supporting intelligence gathering and confidential field ops.", reqs: { investigative: 90, logical: 85, realistic: 80 } },
    { title: "CBI Public Prosecutor", desc: "Prosecuting high-profile anti-corruption and major crime cases.", reqs: { verbal: 90, investigative: 90, logical: 85 } },
    { title: "CSS Section Officer", desc: "Managing administration, files, and staff in central ministries.", reqs: { conventional: 95, logical: 80, conscientiousness: 90 } },
    { title: "Election Commission Assistant", desc: "Managing voter databases, polling schedules, and election logistics.", reqs: { conventional: 90, social: 80, general_awareness: 85 } },
    { title: "Parliamentary Reporter", desc: "Accurately recording and transcribing parliamentary debates.", reqs: { verbal: 95, conventional: 85, conscientiousness: 90 } },
    { title: "AFHQ Assistant", desc: "Clerical and administrative support at Armed Forces Headquarters.", reqs: { conventional: 90, conscientiousness: 90 } },
    { title: "Surveyor General of India Surveyor", desc: "Conducting topographical mapping and land surveys.", reqs: { realistic: 90, investigative: 80, numerical: 80 } },
    { title: "Customs Appraiser", desc: "Assessing the value of imported/exported cargo for tax purposes.", reqs: { investigative: 85, numerical: 85, conventional: 85 } },
    { title: "NCB Inspector", desc: "Investigating and preventing illegal narcotics and drug trafficking.", reqs: { investigative: 95, realistic: 85, emotional_stability: 90 } },
    { title: "RRB Junior Engineer (JE)", desc: "Maintaining railway tracks, bridges, and signal engineering.", reqs: { realistic: 90, logical: 85, conventional: 80 } },
    { title: "RRB Section Engineer", desc: "Senior technical supervision of railway infrastructure projects.", reqs: { realistic: 85, logical: 90, enterprising: 80 } },
    { title: "RRB Staff Nurse", desc: "Providing medical care to railway employees in rail hospitals.", reqs: { social: 90, realistic: 80, agreeableness: 90 } },
    { title: "RRB Commercial Apprentice", desc: "Managing freight, passenger marketing, and commercial rail ops.", reqs: { enterprising: 85, conventional: 85, numerical: 80 } },
    { title: "RRB Traffic Assistant", desc: "Monitoring and managing train traffic and signal control.", reqs: { logical: 85, realistic: 80, conscientiousness: 85 } },
    { title: "RRB RPF Sub-Inspector", desc: "Leading platoons to protect railway property and passengers.", reqs: { realistic: 90, enterprising: 85, emotional_stability: 90 } },
    { title: "RRB RPF Constable", desc: "Patrolling trains and platforms for railway security.", reqs: { realistic: 95, conventional: 85 } },
    { title: "Metro Rail Train Operator", desc: "Driving and monitoring automated city metro trains.", reqs: { realistic: 90, conscientiousness: 95, emotional_stability: 90 } },
    { title: "Metro Rail Station Controller", desc: "Overall management of a metro station's operations and safety.", reqs: { enterprising: 80, conventional: 85, social: 80 } },
    { title: "Port Trust Officer", desc: "Managing shipping logistics, cargo loading, and port regulations.", reqs: { conventional: 85, enterprising: 85, realistic: 80 } },
    { title: "AAI Junior Exec (Air Traffic Control)", desc: "Guiding aircraft, managing airspace, and preventing collisions.", reqs: { logical: 95, numerical: 85, conscientiousness: 95, emotional_stability: 95 } },
    { title: "AAI Commercial Executive", desc: "Managing retail, advertising, and marketing spaces inside airports.", reqs: { enterprising: 90, conventional: 80, verbal: 80 } },
    { title: "DGCA Flight Operations Inspector", desc: "Auditing airlines to ensure strict compliance with aviation safety.", reqs: { investigative: 90, realistic: 85, conventional: 85 } },
    { title: "NHAI Engineer", desc: "Planning and constructing national highways and road networks.", reqs: { realistic: 90, logical: 85, numerical: 80 } },
    { title: "Inland Waterways Authority Officer", desc: "Managing river transport, cargo movement, and waterway logistics.", reqs: { realistic: 85, conventional: 80, investigative: 75 } },

    // === 50 JOBS (Added 51-100: Defense, Ed, Tech, PSU, Health, Law, Media) ===
    { title: "Indian Army Soldier (General Duty)", desc: "Frontline combat, infantry operations, and national defense.", reqs: { realistic: 95, emotional_stability: 95, agreeableness: 80 } },
    { title: "Indian Army Technical Soldier", desc: "Maintaining military equipment, signals, and battlefield engineering.", reqs: { realistic: 90, logical: 85, numerical: 80 } },
    { title: "Indian Army Nursing Assistant", desc: "Providing emergency medical support in military hospitals and field.", reqs: { social: 85, realistic: 85, emotional_stability: 90 } },
    { title: "Indian Navy Artificer Apprentice", desc: "Operating and repairing complex technical systems on warships.", reqs: { realistic: 90, logical: 85, conscientiousness: 85 } },
    { title: "Indian Air Force Group X (Tech)", desc: "Advanced aircraft maintenance, electronics, and weapon systems.", reqs: { realistic: 90, logical: 85, numerical: 80 } },
    { title: "Indian Air Force Group Y (Non-Tech)", desc: "Air base administration, logistics, and ground support operations.", reqs: { conventional: 85, realistic: 80, conscientiousness: 85 } },
    { title: "CISF Constable", desc: "Providing security cover to airports, metro stations, and industries.", reqs: { realistic: 90, conventional: 85, conscientiousness: 90 } },
    { title: "CISF Assistant Commandant", desc: "Commanding security details at critical national infrastructure.", reqs: { enterprising: 90, realistic: 85, emotional_stability: 90 } },
    { title: "ITBP Constable", desc: "Patrolling and securing the high-altitude Indo-Tibetan border.", reqs: { realistic: 95, emotional_stability: 90, conscientiousness: 85 } },
    { title: "SSB Head Constable", desc: "Border communications, intelligence, and administrative support.", reqs: { conventional: 85, realistic: 85, conscientiousness: 80 } },
    { title: "Assam Rifles Soldier", desc: "Guarding the Indo-Myanmar border and conducting counter-insurgency.", reqs: { realistic: 95, emotional_stability: 90, conventional: 80 } },
    { title: "Coast Guard Assistant Commandant", desc: "Leading maritime law enforcement, anti-smuggling, and rescue ops.", reqs: { realistic: 90, enterprising: 90, logical: 85 } },
    { title: "Coast Guard Navik", desc: "Executing sea patrols, vessel maintenance, and search & rescue.", reqs: { realistic: 95, conventional: 80, emotional_stability: 85 } },
    { title: "Judge Advocate General (JAG)", desc: "Serving as a legal advisor and prosecuting attorney for the military.", reqs: { verbal: 90, investigative: 85, conventional: 85 } },
    { title: "State Jail Warder", desc: "Managing prison security, inmate discipline, and facility patrols.", reqs: { realistic: 90, emotional_stability: 90, conscientiousness: 85 } },
    { title: "State TET Primary Teacher", desc: "Foundational early childhood education in state government schools.", reqs: { social: 95, artistic: 80, agreeableness: 95 } },
    { title: "Govt Special Education Teacher", desc: "Teaching and assisting differently-abled students in state programs.", reqs: { social: 95, agreeableness: 95, emotional_stability: 90 } },
    { title: "University Vice-Chancellor", desc: "Top executive academic administration for state/central universities.", reqs: { enterprising: 90, social: 85, verbal: 90 } },
    { title: "Anganwadi Supervisor", desc: "Overseeing rural child nutrition, maternal health, and local centers.", reqs: { social: 90, conventional: 80, agreeableness: 85 } },
    { title: "DIET Lecturer", desc: "Training district-level primary teachers and developing curriculum.", reqs: { social: 85, verbal: 85, investigative: 80 } },
    { title: "ONGC Executive Engineer", desc: "Technical operations in offshore/onshore oil and gas exploration.", reqs: { realistic: 90, logical: 90, investigative: 85 } },
    { title: "BHEL Engineer Trainee", desc: "Designing and manufacturing heavy electrical equipment and turbines.", reqs: { realistic: 90, logical: 85, numerical: 85 } },
    { title: "NTPC Shift Charge Engineer", desc: "Managing the continuous operations of major thermal power plants.", reqs: { realistic: 90, logical: 85, conscientiousness: 90 } },
    { title: "IOCL Graduate Engineer", desc: "Overseeing petroleum refinery processing and chemical engineering.", reqs: { realistic: 90, logical: 85, investigative: 80 } },
    { title: "HAL Management Trainee (Tech)", desc: "Aerospace engineering, aircraft manufacturing, and defense R&D.", reqs: { realistic: 90, logical: 90, numerical: 85 } },
    { title: "SAIL Management Trainee", desc: "Supervising metallurgy, blast furnaces, and steel plant operations.", reqs: { realistic: 90, logical: 85, enterprising: 80 } },
    { title: "BARC Scientific Officer", desc: "Conducting highly classified nuclear research and technology dev.", reqs: { investigative: 95, logical: 95, realistic: 85 } },
    { title: "NIC Scientist / Tech Officer", desc: "Developing e-governance software, cyber infrastructure, and networks.", reqs: { logical: 95, investigative: 90, conventional: 80 } },
    { title: "C-DAC Research Engineer", desc: "R&D in advanced computing, supercomputers, and artificial intelligence.", reqs: { logical: 95, investigative: 90, numerical: 90 } },
    { title: "FSSAI Food Safety Officer", desc: "Testing food quality, lab analysis, and ensuring health standards.", reqs: { investigative: 90, logical: 85, conventional: 85 } },
    { title: "AIIMS Nursing Officer", desc: "Delivering advanced patient care in premier central medical institutes.", reqs: { social: 95, realistic: 85, emotional_stability: 90 } },
    { title: "Govt Dental Surgeon", desc: "Providing public dental health services in government medical centers.", reqs: { realistic: 90, social: 85, investigative: 85 } },
    { title: "Ayush Medical Officer", desc: "Practicing traditional medicine (Ayurveda, Yoga, Unani, Siddha, Homeo).", reqs: { social: 90, investigative: 85, realistic: 80 } },
    { title: "Govt Pharmacist", desc: "Managing dispensaries, maintaining drug stocks, and dispensing meds.", reqs: { conventional: 90, logical: 80, conscientiousness: 90 } },
    { title: "Govt Lab Technician", desc: "Conducting pathological testing, blood work, and medical lab analysis.", reqs: { realistic: 85, conventional: 90, investigative: 85 } },
    { title: "Chief Medical Officer (CMO)", desc: "Top-level administration of district health services and hospitals.", reqs: { enterprising: 90, social: 90, logical: 85 } },
    { title: "Agriculture Field Officer (AFO)", desc: "Advising farmers, inspecting crops, and managing agricultural loans.", reqs: { realistic: 85, social: 85, investigative: 80 } },
    { title: "Horticulture Development Officer", desc: "Managing and promoting fruit, vegetable, and floral cultivation.", reqs: { realistic: 85, investigative: 80, artistic: 75 } },
    { title: "Forest Guard", desc: "Protecting timber, preventing poaching, and patrolling forest reserves.", reqs: { realistic: 95, investigative: 75, emotional_stability: 85 } },
    { title: "Wildlife Inspector", desc: "Tracking animal populations and preventing illegal wildlife trade.", reqs: { realistic: 90, investigative: 90, logical: 80 } },
    { title: "Panchayat Secretary", desc: "Executing village council schemes and local rural administration.", reqs: { conventional: 90, social: 85, enterprising: 80 } },
    { title: "High Court Assistant", desc: "Handling legal clerical work, case files, and court administration.", reqs: { conventional: 95, verbal: 85, conscientiousness: 90 } },
    { title: "State Assembly Secretariat Assistant", desc: "Providing clerical and legislative support to state politicians.", reqs: { conventional: 90, verbal: 85, conscientiousness: 85 } },
    { title: "Public Relations Officer (PRO)", desc: "Managing government media, press releases, and public image.", reqs: { verbal: 95, enterprising: 90, social: 90, artistic: 80 } },
    { title: "Prasar Bharati Executive", desc: "Managing technical and program operations for TV/Radio broadcasting.", reqs: { artistic: 85, enterprising: 85, verbal: 85 } },
    { title: "Doordarshan News Reader", desc: "Broadcasting official government news and state information on TV.", reqs: { verbal: 95, social: 85, artistic: 80 } },
    { title: "ASI Archaeologist", desc: "Excavating and preserving national heritage sites and monuments.", reqs: { investigative: 95, realistic: 85, conventional: 80 } },
    { title: "BSI Botanical Scientist", desc: "Researching, discovering, and cataloging India's plant taxonomy.", reqs: { investigative: 90, realistic: 85, logical: 80 } },
    { title: "ZSI Zoological Researcher", desc: "Researching, cataloging, and studying the national animal taxonomy.", reqs: { investigative: 90, realistic: 85, logical: 80 } },
    { title: "Census Statistical Investigator", desc: "Collecting, managing, and interpreting massive demographic data sets.", reqs: { numerical: 90, conventional: 95, investigative: 85 } },

    // === NEW 100 JOBS (Added 101-200: Specialized State, PSU, Scientific, Allied Services) ===
    { title: "SSC CGL Divisional Accountant (CAG)", desc: "Compiling and auditing accounts for state public works departments.", reqs: { numerical: 90, conventional: 95, conscientiousness: 90 } },
    { title: "SSC CGL Inspector (Central Excise)", desc: "Assessing tax liabilities, inspecting manufacturing units, and preventing evasion.", reqs: { investigative: 85, numerical: 85, realistic: 80 } },
    { title: "SSC CGL Assistant Section Officer (Railways)", desc: "Policy drafting and administration inside the Railway Board headquarters.", reqs: { conventional: 90, logical: 85, conscientiousness: 85 } },
    { title: "SSC CGL Assistant Section Officer (AFHQ)", desc: "Civilian administrative duties at Armed Forces Headquarters.", reqs: { conventional: 95, conscientiousness: 90, emotional_stability: 85 } },
    { title: "SSC CGL Sub-Inspector (NIA)", desc: "Investigating major national security threats and counter-terrorism cases.", reqs: { investigative: 95, logical: 90, realistic: 85, emotional_stability: 95 } },
    { title: "SSC CHSL Lower Divisional Clerk (LDC)", desc: "Basic clerical duties, typing, and record maintenance in ministries.", reqs: { conventional: 90, numerical: 75, conscientiousness: 85 } },
    { title: "SSC CHSL Postal Assistant", desc: "Front desk customer service and mail routing in post offices.", reqs: { conventional: 85, social: 80, conscientiousness: 85 } },
    { title: "UPSC CAPF Medical Officer", desc: "Providing primary and trauma healthcare to paramilitary forces in field areas.", reqs: { social: 90, realistic: 85, emotional_stability: 95, investigative: 85 } },
    { title: "UPSC CMS (Combined Medical Services) Officer", desc: "Serving as a medical officer in various central government health schemes.", reqs: { social: 95, investigative: 90, logical: 85, emotional_stability: 90 } },
    { title: "UPSC Geologist", desc: "Conducting geological surveys and mineral exploration for the government.", reqs: { investigative: 95, realistic: 90, logical: 85 } },
    { title: "UPSC Indian Economic Service (IES) Officer", desc: "Formulating economic policies and advising the central government.", reqs: { logical: 95, numerical: 95, investigative: 90, conventional: 85 } },
    { title: "UPSC Indian Statistical Service (ISS) Officer", desc: "Managing national statistical databases and planning surveys.", reqs: { numerical: 95, logical: 90, conventional: 90, conscientiousness: 90 } },
    { title: "Ministry of Defence Civilian Motor Driver", desc: "Driving and maintaining military transport and logistics vehicles.", reqs: { realistic: 95, conscientiousness: 85, emotional_stability: 85 } },
    { title: "Ministry of Home Affairs Intelligence Officer", desc: "Analyzing domestic intelligence and internal security threats.", reqs: { investigative: 95, logical: 90, emotional_stability: 95, general_awareness: 95 } },
    { title: "Central Water Commission Hydrographic Surveyor", desc: "Surveying water bodies, rivers, and coastal areas for infrastructure planning.", reqs: { realistic: 90, investigative: 85, numerical: 85 } },
    { title: "Archaeological Survey of India (ASI) Epigraphist", desc: "Studying, translating, and preserving ancient inscriptions and scripts.", reqs: { investigative: 95, conventional: 85, artistic: 80 } },
    { title: "National Archives of India Archivist", desc: "Preserving, cataloging, and managing historical government documents.", reqs: { conventional: 95, investigative: 85, conscientiousness: 95 } },
    { title: "Ministry of Mines Cartographer", desc: "Designing and updating complex geological and mineral maps.", reqs: { realistic: 85, conventional: 90, logical: 85 } },
    { title: "Enforcement Directorate (ED) Assistant", desc: "Assisting in investigations of money laundering and financial frauds.", reqs: { investigative: 90, logical: 85, numerical: 85, conventional: 85 } },
    { title: "Serious Fraud Investigation Office (SFIO) Inspector", desc: "Investigating complex white-collar crimes and corporate frauds.", reqs: { investigative: 95, numerical: 90, logical: 90, conscientiousness: 90 } },
    { title: "National Human Rights Commission (NHRC) Investigator", desc: "Investigating civil rights violations and drafting human rights reports.", reqs: { investigative: 90, social: 95, verbal: 90, general_awareness: 90 } },
    { title: "Central Pollution Control Board (CPCB) Scientist", desc: "Monitoring environmental data and enforcing pollution control laws.", reqs: { investigative: 90, logical: 85, realistic: 80 } },
    { title: "National Disaster Response Force (NDRF) Rescuer", desc: "Conducting highly dangerous rescue operations during natural disasters.", reqs: { realistic: 95, emotional_stability: 95, social: 85, agreeableness: 85 } },
    { title: "Central Vigilance Commission (CVC) Technical Examiner", desc: "Auditing government projects to prevent corruption and fund leakage.", reqs: { investigative: 95, logical: 90, conventional: 90 } },
    { title: "Aviation Research Centre (ARC) Analyst", desc: "Analyzing aerial and satellite imagery for intelligence purposes.", reqs: { logical: 95, investigative: 95, numerical: 85, general_awareness: 85 } },
    { title: "State PWD Civil Engineer", desc: "Designing and overseeing the construction of state roads and buildings.", reqs: { realistic: 90, logical: 85, numerical: 85, conventional: 80 } },
    { title: "State Electricity Board Lineman", desc: "Maintaining high-voltage electrical lines and power grids in the state.", reqs: { realistic: 95, conventional: 80, conscientiousness: 85 } },
    { title: "State Water Supply Junior Engineer", desc: "Managing water treatment plants and distribution networks.", reqs: { realistic: 85, logical: 85, conventional: 80 } },
    { title: "Civil Supplies Inspector", desc: "Monitoring public distribution systems (PDS) and ration shops.", reqs: { conventional: 85, investigative: 80, social: 80 } },
    { title: "District Employment Officer", desc: "Registering job seekers and managing employment exchanges.", reqs: { social: 90, enterprising: 85, conventional: 85 } },
    { title: "Panchayat Development Officer (PDO)", desc: "Executing state development schemes at the village panchayat level.", reqs: { enterprising: 85, social: 90, general_awareness: 85, conventional: 85 } },
    { title: "Village Administrative Officer (VAO)", desc: "Handling village administration, tax collection, and local records.", reqs: { conventional: 90, social: 85, numerical: 80 } },
    { title: "Revenue Inspector", desc: "Assessing agricultural land yields and verifying property borders.", reqs: { conventional: 85, numerical: 85, investigative: 80 } },
    { title: "Sub-Registrar (Land & Revenue)", desc: "Registering property deeds, marriages, and official state documents.", reqs: { conventional: 95, logical: 85, verbal: 85 } },
    { title: "State Treasury Officer", desc: "Authorizing state expenditures and managing government accounts.", reqs: { numerical: 95, conventional: 95, conscientiousness: 95 } },
    { title: "Food and Civil Supplies Assistant", desc: "Clerical duties managing data for state food security programs.", reqs: { conventional: 90, numerical: 80, conscientiousness: 85 } },
    { title: "State Transport Inspector", desc: "Enforcing transport regulations and inspecting commercial vehicles.", reqs: { realistic: 85, conventional: 85, enterprising: 80 } },
    { title: "Motor Vehicle Inspector (MVI)", desc: "Testing driving skills and certifying vehicle roadworthiness.", reqs: { realistic: 90, logical: 80, conventional: 85 } },
    { title: "Fire Operator / Fireman", desc: "Responding to fire emergencies and conducting rescue operations.", reqs: { realistic: 95, emotional_stability: 95, social: 80 } },
    { title: "State Police Cyber Cell Analyst", desc: "Investigating cybercrimes, hacking, and digital frauds.", reqs: { logical: 95, investigative: 95, conventional: 80 } },
    { title: "State Forensic Science Lab (FSL) Assistant", desc: "Assisting in the chemical and biological analysis of crime scene evidence.", reqs: { investigative: 90, realistic: 80, conventional: 85 } },
    { title: "District Court Typist / Copyist", desc: "Typing legal judgments and copying official court documents.", reqs: { conventional: 95, verbal: 85, conscientiousness: 95 } },
    { title: "Family Court Counselor", desc: "Providing mediation and counseling to families in legal disputes.", reqs: { social: 95, verbal: 90, agreeableness: 95, emotional_stability: 90 } },
    { title: "Labour Inspector", desc: "Ensuring factories and businesses comply with worker safety and wage laws.", reqs: { investigative: 85, social: 85, conventional: 85 } },
    { title: "Cooperative Societies Inspector", desc: "Auditing and regulating local cooperative banks and farming societies.", reqs: { conventional: 90, numerical: 85, social: 80 } },
    { title: "Child Development Project Officer (CDPO)", desc: "Implementing nutrition and early education schemes for children.", reqs: { social: 95, enterprising: 85, conventional: 85 } },
    { title: "Women & Child Welfare Supervisor", desc: "Monitoring grassroots welfare programs for women and children.", reqs: { social: 90, agreeableness: 90, conventional: 85 } },
    { title: "State Tourism Development Executive", desc: "Promoting state tourism, managing info centers, and guiding tourists.", reqs: { enterprising: 90, social: 90, verbal: 90 } },
    { title: "Municipal Corporation Tax Collector", desc: "Collecting property and water taxes for local city governments.", reqs: { conventional: 90, numerical: 85, enterprising: 80 } },
    { title: "Town Planning Officer", desc: "Designing urban layouts and enforcing city zoning regulations.", reqs: { logical: 90, realistic: 85, conventional: 85, artistic: 75 } },
    { title: "Coal India Management Trainee", desc: "Supervising coal mining operations and technical deployments.", reqs: { enterprising: 85, realistic: 90, logical: 85 } },
    { title: "GAIL Executive Trainee (Chemical)", desc: "Managing natural gas processing and chemical plant operations.", reqs: { logical: 90, realistic: 85, numerical: 85 } },
    { title: "HPCL Operations Officer", desc: "Overseeing petroleum storage, distribution, and refinery operations.", reqs: { realistic: 90, logical: 85, conventional: 85 } },
    { title: "BPCL Process Engineer", desc: "Optimizing chemical processes in oil refineries.", reqs: { logical: 95, realistic: 85, numerical: 90 } },
    { title: "Power Grid Corporation (PGCIL) Diploma Trainee", desc: "Maintaining national power transmission grids and substations.", reqs: { realistic: 90, logical: 85, conventional: 80 } },
    { title: "BSNL Junior Telecom Officer (JTO)", desc: "Managing telecommunication networks and broadband services.", reqs: { logical: 90, realistic: 85, numerical: 85 } },
    { title: "MTNL Telecom Electrical Engineer", desc: "Maintaining electrical infrastructure for telecom exchanges.", reqs: { logical: 85, realistic: 90, conventional: 80 } },
    { title: "Food Corporation of India (FCI) Assistant Grade III", desc: "Managing clerical duties, grain procurement, and dispatch.", reqs: { conventional: 90, numerical: 85, conscientiousness: 85 } },
    { title: "FCI Technical Assistant (Quality Control)", desc: "Testing the quality of procured food grains in laboratories.", reqs: { investigative: 85, realistic: 80, conventional: 85 } },
    { title: "National Highways Authority (NHAI) Site Engineer", desc: "On-site supervision of major highway construction projects.", reqs: { realistic: 95, logical: 85, conventional: 80 } },
    { title: "Airports Authority of India (AAI) Fire Services Assistant", desc: "Specialized aircraft rescue and firefighting at airports.", reqs: { realistic: 95, emotional_stability: 95, conscientiousness: 90 } },
    { title: "LIC Housing Finance Assistant", desc: "Processing home loan applications and customer service.", reqs: { numerical: 85, conventional: 90, social: 85 } },
    { title: "NABARD Development Assistant", desc: "Assisting in rural development projects and agricultural financing.", reqs: { conventional: 90, numerical: 85, social: 80 } },
    { title: "EXIM Bank Officer", desc: "Managing export-import financing and international trade loans.", reqs: { numerical: 90, logical: 85, enterprising: 85, conventional: 85 } },
    { title: "National Housing Bank (NHB) Assistant Manager", desc: "Regulating and financing housing finance companies.", reqs: { numerical: 90, conventional: 90, enterprising: 85 } },
    { title: "ECGC Probationary Officer", desc: "Providing export credit insurance and managing trade risks.", reqs: { logical: 90, numerical: 85, conventional: 85 } },
    { title: "IRCTC Ticketing Executive", desc: "Managing train reservations, cancellations, and customer queries.", reqs: { conventional: 90, social: 85, numerical: 80 } },
    { title: "CONCOR Hospitality Manager", desc: "Managing catering and hospitality services on premium trains.", reqs: { social: 90, enterprising: 85, conventional: 80 } },
    { title: "BEML Aerospace Engineer", desc: "Designing and manufacturing defense and aerospace equipment.", reqs: { logical: 95, realistic: 90, numerical: 90 } },
    { title: "Hindustan Shipyard Marine Engineer", desc: "Building and repairing naval warships and submarines.", reqs: { realistic: 95, logical: 90, conventional: 85 } },
    { title: "Mazagon Dock Shipbuilder", desc: "Technical trades working on the construction of naval vessels.", reqs: { realistic: 95, conventional: 85, conscientiousness: 90 } },
    { title: "MECON Heavy Machinery Technician", desc: "Maintaining heavy industrial machinery for steel plants.", reqs: { realistic: 95, conventional: 85, logical: 80 } },
    { title: "National Seed Corporation (NSC) Trainee", desc: "Ensuring the quality and distribution of agricultural seeds.", reqs: { realistic: 85, conventional: 85, investigative: 80 } },
    { title: "Central Warehousing Corporation (CWC) Superintendent", desc: "Managing vast storage warehouses for agricultural and industrial goods.", reqs: { conventional: 90, enterprising: 85, logical: 80 } },
    { title: "NHPC Control Room Operator", desc: "Monitoring hydroelectric power generation in control rooms.", reqs: { realistic: 85, conventional: 90, conscientiousness: 95 } },
    { title: "CSIR Junior Research Fellow (JRF)", desc: "Conducting scientific research under the Council of Scientific and Industrial Research.", reqs: { investigative: 95, logical: 90, verbal: 85 } },
    { title: "ICAR Agricultural Scientist", desc: "Researching crop improvements and sustainable farming techniques.", reqs: { investigative: 95, realistic: 85, logical: 90 } },
    { title: "ICMR Clinical Researcher", desc: "Conducting medical research and epidemiological studies.", reqs: { investigative: 95, logical: 90, social: 80 } },
    { title: "DRDO Technical Assistant (CEPTAM)", desc: "Assisting scientists in defense R&D and weapon testing.", reqs: { realistic: 90, logical: 85, conventional: 85 } },
    { title: "ISRO Technical Assistant", desc: "Supporting the assembly and testing of space launch vehicles.", reqs: { realistic: 90, logical: 90, numerical: 85 } },
    { title: "National Informatics Centre (NIC) Network Engineer", desc: "Maintaining the government's secure internet and server networks.", reqs: { logical: 95, conventional: 85, investigative: 85 } },
    { title: "Meteorological Department (IMD) Observer", desc: "Recording weather data from instruments for forecasting.", reqs: { investigative: 85, conventional: 90, realistic: 80 } },
    { title: "Navodaya Vidyalaya (NVS) Principal", desc: "Administering residential schools for talented rural children.", reqs: { enterprising: 95, social: 90, verbal: 90, conventional: 85 } },
    { title: "Kendriya Vidyalaya (KVS) Librarian", desc: "Managing school libraries and promoting reading habits.", reqs: { conventional: 90, social: 85, verbal: 85 } },
    { title: "Govt Polytechnic Lecturer", desc: "Teaching technical and engineering diploma courses.", reqs: { social: 90, verbal: 85, logical: 85 } },
    { title: "ITI Instructor / Trade Trainer", desc: "Teaching vocational trades like welding, electricity, and mechanics.", reqs: { realistic: 95, social: 85, conventional: 80 } },
    { title: "State Medical Council Drug Inspector", desc: "Inspecting pharmacies and pharmaceutical manufacturing units.", reqs: { investigative: 90, conventional: 90, logical: 85 } },
    { title: "Government Veterinary Officer", desc: "Providing medical care to livestock and managing animal husbandry.", reqs: { investigative: 85, realistic: 90, social: 80 } },
    { title: "Public Health Nurse", desc: "Providing community health services, immunizations, and maternal care.", reqs: { social: 95, realistic: 85, agreeableness: 95 } },
    { title: "Government Physiotherapist", desc: "Providing physical rehabilitation to patients in government hospitals.", reqs: { social: 95, realistic: 85, agreeableness: 90 } },
    { title: "State Hospital Radiographer", desc: "Operating X-Ray, MRI, and CT scan machines.", reqs: { realistic: 90, conventional: 85, investigative: 80 } },
    { title: "Blood Bank Technician", desc: "Testing blood samples, typing blood, and managing storage.", reqs: { conventional: 95, realistic: 85, conscientiousness: 95 } },
    { title: "Central Govt Health Scheme (CGHS) Pharmacist", desc: "Dispensing medicines to central government employees.", reqs: { conventional: 95, social: 85, conscientiousness: 95 } },
    { title: "Railway Hospital Dietician", desc: "Planning nutritional diets for patients in railway hospitals.", reqs: { social: 85, investigative: 85, conventional: 80 } },
    { title: "Sports Authority of India (SAI) Coach", desc: "Training national athletes in specific sports disciplines.", reqs: { social: 90, realistic: 95, enterprising: 90 } },
    { title: "National Institute of Sports (NIS) Physiologist", desc: "Studying athlete performance and physical biomechanics.", reqs: { investigative: 90, logical: 85, realistic: 80 } },
    { title: "Central Institute of Indian Languages (CIIL) Translator", desc: "Translating official documents to preserve linguistic diversity.", reqs: { verbal: 95, artistic: 80, conventional: 85 } },
    { title: "National Museum Curator", desc: "Managing museum exhibits, acquiring artifacts, and organizing displays.", reqs: { investigative: 85, conventional: 85, artistic: 90 } },
    { title: "Film and Television Institute (FTII) Sound Engineer", desc: "Managing audio recording and engineering for government media.", reqs: { artistic: 90, realistic: 85, logical: 80 } },
    { title: "Govt Printing Press Typesetter", desc: "Formatting and printing official government documents and gazettes.", reqs: { conventional: 95, realistic: 85, conscientiousness: 95 } }
];

// If using ES6 modules in future setups
if (typeof module !== 'undefined' && module.exports) {
    module.exports = govtJobDatabase;
}
