const questionsPart1 = [
    // ==========================================
    // MODULE A: APTITUDE & COGNITIVE ABILITY (60 Questions)
    // ==========================================

    // --- Numerical Aptitude (20 Questions) ---
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "What is 20% of 150?", options: [{text:"20", val:0}, {text:"30", val:5}, {text:"40", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "If 3x = 21, what is x?", options: [{text:"6", val:0}, {text:"7", val:5}, {text:"8", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "A car travels 120 miles in 2 hours. What is its average speed?", options: [{text:"50 mph", val:0}, {text:"60 mph", val:5}, {text:"70 mph", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "What is the square root of 144?", options: [{text:"10", val:0}, {text:"12", val:5}, {text:"14", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "If a book costs $15 and is on sale for 10% off, what is the new price?", options: [{text:"$13.50", val:5}, {text:"$14.00", val:0}, {text:"$12.50", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "Solve: 5 + 3 × 4", options: [{text:"32", val:0}, {text:"17", val:5}, {text:"12", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "What is 1/4 as a decimal?", options: [{text:"0.20", val:0}, {text:"0.25", val:5}, {text:"0.40", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "If 4 workers build a shed in 5 days, how many days will it take 10 workers?", options: [{text:"2 days", val:5}, {text:"3 days", val:0}, {text:"4 days", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "What is the perimeter of a rectangle with length 8 and width 3?", options: [{text:"22", val:5}, {text:"24", val:0}, {text:"11", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "If a train is 100 meters long and travels at 36 km/h, how long to pass a pole?", options: [{text:"8 seconds", val:0}, {text:"10 seconds", val:5}, {text:"12 seconds", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "Solve: (12 / 4) + (5 × 2)", options: [{text:"13", val:5}, {text:"16", val:0}, {text:"10", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "What is the next prime number after 11?", options: [{text:"12", val:0}, {text:"13", val:5}, {text:"15", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "If 1 inch = 2.54 cm, how many cm is 10 inches?", options: [{text:"25.4", val:5}, {text:"2.54", val:0}, {text:"254", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "What is 5 cubed (5³)?", options: [{text:"25", val:0}, {text:"125", val:5}, {text:"150", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "A meal costs $40. If you leave a 15% tip, what is the total paid?", options: [{text:"$45", val:0}, {text:"$46", val:5}, {text:"$55", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "Solve for y: 2y - 4 = 10", options: [{text:"6", val:0}, {text:"7", val:5}, {text:"8", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "If a pie is cut into 8 equal slices and you eat 3, what percentage is left?", options: [{text:"37.5%", val:0}, {text:"62.5%", val:5}, {text:"60%", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "What is the least common multiple (LCM) of 4 and 6?", options: [{text:"12", val:5}, {text:"24", val:0}, {text:"10", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "If you flip a fair coin 3 times, what is the probability of getting 3 heads?", options: [{text:"1/4", val:0}, {text:"1/8", val:5}, {text:"1/6", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "Convert 0.75 to a fraction.", options: [{text:"3/4", val:5}, {text:"2/3", val:0}, {text:"4/5", val:0}] },

    // --- Logical Reasoning (20 Questions) ---
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Which number is next: 1, 4, 9, 16, __?", options: [{text:"20", val:0}, {text:"25", val:5}, {text:"30", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Tree is to Leaf as Flower is to...?", options: [{text:"Petal", val:5}, {text:"Root", val:0}, {text:"Stem", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "If all Z are Y, and all Y are X, then are all Z definitely X?", options: [{text:"Yes", val:5}, {text:"No", val:0}, {text:"Maybe", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Which is the odd one out: Dog, Cat, Horse, Snake?", options: [{text:"Snake", val:5}, {text:"Dog", val:0}, {text:"Horse", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "If A > B and B > C, which is true?", options: [{text:"A < C", val:0}, {text:"A > C", val:5}, {text:"A = C", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Next in sequence: A, C, E, G, __?", options: [{text:"H", val:0}, {text:"I", val:5}, {text:"J", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Doctor is to Hospital as Teacher is to...?", options: [{text:"Student", val:0}, {text:"School", val:5}, {text:"Books", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "If DAY is coded as 4125, what does it represent?", options: [{text:"Alphabet Positions", val:5}, {text:"Random Numbers", val:0}, {text:"Reverse Alphabet", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "A woman says, 'His mother is the only daughter of my mother.' How is the woman related to him?", options: [{text:"Aunt", val:0}, {text:"Mother", val:5}, {text:"Sister", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Which comes next: 10, 22, 46, 94, __?", options: [{text:"180", val:0}, {text:"190", val:5}, {text:"196", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Some cars are red. All red things are fast. Are some cars fast?", options: [{text:"Yes", val:5}, {text:"No", val:0}, {text:"Unknown", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Book is to Reading as Fork is to...?", options: [{text:"Kitchen", val:0}, {text:"Eating", val:5}, {text:"Steel", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Find the odd one out: Circle, Square, Triangle, Rectangle.", options: [{text:"Triangle", val:0}, {text:"Circle", val:5}, {text:"Square", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Walk 10m East, turn left, walk 10m. What direction are you facing?", options: [{text:"North", val:5}, {text:"West", val:0}, {text:"South", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Next in sequence: Z, X, V, T, __?", options: [{text:"S", val:0}, {text:"R", val:5}, {text:"Q", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Thermometer is to Temperature as Clock is to...?", options: [{text:"Wall", val:0}, {text:"Time", val:5}, {text:"Gears", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "If Tuesday is the 4th of the month, what day is the 18th?", options: [{text:"Monday", val:0}, {text:"Tuesday", val:5}, {text:"Wednesday", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "All birds have wings. A penguin is a bird. Does a penguin have wings?", options: [{text:"Yes", val:5}, {text:"No", val:0}, {text:"Maybe", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Which number does not belong: 2, 3, 5, 8, 11, 13?", options: [{text:"8", val:5}, {text:"11", val:0}, {text:"13", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "If CAT is 24, DOG is 26, then BIRD is?", options: [{text:"30", val:0}, {text:"38", val:5}, {text:"40", val:0}] },

    // --- Verbal Reasoning (20 Questions) ---
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Choose the synonym for 'LUCID':", options: [{text:"Confusing", val:0}, {text:"Clear", val:5}, {text:"Dark", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Choose the antonym for 'EXPAND':", options: [{text:"Shrink", val:5}, {text:"Grow", val:0}, {text:"Build", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Which word means 'to put off until later'?", options: [{text:"Accelerate", val:0}, {text:"Procrastinate", val:5}, {text:"Execute", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Complete the analogy: Hot is to Cold as High is to...?", options: [{text:"Low", val:5}, {text:"Tall", val:0}, {text:"Sky", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Which is correctly spelled?", options: [{text:"Accomodate", val:0}, {text:"Accommodate", val:5}, {text:"Acomodate", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "A person who studies rocks is a...?", options: [{text:"Biologist", val:0}, {text:"Geologist", val:5}, {text:"Astronomer", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Choose the synonym for 'VITAL':", options: [{text:"Optional", val:0}, {text:"Essential", val:5}, {text:"Useless", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "What is the plural of 'Radius'?", options: [{text:"Radiuses", val:0}, {text:"Radii", val:5}, {text:"Radius", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "An 'Oculist' specializes in treating...?", options: [{text:"Bones", val:0}, {text:"Eyes", val:5}, {text:"Skin", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Choose the antonym for 'BENIGN':", options: [{text:"Harmless", val:0}, {text:"Malignant", val:5}, {text:"Gentle", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Find the odd word: Joy, Happiness, Sorrow, Delight.", options: [{text:"Sorrow", val:5}, {text:"Joy", val:0}, {text:"Delight", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "What does 'Omnipresent' mean?", options: [{text:"All-knowing", val:0}, {text:"Present everywhere", val:5}, {text:"All-powerful", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Which word is a verb? (Beautiful, Run, Quickly)", options: [{text:"Beautiful", val:0}, {text:"Run", val:5}, {text:"Quickly", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Complete the sentence: She ____ to the store yesterday.", options: [{text:"goes", val:0}, {text:"went", val:5}, {text:"gone", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Synonym for 'GENUINE':", options: [{text:"Fake", val:0}, {text:"Authentic", val:5}, {text:"Cheap", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "What is a group of lions called?", options: [{text:"Flock", val:0}, {text:"Pride", val:5}, {text:"Herd", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Antonym for 'ARROGANT':", options: [{text:"Proud", val:0}, {text:"Humble", val:5}, {text:"Loud", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "The prefix 'Re-' means:", options: [{text:"Before", val:0}, {text:"Again", val:5}, {text:"Under", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "If something is 'Inevitable', it is:", options: [{text:"Avoidable", val:0}, {text:"Unavoidable", val:5}, {text:"Unlikely", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Which word means 'a period of 100 years'?", options: [{text:"Decade", val:0}, {text:"Century", val:5}, {text:"Millennium", val:0}] },

    // ==========================================
    // MODULE B: INTERESTS - RIASEC (120 Questions)
    // ==========================================

    // --- Realistic (20 Questions) ---
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I enjoy building or repairing mechanical objects." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I prefer working with my hands rather than working on a computer." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I would like a job where I get to operate heavy machinery or vehicles." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I like fixing electrical appliances when they break." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I enjoy outdoor physical labor like gardening or construction." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I would rather assemble a piece of furniture than write an essay." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I like taking things apart just to see how they work." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I prefer practical, real-world problems over theoretical discussions." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I enjoy activities like fishing, hunting, or camping." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I would enjoy working as a carpenter or woodworker." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I like understanding the schematics of an engine." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I prefer jobs where I can see a tangible physical product at the end of the day." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I am comfortable using power tools." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I enjoy hands-on hobbies like pottery, carving, or sewing." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I would like to work in agriculture or farming." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I like knowing survival skills and practical outdoor techniques." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I would rather maintain computer hardware than program software." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I find satisfaction in physical exertion and manual labor." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I like working with raw materials like metal, wood, or stone." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I would enjoy a career as an auto mechanic or technician." },

    // --- Investigative (20 Questions) ---
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I enjoy reading science magazines or technical journals." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I like solving complicated math or logic puzzles." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I prefer a job where I spend my time analyzing data." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I am curious about the natural laws of the universe." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I enjoy conducting chemistry or physics experiments." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I would like to work in a laboratory setting." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I like to deeply research a topic before making a major decision." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I enjoy finding hidden patterns in large sets of numbers." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I would enjoy a career as a scientific researcher." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I like asking 'why' and diving deep into theoretical concepts." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I prefer working with ideas and theories rather than people." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I enjoy diagnosing problems by examining the symptoms and evidence." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I would like to study genetics or biology." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I find computer programming and algorithm design fascinating." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I like reading about historical events to figure out the root causes." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I would enjoy working as a detective or forensic analyst." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I enjoy learning about astronomy and the solar system." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I like to break down a complex system to understand its individual parts." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I would rather read a non-fiction book about economics than a novel." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I trust objective facts and statistics more than human intuition." },

    // --- Artistic (20 Questions) ---
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I enjoy painting, drawing, or graphic design." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I like writing stories, poems, or scripts." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I prefer jobs where I have the freedom to be creative." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I am deeply moved by beautiful music or theater." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I like to decorate spaces and choose color palettes." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I often come up with unconventional, out-of-the-box ideas." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I dislike strict routines and prefer a flexible, spontaneous lifestyle." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I would enjoy a career as an architect or interior designer." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I like playing a musical instrument or singing." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I care heavily about the aesthetic look of a final product." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I enjoy acting in plays or creating video content." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I prefer expressing my feelings through art rather than talking." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I would rather visit an art museum than a science fair." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I enjoy brainstorming creative marketing campaigns." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I like creating custom outfits or studying fashion." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I value originality and hate copying what others have done." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I enjoy taking artistic photographs." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I would like to work as a freelance creator or artist." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I find inspiration in nature and beautiful landscapes." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I believe imagination is more important than raw knowledge." },

    // --- Social (20 Questions) ---
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I enjoy teaching or mentoring younger students." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I naturally want to comfort people when they are upset." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I would like a career in nursing or healthcare." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I prefer working in a collaborative team over working alone." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I frequently volunteer my time to help my community." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I am patient when explaining things to people who learn slowly." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I would enjoy working as a school counselor or therapist." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I find it easy to understand what other people are feeling." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I am motivated by a desire to improve the lives of others." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I enjoy organizing social events or community gatherings." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I prefer listening to someone's problems over analyzing data." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I would like to work in Human Resources or employee training." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I enjoy mediating conflicts and helping people find compromises." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I feel fulfilled when I see someone else succeed because of my help." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I would enjoy working for a non-profit organization or charity." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I am interested in studying psychology or sociology." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I like making new people feel welcome in a group." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I would rather have a friendly workplace than a high-paying stressful one." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I enjoy working directly with the public or customers." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I believe compassion is the most important trait a person can have." },

    // --- Enterprising (20 Questions) ---
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I enjoy taking the lead on group projects." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I like convincing others to agree with my point of view." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I am highly motivated by financial success and earning potential." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I would like to start and run my own business." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I enjoy public speaking and giving presentations to large crowds." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I like negotiating deals and haggling for better prices." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I would enjoy a career in sales, marketing, or real estate." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I am comfortable taking financial risks if the reward is high." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I enjoy debating and participating in political discussions." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I like being the person in charge who makes the final decisions." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I am very competitive and like to win." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I would enjoy managing a large team of employees." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I enjoy networking and meeting influential people." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I like selling products or promoting ideas I believe in." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I am comfortable giving direct feedback, even if it is negative." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I would enjoy working as a lawyer or corporate executive." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I like setting ambitious goals and working hard to achieve them." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I find corporate strategy and business planning exciting." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I like being recognized publicly for my achievements." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I would rather manage a department than do the manual work myself." },

    // --- Conventional (20 Questions) ---
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I prefer having a very clear, organized, and predictable daily routine." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I enjoy managing spreadsheets, databases, or filing systems." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I like balancing financial accounts or keeping track of budgets." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I pay close attention to small details that others might miss." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I prefer a job with clear rules and established procedures." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I like checking documents for spelling or numerical errors." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I would enjoy a career as an accountant or bookkeeper." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I prefer office environments over working outdoors." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I like keeping my physical and digital workspaces perfectly organized." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I find satisfaction in entering data accurately into a computer." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I would enjoy working in inventory management or logistics." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I prefer following instructions rather than inventing new ways to do things." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I like planning trips or events with detailed itineraries." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I value efficiency and hate when things are disorganized." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I would enjoy working as a bank teller or financial clerk." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I like classifying things into specific categories or folders." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I am very good at remembering strict rules and regulations." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I prefer steady, secure employment over risky entrepreneurial ventures." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I enjoy typing and performing administrative office tasks." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I am usually the person who keeps records or takes notes in a meeting." },

    // ==========================================
    // MODULE C: PERSONALITY - BIG-5 (120 Questions)
    // ==========================================

    // --- Conscientiousness (24 Questions) ---
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I am always prepared for classes or meetings." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I pay attention to small details." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I get my chores and duties done right away." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I like order and tidiness in my room." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I follow a strict schedule." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I am exacting in my work." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I never leave my belongings around." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I always put things back in their proper place." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I do not shirk my duties." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I complete tasks successfully." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I go straight for the goal without getting distracted." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I work hard to achieve my ambitions." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I double-check my work for errors." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I rarely act on impulse." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I keep my promises no matter what." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I start tasks as soon as they are assigned." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I am highly reliable." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I plan my finances carefully." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I despise wasting time." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I stick to my plans." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I prefer to finish one project before starting another." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I am always punctual." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I thoroughly read instructions before starting." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I believe rules should be followed strictly." },

    // --- Extraversion (24 Questions) ---
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I am the life of the party." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I feel comfortable around people." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I start conversations easily." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I talk to a lot of different people at parties." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I don't mind being the center of attention." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I make friends easily." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I take charge in group situations." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I know how to captivate people." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I feel at ease in large crowds." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I cheer people up." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I am a very energetic person." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I express my thoughts clearly and loudly." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I love exciting, high-energy activities." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I am very talkative." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I enjoy networking and meeting strangers." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I have a loud, booming laugh." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I act confidently." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I love large social gatherings." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I can easily convince others to join my plans." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I seek out adventure." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I rarely keep quiet for long." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I enjoy entertaining guests." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I am usually the first to volunteer for a task." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I radiate joy and enthusiasm." },

    // --- Agreeableness (24 Questions) ---
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I sympathize with others' feelings." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I take time out for others." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I feel others' emotions." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I make people feel at ease." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I am interested in people." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I have a soft heart." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I am easy to satisfy." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I respect others." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I believe that others have good intentions." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I am a very trusting person." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I hate arguing with my friends." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I am quick to forgive others." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I avoid imposing my will on others." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I love to help strangers." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I care deeply about those around me." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I avoid insulting people at all costs." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I value cooperation over competition." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I easily share my belongings." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I try to be humble." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I am sensitive to the needs of the poor." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I rarely hold a grudge." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I try to find a compromise in conflicts." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I speak softly to avoid intimidation." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I treat everyone as an equal." },

    // --- Openness (24 Questions) ---
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I have a rich vocabulary." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I have a vivid imagination." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I have excellent ideas." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I am quick to understand things." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I use difficult words." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I spend time reflecting on things." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I am full of ideas." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I love reading challenging books." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I love exploring philosophical concepts." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I appreciate beautiful art and music." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I am deeply moved by poetry." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I enjoy trying food from different cultures." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I like to break traditional rules." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I daydream frequently." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I see beauty in things others overlook." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I am highly curious about the world." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I adapt easily to new environments." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I enjoy visiting museums and galleries." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I like solving abstract problems." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I am interested in learning new languages." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I challenge the status quo." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I enjoy debating theories." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I like taking different routes to work/school just for variety." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I am fascinated by science and nature." },

    // --- Emotional Stability (Neuroticism Reversed) (24 Questions) ---
    // Note: Likert 1-5. High score = High Stability
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I am relaxed most of the time." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I seldom feel blue or depressed." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I handle stress very well." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I remain calm under heavy pressure." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I rarely get irritated." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I am not easily bothered by things." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I bounce back quickly after setbacks." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I keep my emotions under tight control." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I seldom worry about the future." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I don't let small failures bother me." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I am rarely annoyed by my coworkers or peers." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I feel confident and secure in myself." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I rarely experience mood swings." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I sleep well, even before a big event." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I don't let insults affect my self-worth." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I easily let go of negative thoughts." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I am generally an optimistic person." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I do not panic in emergencies." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I rarely feel overwhelmed by my responsibilities." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I maintain a positive attitude during hard times." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I forgive myself easily when I make a mistake." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I do not fear the unknown." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I feel capable of handling whatever life throws at me." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I approach problems logically, not emotionally." }
];