const questionsPart6 = [
    // ==========================================
    // MODULE A: APTITUDE & COGNITIVE ABILITY (60 Questions)
    // ==========================================

    // --- Numerical Aptitude (20 Questions) ---
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "What is 80% of 150?", options: [{text:"100", val:0}, {text:"120", val:5}, {text:"140", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "If 11d = 121, what is the value of d?", options: [{text:"10", val:0}, {text:"11", val:5}, {text:"12", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "A cyclist rides 45 km in 3 hours. Average speed?", options: [{text:"10 km/h", val:0}, {text:"15 km/h", val:5}, {text:"20 km/h", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "What is the square root of 196?", options: [{text:"12", val:0}, {text:"14", val:5}, {text:"16", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "A $200 TV is on sale for 15% off. New price?", options: [{text:"$170", val:5}, {text:"$185", val:0}, {text:"$180", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "Solve: (24 / 3) + 7", options: [{text:"14", val:0}, {text:"15", val:5}, {text:"16", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "What is 3/8 as a decimal?", options: [{text:"0.375", val:5}, {text:"0.350", val:0}, {text:"0.400", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "If 8 machines produce 100 widgets in an hour, how many machines are needed for 200 widgets?", options: [{text:"12", val:0}, {text:"16", val:5}, {text:"20", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "Area of a rectangle with length 15 and width 5?", options: [{text:"60", val:0}, {text:"75", val:5}, {text:"100", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "A seminar starts at 1:15 PM and ends at 3:45 PM. Duration?", options: [{text:"2h 15m", val:0}, {text:"2h 30m", val:5}, {text:"2h 45m", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "What is the square root of 256?", options: [{text:"16", val:5}, {text:"14", val:0}, {text:"18", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "Next prime number after 47?", options: [{text:"49", val:0}, {text:"53", val:5}, {text:"51", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "If 1 meter = 3.28 feet, how many feet in 5 meters?", options: [{text:"15.4", val:0}, {text:"16.4", val:5}, {text:"17.4", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "What is 9 cubed (9³)?", options: [{text:"729", val:5}, {text:"81", val:0}, {text:"649", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "A $300 bill divided among 6 people is?", options: [{text:"$40", val:0}, {text:"$50", val:5}, {text:"$60", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "Solve for y: 4y + 12 = 36", options: [{text:"6", val:5}, {text:"8", val:0}, {text:"5", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "A cake has 16 slices. You eat 4. Fraction remaining?", options: [{text:"1/4", val:0}, {text:"3/4", val:5}, {text:"1/2", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "Least Common Multiple (LCM) of 4 and 10?", options: [{text:"20", val:5}, {text:"40", val:0}, {text:"14", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "Probability of drawing a face card (Jack, Queen, King) from a standard deck?", options: [{text:"3/52", val:0}, {text:"12/52 (or 3/13)", val:5}, {text:"1/4", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "Convert 0.45 to a simplified fraction.", options: [{text:"9/20", val:5}, {text:"45/100", val:0}, {text:"7/20", val:0}] },

    // --- Logical Reasoning (20 Questions) ---
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Sequence: 10, 30, 90, 270, __?", options: [{text:"810", val:5}, {text:"540", val:0}, {text:"900", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Fish is to Gills as Human is to...?", options: [{text:"Lungs", val:5}, {text:"Nose", val:0}, {text:"Mouth", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "All birds can fly. An ostrich is a bird. Can an ostrich fly? (Based strictly on premise)", options: [{text:"Yes", val:5}, {text:"No", val:0}, {text:"Cannot be determined", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Odd one out: Square, Circle, Triangle, Sphere?", options: [{text:"Sphere", val:5}, {text:"Circle", val:0}, {text:"Triangle", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "If X is heavier than Y, and Y is heavier than Z, who is the heaviest?", options: [{text:"X", val:5}, {text:"Y", val:0}, {text:"Z", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Sequence: P, R, T, V, __?", options: [{text:"W", val:0}, {text:"X", val:5}, {text:"Y", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Surgeon is to Scalpel as Writer is to...?", options: [{text:"Book", val:0}, {text:"Pen", val:5}, {text:"Idea", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "If ONE is 345, TWO is 678, what is NOT?", options: [{text:"486", val:5}, {text:"684", val:0}, {text:"386", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "My sister's husband's mother is my sister's...?", options: [{text:"Aunt", val:0}, {text:"Mother-in-law", val:5}, {text:"Mother", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Sequence: 8, 16, 32, 64, __?", options: [{text:"128", val:5}, {text:"96", val:0}, {text:"100", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Some flowers are blue. All blue things are sad. Are some flowers sad?", options: [{text:"Yes", val:5}, {text:"No", val:0}, {text:"Cannot be determined", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Needle is to Thread as Bow is to...?", options: [{text:"Arrow", val:5}, {text:"Target", val:0}, {text:"String", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Odd one out: Apple, Peach, Tomato, Cherry.", options: [{text:"Tomato", val:5}, {text:"Cherry", val:0}, {text:"Peach", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Walk 5m North, turn around, walk 15m South. Direction facing?", options: [{text:"South", val:5}, {text:"North", val:0}, {text:"East", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Sequence: 3, 6, 11, 18, 27, __?", options: [{text:"38", val:5}, {text:"36", val:0}, {text:"39", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Thermostat is to Temperature as Barometer is to...?", options: [{text:"Pressure", val:5}, {text:"Wind", val:0}, {text:"Rain", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "If the 5th of the month is a Tuesday, what day is the 26th?", options: [{text:"Tuesday", val:5}, {text:"Wednesday", val:0}, {text:"Monday", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "All dogs bark. No cats bark. Can a cat be a dog?", options: [{text:"Yes", val:0}, {text:"No", val:5}, {text:"Cannot be determined", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Odd one out: 21, 35, 49, 56, 60?", options: [{text:"60", val:5}, {text:"56", val:0}, {text:"49", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "If B=2, D=4, F=6, then H=?", options: [{text:"7", val:0}, {text:"8", val:5}, {text:"9", val:0}] },

    // --- Verbal Reasoning (20 Questions) ---
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Synonym for 'LUCID':", options: [{text:"Clear", val:5}, {text:"Confused", val:0}, {text:"Dark", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Antonym for 'RIGID':", options: [{text:"Flexible", val:5}, {text:"Stiff", val:0}, {text:"Hard", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Meaning of 'piece of cake':", options: [{text:"Very easy", val:5}, {text:"A dessert", val:0}, {text:"Difficult", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Tree is to Forest as Sand is to...?", options: [{text:"Desert", val:5}, {text:"Beach", val:0}, {text:"Ocean", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Correct spelling:", options: [{text:"Accommodate", val:5}, {text:"Acommodate", val:0}, {text:"Accomodate", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "A person who studies language is a...?", options: [{text:"Linguist", val:5}, {text:"Historian", val:0}, {text:"Sociologist", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Synonym for 'PRAGMATIC':", options: [{text:"Practical", val:5}, {text:"Idealistic", val:0}, {text:"Emotional", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Plural of 'Crisis':", options: [{text:"Crisises", val:0}, {text:"Crises", val:5}, {text:"Crisis", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "A 'Cardiologist' treats the...?", options: [{text:"Heart", val:5}, {text:"Brain", val:0}, {text:"Stomach", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Antonym for 'ELEVATE':", options: [{text:"Lower", val:5}, {text:"Raise", val:0}, {text:"Lift", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Odd word out: Happy, Joyful, Ecstatic, Sad.", options: [{text:"Sad", val:5}, {text:"Happy", val:0}, {text:"Ecstatic", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Meaning of 'Inevitable':", options: [{text:"Avoidable", val:0}, {text:"Unavoidable", val:5}, {text:"Possible", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Which is a preposition? (Because, Blue, Quickly)", options: [{text:"Because", val:5}, {text:"Blue", val:0}, {text:"Quickly", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "We ____ to the movies last night.", options: [{text:"go", val:0}, {text:"went", val:5}, {text:"going", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Synonym for 'HOSTILE':", options: [{text:"Friendly", val:0}, {text:"Unfriendly", val:5}, {text:"Neutral", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "A group of lions is called a...?", options: [{text:"Pride", val:5}, {text:"Pack", val:0}, {text:"Herd", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Antonym for 'EXPAND':", options: [{text:"Contract", val:5}, {text:"Grow", val:0}, {text:"Increase", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Prefix 'Inter-' means:", options: [{text:"Between", val:5}, {text:"Inside", val:0}, {text:"Outside", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "If something is 'Crucial', it is:", options: [{text:"Important", val:5}, {text:"Unimportant", val:0}, {text:"Optional", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Meaning of 'Perennial':", options: [{text:"Lasting for many years", val:5}, {text:"Happening once a year", val:0}, {text:"Lasting for one year", val:0}] },

    // ==========================================
    // MODULE B: INTERESTS - RIASEC (120 Questions)
    // ==========================================

    // --- Realistic (20 Questions) ---
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I prefer working with tools and machinery rather than with people." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I enjoy learning how to repair small engines." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I like jobs that require manual dexterity." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I would rather frame a house than draft the architectural plans." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I enjoy operating power tools safely." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I like working with electronic components." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I am comfortable working in physically demanding conditions." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I enjoy maintaining large gardens or parks." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I would like to be a heavy equipment operator." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I like using precision measuring instruments." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I prefer hobbies that involve building or repairing physical objects." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I enjoy diagnosing and fixing mechanical problems." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I like installing complex wiring systems." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I would enjoy a career as a surveyor." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I like understanding the mechanics of how things move." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I find theoretical discussions less interesting than practical applications." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I prefer tasks that produce immediate, visible results." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I enjoy working on DIY home improvement projects." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I am interested in careers in law enforcement or the military." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I like assembling components according to detailed diagrams." },

    // --- Investigative (20 Questions) ---
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I enjoy reading about the latest discoveries in physics." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I like analyzing complex datasets using software." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I am intrigued by the root causes of economic shifts." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I prefer to verify facts before accepting them as truth." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I enjoy writing detailed technical reports." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I like formulating hypotheses and testing them." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I want to contribute to significant scientific research." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I enjoy studying the intricacies of human anatomy." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I like using predictive modeling to understand future outcomes." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I would enjoy working as a research chemist." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I like solving problems that require deep logical thought." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I am fascinated by the complexities of the immune system." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I enjoy coding scripts to automate data analysis." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I am highly critical of anecdotal evidence." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I would like to work as an environmental scientist." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I enjoy understanding the chemical properties of different substances." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I like tackling difficult mathematical puzzles." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I would rather attend a lecture on a complex topic than a social event." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I enjoy studying the structural differences between languages." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I believe that scientific inquiry is the best way to solve societal problems." },

    // --- Artistic (20 Questions) ---
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I enjoy developing color palettes for visual projects." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I like writing original poetry or song lyrics." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I am passionate about set design for theater." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I prefer working in a creative and unstructured environment." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I enjoy writing engaging content for marketing campaigns." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I like redesigning the visual layout of websites." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I am interested in improvisational acting." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I prefer assignments that allow me to express my own ideas." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I enjoy analyzing the aesthetic choices in films." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I would like a career as a graphic designer." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I find joy in studying various architectural styles." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I like creating unique patterns for textiles." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I am drawn to careers in visual arts." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I believe that good design enhances the user experience." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I enjoy customizing my clothes or accessories." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I would rather visit a modern art museum than a science center." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I like developing detailed backgrounds for fictional characters." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I enjoy learning about the history of different art movements." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I like decorating interior spaces to reflect a specific mood." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I constantly seek to express my creativity in my daily life." },

    // --- Social (20 Questions) ---
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I enjoy moderating group discussions or support circles." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I like providing advice to people facing difficult life choices." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I want a career in counseling or social work." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I enjoy organizing community outreach programs." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I am passionate about promoting mental health awareness." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I like helping individuals with disabilities navigate daily life." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I prefer roles that require me to be highly compassionate." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I enjoy working as a mentor or tutor for students." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I would like to work in disaster response." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I like advocating for better conditions for disadvantaged groups." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I find great joy in helping someone overcome a personal challenge." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I would enjoy a career as a registered nurse." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I am motivated by the desire to foster a sense of community." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I enjoy facilitating team-building exercises." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I like supporting families dealing with severe illness." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I prefer working in environments dedicated to helping others." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I enjoy helping opposing parties reach a mutual understanding." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I am patient when working with people who are highly emotional." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I would like to work as a community health educator." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I feel that improving the lives of others is the most important work." },

    // --- Enterprising (20 Questions) ---
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I enjoy negotiating the terms of a business deal." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I like creating pitch decks for new ventures." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I am driven by the challenge of meeting high revenue targets." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I enjoy evaluating investment opportunities." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I like taking decisive action to turn around a struggling project." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I prefer roles with a significant portion of performance-based pay." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I am comfortable making tough leadership decisions quickly." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I enjoy attending high-level industry events." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I would like to be the director of a major organization." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I like representing my organization to the media." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I enjoy managing and allocating significant financial budgets." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I am confident I can sell almost anything to anyone." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I would enjoy a career as a corporate executive." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I am highly motivated by the prospect of climbing the corporate ladder." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I enjoy analyzing market data to find competitive advantages." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I like the responsibility of building a strong leadership team." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I enjoy leading large-scale promotional campaigns." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I would like to work as an independent business consultant." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I am skilled at converting skeptical prospects into clients." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I believe that taking bold risks is essential for significant growth." },

    // --- Conventional (20 Questions) ---
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I enjoy verifying the accuracy of complex financial reports." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I like maintaining detailed logs of all company assets." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I prefer working in an environment with clear, strict rules." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I am excellent at formatting documents to meet specific standards." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I enjoy calculating payroll and ensuring compliance." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I like working as a quality assurance inspector." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I am highly comfortable with routine, detail-oriented tasks." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I enjoy ensuring all procedures meet regulatory requirements." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I like developing standard operating procedures for new tasks." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I would enjoy a career in data entry and management." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I enjoy organizing large volumes of physical files." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I prefer being evaluated on measurable, objective criteria." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I like cataloging information using specific classification systems." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I would enjoy working as an inventory clerk." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I value precision and error-free work above all else." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I like reviewing contracts for specific legal clauses." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I enjoy transcribing meetings accurately." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I would like a career in administrative support." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I feel stressed when people do not follow the established rules." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I believe that organized records are the foundation of any successful business." },

    // ==========================================
    // MODULE C: PERSONALITY - BIG-5 (120 Questions)
    // ==========================================

    // --- Conscientiousness (24 Questions) ---
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I prepare my tasks for the next day before going to bed." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I rarely miss credit card payments." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I prefer to finish assignments long before the deadline." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I set weekly targets for my work output." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I am disturbed when tools are not returned to their proper place." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I keep a precise log of my daily expenses." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I consistently arrive early for appointments." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I rigorously check my work for typos before submission." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I believe strong self-discipline leads to success." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I complete my responsibilities even when I lack motivation." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I strictly adhere to my long-term financial plans." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I hate leaving tasks uncompleted." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I am highly structured in my approach to new projects." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I evaluate all potential outcomes before making a decision." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I promptly reply to important messages." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I follow maintenance schedules carefully." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I never compromise on safety procedures." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I regularly organize my digital files." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I follow my routines consistently." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I am determined to find the correct answer, no matter how long it takes." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I avoid making promises I cannot fulfill." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I prefer highly structured learning environments." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I take pride in my reliability." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I am known for never forgetting important details." },

    // --- Extraversion (24 Questions) ---
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I typically volunteer to present group projects." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I enjoy planning large social events." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I feel restless if I have to work alone all day." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I naturally speak with enthusiasm." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I easily strike up conversations with strangers." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I am highly expressive when telling a story." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I prefer energetic, collaborative work settings." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I am quick to introduce myself to new colleagues." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I love participating in team-based activities." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I often suggest after-work social gatherings." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I confidently defend my opinions in public." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I dislike traveling alone." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I thrive in lively, noisy environments." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I am quick to suggest going out with friends." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I have a distinct and loud laugh." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I enjoy speaking in front of an audience." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I maintain a large network of professional contacts." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I am generally described as highly sociable." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I naturally seek out the busiest areas at an event." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I find solitary activities to be dull." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I enjoy participating in engaging debates." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I prefer playing team sports over working out alone." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I tend to process my thoughts by talking them out." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I consider myself very outgoing." },

    // --- Agreeableness (24 Questions) ---
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I assume people have good intentions even if they mess up." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I am uncomfortable criticizing others." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I regularly support charitable causes." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I feel guilty when I disappoint someone." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I am known for being easygoing." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I will help a colleague even if I am busy." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I prefer finding common ground over winning arguments." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I am highly empathetic toward people in need." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I make sure to credit others for their work." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I try to quickly resolve tension in a group." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I rarely judge others for their past actions." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I believe society should care for those who cannot care for themselves." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I have a lot of patience with people who are struggling to learn." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I am the person people come to for comfort." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I often prioritize my friends' needs over my own." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I dislike humor that targets specific individuals." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I am very accommodating when making group plans." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I listen attentively when someone is upset." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I believe that holding grudges is harmful." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I regularly show appreciation to my colleagues." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I rarely insist on having things my way." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I easily yield in minor disagreements." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I am deeply moved by acts of compassion." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I believe empathy is essential for good leadership." },

    // --- Openness (24 Questions) ---
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I love exploring independent art galleries." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I enjoy discussing complex philosophical issues." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I frequently read about new scientific theories." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I enjoy trying unique and unfamiliar foods." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I am highly creative when tackling unusual problems." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I like questioning accepted interpretations of history." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I prefer thought-provoking films over standard action movies." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I am open to learning about different spiritual beliefs." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I enjoy writing creatively in my free time." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I am deeply curious about human behavior." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I like listening to a wide range of musical genres." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I am fascinated by ancient myths and legends." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I believe art should push boundaries." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I like finding innovative uses for everyday items." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I enjoy visiting nature reserves and gardens." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I often think about the ethical implications of new technologies." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I enjoy learning about complex topics like cryptography." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I prefer to travel without a strict plan." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I am drawn to abstract and modern art." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I appreciate intricately detailed fictional worlds." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I believe laws should change as society changes." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I enjoy discussing global economics and politics." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I am quick to explore new lifestyle trends." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I feel stimulated when contemplating abstract ideas." },

    // --- Emotional Stability (Neuroticism Reversed) (24 Questions) ---
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I rarely get frustrated when stuck in traffic." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I do not panic when facing technical difficulties." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I wake up feeling generally positive." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I am highly resilient when dealing with failure." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I don't hold onto anger after an argument." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I can easily accept constructive criticism." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I rarely feel anxious in crowded places." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I am able to maintain composure in stressful situations." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I rarely envy the success of others." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I am comfortable handling unexpected changes to my schedule." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I do not constantly worry about my future." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I view setbacks as an opportunity to improve." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I maintain a consistent mood throughout the week." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I am not easily startled by loud noises." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I can easily dismiss negative comments from others." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I don't dwell on past embarrassing moments." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I feel confident in my personal relationships." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I rarely feel isolated from my peer group." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I do not rely on others for my sense of self-worth." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I can easily relax and calm my mind." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I view changes in circumstances as normal parts of life." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I avoid expecting the worst in difficult situations." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I am generally satisfied with my abilities." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I can discuss sensitive topics without becoming overly emotional." }
];