const questionsPart9 = [
    // ==========================================
    // MODULE A: APTITUDE & COGNITIVE ABILITY (60 Questions)
    // ==========================================

    // --- Numerical Aptitude (20 Questions) ---
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "What is 35% of 400?", options: [{text:"120", val:0}, {text:"140", val:5}, {text:"160", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "If 10g = 150, what is the value of g?", options: [{text:"12", val:0}, {text:"15", val:5}, {text:"20", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "A boat travels 60 miles in 4 hours. Average speed?", options: [{text:"12 mph", val:0}, {text:"15 mph", val:5}, {text:"18 mph", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "What is the square root of 625?", options: [{text:"25", val:5}, {text:"35", val:0}, {text:"15", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "A $400 desk is discounted by 25%. What is the new price?", options: [{text:"$250", val:0}, {text:"$300", val:5}, {text:"$350", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "Solve: (12 × 4) / 2", options: [{text:"20", val:0}, {text:"24", val:5}, {text:"30", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "What is 9/10 as a decimal?", options: [{text:"0.95", val:0}, {text:"0.90", val:5}, {text:"0.09", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "If 4 chefs bake 20 cakes in an hour, how many cakes can 8 chefs bake?", options: [{text:"30", val:0}, {text:"40", val:5}, {text:"50", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "Area of a triangle with base 15 and height 10?", options: [{text:"50", val:0}, {text:"75", val:5}, {text:"150", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "A concert starts at 7:30 PM and ends at 10:15 PM. Duration?", options: [{text:"2h 30m", val:0}, {text:"2h 45m", val:5}, {text:"3h 15m", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "What is the square root of 900?", options: [{text:"20", val:0}, {text:"30", val:5}, {text:"90", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "Next prime number after 71?", options: [{text:"73", val:5}, {text:"75", val:0}, {text:"77", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "If 1 centimeter = 10 millimeters, how many millimeters in 4.8 cm?", options: [{text:"480", val:0}, {text:"48", val:5}, {text:"408", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "What is 3 to the power of 4 (3^4)?", options: [{text:"27", val:0}, {text:"81", val:5}, {text:"243", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "A $500 bonus divided among 4 people is?", options: [{text:"$100", val:0}, {text:"$125", val:5}, {text:"$150", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "Solve for k: 7k - 14 = 35", options: [{text:"5", val:0}, {text:"7", val:5}, {text:"9", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "A pizza has 10 slices. You eat 7. Fraction remaining?", options: [{text:"1/5", val:0}, {text:"3/10", val:5}, {text:"1/2", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "Least Common Multiple (LCM) of 8 and 12?", options: [{text:"16", val:0}, {text:"24", val:5}, {text:"48", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "Probability of rolling a prime number on a standard die (2, 3, 5)?", options: [{text:"1/3", val:0}, {text:"1/2", val:5}, {text:"2/3", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "Convert 0.15 to a simplified fraction.", options: [{text:"1/5", val:0}, {text:"3/20", val:5}, {text:"15/100", val:0}] },

    // --- Logical Reasoning (20 Questions) ---
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Sequence: 2, 5, 11, 23, __?", options: [{text:"35", val:0}, {text:"47", val:5}, {text:"44", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Ship is to Anchor as Car is to...?", options: [{text:"Wheel", val:0}, {text:"Brake", val:5}, {text:"Engine", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "All scientists are smart. Some teachers are scientists. Are some teachers smart?", options: [{text:"Yes", val:5}, {text:"No", val:0}, {text:"Cannot be determined", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Odd one out: Rose, Tulip, Lily, Tree?", options: [{text:"Tree", val:5}, {text:"Rose", val:0}, {text:"Tulip", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "If X < Y and Z < X, who is the smallest?", options: [{text:"X", val:0}, {text:"Y", val:0}, {text:"Z", val:5}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Sequence: W, U, S, Q, __?", options: [{text:"P", val:0}, {text:"O", val:5}, {text:"N", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Mechanic is to Wrench as Chef is to...?", options: [{text:"Kitchen", val:0}, {text:"Knife", val:5}, {text:"Food", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "If BOY is 42, GIRL is 46, what is MAN?", options: [{text:"28", val:5}, {text:"30", val:0}, {text:"32", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "My sister's son's father is my...?", options: [{text:"Brother", val:0}, {text:"Brother-in-law", val:5}, {text:"Nephew", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Sequence: 400, 200, 100, 50, __?", options: [{text:"25", val:5}, {text:"30", val:0}, {text:"20", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Some boxes are square. All squares have four sides. Do some boxes have four sides?", options: [{text:"Yes", val:5}, {text:"No", val:0}, {text:"Cannot be determined", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Light is to Lamp as Wind is to...?", options: [{text:"Breeze", val:0}, {text:"Sky", val:0}, {text:"Fan", val:5}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Odd one out: Gold, Platinum, Diamond, Bronze.", options: [{text:"Diamond", val:5}, {text:"Gold", val:0}, {text:"Platinum", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Walk 10m South, turn right, walk 20m. Direction facing?", options: [{text:"South", val:0}, {text:"West", val:5}, {text:"East", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Sequence: 2, 6, 12, 20, 30, __?", options: [{text:"40", val:0}, {text:"42", val:5}, {text:"44", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Scale is to Weight as Clock is to...?", options: [{text:"Time", val:5}, {text:"Hour", val:0}, {text:"Wall", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "If the 6th of the month is Thursday, what day is the 20th?", options: [{text:"Thursday", val:5}, {text:"Wednesday", val:0}, {text:"Friday", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "All birds have beaks. A parrot is a bird. Does a parrot have a beak?", options: [{text:"Yes", val:5}, {text:"No", val:0}, {text:"Cannot be determined", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Odd one out: 16, 32, 64, 100, 128?", options: [{text:"100", val:5}, {text:"64", val:0}, {text:"32", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "If E=5, J=10, O=15, then T=?", options: [{text:"18", val:0}, {text:"20", val:5}, {text:"22", val:0}] },

    // --- Verbal Reasoning (20 Questions) ---
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Synonym for 'ENIGMA':", options: [{text:"Solution", val:0}, {text:"Puzzle", val:5}, {text:"Clarity", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Antonym for 'PROFOUND':", options: [{text:"Superficial", val:5}, {text:"Deep", val:0}, {text:"Intense", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Meaning of 'cost an arm and a leg':", options: [{text:"Very expensive", val:5}, {text:"A dangerous task", val:0}, {text:"Free", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Wing is to Airplane as Fin is to...?", options: [{text:"Fish", val:5}, {text:"Boat", val:0}, {text:"Water", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Correct spelling:", options: [{text:"Acquaintence", val:0}, {text:"Acquaintance", val:5}, {text:"Aquaintance", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "A person who studies earthquakes is a...?", options: [{text:"Seismologist", val:5}, {text:"Volcanologist", val:0}, {text:"Geologist", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Synonym for 'TENACIOUS':", options: [{text:"Persistent", val:5}, {text:"Weak", val:0}, {text:"Lazy", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Plural of 'Syllabus':", options: [{text:"Syllabuses", val:0}, {text:"Syllabi", val:5}, {text:"Syllabus", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "A 'Pulmonologist' treats the...?", options: [{text:"Lungs", val:5}, {text:"Heart", val:0}, {text:"Brain", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Antonym for 'OBVIOUS':", options: [{text:"Clear", val:0}, {text:"Hidden", val:5}, {text:"Loud", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Odd word out: Fast, Quick, Rapid, Slow.", options: [{text:"Slow", val:5}, {text:"Fast", val:0}, {text:"Quick", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Meaning of 'Plausible':", options: [{text:"Impossible", val:0}, {text:"Reasonable/Likely", val:5}, {text:"Fake", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Which is a verb? (Happily, Swim, Tree)", options: [{text:"Swim", val:5}, {text:"Happily", val:0}, {text:"Tree", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "He ____ working there for five years.", options: [{text:"has been", val:5}, {text:"is", val:0}, {text:"was", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Synonym for 'LETHARGIC':", options: [{text:"Energetic", val:0}, {text:"Sluggish", val:5}, {text:"Fast", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "A group of elephants is called a...?", options: [{text:"Herd", val:5}, {text:"Flock", val:0}, {text:"Pack", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Antonym for 'CORRUPT':", options: [{text:"Honest", val:5}, {text:"Dishonest", val:0}, {text:"Bad", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Prefix 'Semi-' means:", options: [{text:"Full", val:0}, {text:"Half", val:5}, {text:"Double", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "If something is 'Vivid', it is:", options: [{text:"Dull", val:0}, {text:"Bright and clear", val:5}, {text:"Dark", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Meaning of 'Decade':", options: [{text:"100 years", val:0}, {text:"10 years", val:5}, {text:"1000 years", val:0}] },

    // ==========================================
    // MODULE B: INTERESTS - RIASEC (120 Questions)
    // ==========================================

    // --- Realistic (20 Questions) ---
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I prefer working on tangible products rather than abstract ideas." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I enjoy learning how to weld or solder metals." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I like jobs that require me to be outdoors in nature." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I would rather build a bridge than write a report about one." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I enjoy operating commercial vehicles or trains." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I like working with mechanical schematics and blueprints." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I am comfortable working in physically hazardous environments safely." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I enjoy working with timber and building wooden structures." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I would like to be a commercial pilot or ship captain." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I like using heavy duty power tools on a daily basis." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I prefer hobbies that require me to fix broken items around the house." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I enjoy troubleshooting complex machinery when it fails." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I like installing physical network cables or fiber optics." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I would enjoy a career as a general contractor." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I like understanding the aerodynamics or physics of physical objects." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I find writing essays and attending meetings to be tedious." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I prefer learning through apprenticeship and physical repetition." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I enjoy taking care of horses, cattle, or livestock." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I am interested in careers involving maritime or ocean work." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I like physically turning raw materials into finished goods." },

    // --- Investigative (20 Questions) ---
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I enjoy reading complex manuals about how software works." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I like analyzing large spreadsheets to locate anomalies." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I am fascinated by the study of microscopic organisms." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I prefer conducting independent research over group discussions." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I enjoy writing white papers detailing scientific phenomena." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I like formulating mathematical models to describe reality." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I want to publish a groundbreaking study in my field." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I enjoy studying geology and the formation of the earth." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I like using logic to dismantle flawed arguments." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I would enjoy working as a quantitative analyst." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I like investigating complex technical failures to find the exact cause." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I am interested in learning about advanced robotics." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I enjoy analyzing behavioral data to predict human actions." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I am critical of subjective opinions pretending to be facts." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I would like to work as a data scientist or statistician." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I enjoy understanding the algorithms that drive search engines." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I like working on problems that take days or weeks to fully solve." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I would rather visit an observatory than an art gallery." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I enjoy exploring complex astronomical concepts." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I believe that the scientific method is the ultimate tool for truth." },

    // --- Artistic (20 Questions) ---
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I enjoy creating 3D models or digital sculptures." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I like writing screenplays for independent films." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I am passionate about expressing my identity through fashion." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I prefer workspaces that have vibrant colors and unique decor." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I enjoy writing melodic compositions for different instruments." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I like sketching concepts for video game characters." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I am interested in directing stage productions." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I prefer assignments that let me interpret the rules creatively." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I enjoy analyzing the brush strokes and techniques in classic paintings." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I would like a career as a concept artist." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I find joy in visiting underground music venues." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I like developing intricate plots for stories." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I am drawn to careers in landscape architecture." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I believe that creativity is just as important as logic." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I enjoy experimenting with digital photography editing." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I would rather read a book of poems than an encyclopedia." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I like brainstorming visually striking marketing campaigns." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I enjoy learning about the evolution of typography and fonts." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I like arranging physical spaces to create a specific emotional response." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I constantly seek out new forms of media to inspire my own work." },

    // --- Social (20 Questions) ---
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I enjoy helping individuals navigate the healthcare system." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I like teaching language skills to non-native speakers." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I want a career where my primary goal is community enrichment." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I enjoy volunteering at local animal shelters or rescues." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I am passionate about providing grief counseling." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I like working collaboratively to resolve community disputes." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I prefer roles that require me to deeply understand others' backgrounds." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I enjoy advising teenagers on overcoming peer pressure." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I would like to work as a specialized therapist." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I like mediating conflicts between family members." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I find great joy in assisting people in their personal recovery." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I would enjoy a career as a public health advocate." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I am motivated by a desire to ensure everyone feels included." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I enjoy organizing support networks for vulnerable populations." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I like providing direct care for those recovering from surgery." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I prefer working in environments focused on holistic wellness." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I enjoy listening to people who feel they have no one else to talk to." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I am patient when communicating with individuals who are confused." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I would like to work in a role focused entirely on employee satisfaction." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I feel that helping society's most vulnerable is a moral duty." },

    // --- Enterprising (20 Questions) ---
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I enjoy leading aggressive sales initiatives." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I like pitching high-risk, high-reward concepts to executives." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I am driven by the opportunity to dominate a market." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I enjoy developing strategies to drastically cut corporate costs." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I like making executive decisions that affect hundreds of employees." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I prefer roles that offer immense public visibility and status." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I am comfortable negotiating aggressive corporate mergers." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I enjoy participating in highly competitive corporate environments." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I would like to be an elected public official." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I like networking with billionaires and industry titans." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I enjoy giving presentations to convince shareholders." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I am confident in my ability to persuade almost anyone." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I would enjoy a career as an aggressive litigation attorney." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I am highly motivated by accumulating wealth and power." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I enjoy analyzing global markets to find lucrative trade opportunities." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I like the challenge of managing a massive, multi-national budget." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I enjoy leading massive product launches." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I would like to work as a high-end corporate consultant." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I am skilled at motivating a lazy team to hit record numbers." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I believe that ruthless competition breeds the best results." },

    // --- Conventional (20 Questions) ---
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I enjoy organizing raw data into perfectly formatted tables." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I like keeping flawless tax records." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I prefer working in an environment with absolutely strict rules." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I am excellent at catching micro-errors in massive documents." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I enjoy tasks that require 100% adherence to standard operating procedure." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I like working as a strictly regulated financial auditor." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I am highly comfortable with monotonous, predictable, and quiet work." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I enjoy ensuring compliance with complex international shipping laws." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I like creating exhaustive filing systems for corporate use." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I would enjoy a career as a highly structured paralegal." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I enjoy categorizing massive physical archives." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I prefer jobs where creativity is not required." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I like reviewing databases for duplicate or erroneous entries." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I would enjoy working as an advanced data entry specialist." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I value efficiency, order, and predictability above all else." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I like processing endless stacks of identical forms." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I enjoy managing strictly controlled inventory warehouses." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I would like a career in municipal court administration." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I feel stressed when my coworkers skip required paperwork." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I believe that following the rules precisely prevents all workplace issues." },

    // ==========================================
    // MODULE C: PERSONALITY - BIG-5 (120 Questions)
    // ==========================================

    // --- Conscientiousness (24 Questions) ---
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I mentally review my tasks before sleep." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I rarely ever miss a loan or rent payment." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I prefer to finish assignments weeks in advance." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I set daily, weekly, and monthly targets for myself." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I am disturbed when someone moves items on my desk." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I keep a precise log of my vehicle's mileage." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I consistently arrive 15 minutes early for flights or trains." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I rigorously check my work for formatting errors." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I believe that organization is the key to mental peace." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I complete my most dreaded chores first thing in the morning." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I strictly adhere to corporate policies." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I hate feeling like I am unprepared for an exam." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I am highly focused when reading dense manuals." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I evaluate all minor details before starting a large task." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I promptly handle all boring administrative duties." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I follow instructions carefully, even if no one is watching." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I never leave my car or room disorganized." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I regularly review my progress toward long-term goals." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I follow my morning and evening routines without fail." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I am determined to meet exceptionally high standards." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I avoid acting impulsively when dealing with money." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I prefer working in environments with obvious hierarchy." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I take great pride in my perfectionism." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I am known for my intensely methodical approach." },

    // --- Extraversion (24 Questions) ---
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I typically enjoy being the absolute center of attention." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I enjoy hosting massive block parties." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I feel invigorated after interacting with a huge crowd." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I naturally take the microphone at events." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I easily make friends with people on airplanes." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I am highly dramatic and expressive when speaking." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I prefer extremely energetic, open-office settings." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I am quick to introduce myself to executives." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I love participating in loud group celebrations." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I often initiate weekend trips with large groups." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I confidently challenge the speaker during a lecture." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I dislike working alone in a closed room." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I thrive in loud, fast-paced trading floors or sales floors." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I am quick to suggest jumping on a stage or dance floor." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I have a very piercing and infectious laugh." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I enjoy speaking into a megaphone." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I maintain an enormous circle of casual friends." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I am generally described as deeply extroverted." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I naturally seek out the most crowded parts of a venue." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I find reading alone to be torturously boring." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I enjoy participating in fiery shouting matches or debates." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I prefer chaotic team sports over quiet gym workouts." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I tend to communicate constantly via texts and calls." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I consider myself the ultimate 'people person'." },

    // --- Agreeableness (24 Questions) ---
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I assume strangers have my best interests at heart." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I am entirely uncomfortable confronting a bad employee." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I regularly volunteer at homeless shelters." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I feel crushing guilt when I let my team down." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I am known for being overwhelmingly sweet." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I will do a coworker's job for them if they are stressed." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I prefer surrendering an argument to keep the peace." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I am highly sympathetic to criminals who had bad childhoods." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I make sure to write thank-you notes for every gift." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I try to instantly defuse any hostility in a room." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I rarely hold prejudice against people with different views." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I believe universal basic income is a moral necessity." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I have endless patience with complaining customers." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I am the designated therapist among my friend group." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I often put the financial needs of others before my own." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I deeply despise cruel or dark humor." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I am extremely passive when deciding where to eat." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I listen carefully without judging when someone confesses a flaw." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I believe that vengeance is completely useless." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I regularly buy lunch for my subordinates." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I rarely demand the spotlight or recognition." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I easily back down in debates over politics." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I am deeply moved to tears by sad documentaries." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I believe that kindness is the only thing that truly matters." },

    // --- Openness (24 Questions) ---
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I love exploring highly controversial new ideas." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I enjoy discussing the simulation theory of the universe." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I frequently read obscure academic journals." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I enjoy trying sensory deprivation tanks or meditation retreats." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I am highly imaginative when writing fiction." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I like deeply questioning my own cultural biases." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I prefer art house cinema over reality television." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I am open to exploring pagan or esoteric belief systems." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I enjoy writing bizarre or surrealist poetry." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I am deeply curious about evolutionary psychology." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I like listening to extremely niche foreign music." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I am fascinated by quantum physics and alternate dimensions." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I believe society is fundamentally flawed and needs redesigning." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I like inventing totally new words or slang." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I enjoy visiting ancient, mystical ruins." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I often think about the philosophy of consciousness." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I enjoy learning obscure coding languages." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I prefer to backpack through unfamiliar countries." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I am drawn to highly experimental, non-traditional art forms." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I appreciate the lore of massive fantasy universes." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I believe that traditional marriage might be an outdated concept." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I enjoy discussing anarcho-capitalism or pure socialism." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I am quick to embrace drastic dietary changes like veganism." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I feel stimulated by deeply confusing riddles." },

    // --- Emotional Stability (Neuroticism Reversed) (24 Questions) ---
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I rarely ever scream or yell in frustration." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I do not panic when my flight is suddenly canceled." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I wake up feeling at absolute peace with the world." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I am highly resilient when getting fired or laid off." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I never hold onto resentment after a breakup." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I can easily accept brutal honesty about my flaws." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I rarely feel anxious about public speaking." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I am able to stay fully focused during a medical emergency." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I rarely feel envious of celebrities or billionaires." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I am totally comfortable with the idea of moving to a new city." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I do not worry about aging or getting older." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I view intense hardship as an exciting trial to overcome." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I maintain a stoic, unflappable temper at work." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I am not easily rattled by horror movies or jump scares." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I can easily laugh off a coffee spill on my new shirt." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I don't dwell on what I could have done differently in high school." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I feel incredibly secure in my physical capabilities." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I rarely feel 'FOMO' (Fear Of Missing Out)." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I do not rely on romantic partners to feel complete." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I can easily fall back asleep if woken in the night." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I view economic recessions as cyclical and not terrifying." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I completely avoid catastrophizing when I feel mildly sick." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I am completely at peace with my current social status." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I can discuss death and mortality without anxiety." }
];