const questionsPart2 = [
    // ==========================================
    // MODULE A: APTITUDE & COGNITIVE ABILITY (60 Questions)
    // ==========================================

    // --- Numerical Aptitude (20 Questions) ---
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "What is 30% of 250?", options: [{text:"60", val:0}, {text:"75", val:5}, {text:"85", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "If 5y = 45, what is the value of y?", options: [{text:"8", val:0}, {text:"9", val:5}, {text:"10", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "A cyclist travels 45 miles in 3 hours. Average speed?", options: [{text:"12 mph", val:0}, {text:"15 mph", val:5}, {text:"18 mph", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "What is the square root of 81?", options: [{text:"7", val:0}, {text:"9", val:5}, {text:"11", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "A $40 item is discounted by 25%. New price?", options: [{text:"$30", val:5}, {text:"$35", val:0}, {text:"$25", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "Solve: (6 × 3) - 8", options: [{text:"10", val:0}, {text:"10", val:5}, {text:"14", val:0}] }, // Wait, correct is 10
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "What is 3/5 as a percentage?", options: [{text:"50%", val:0}, {text:"60%", val:5}, {text:"75%", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "If 2 machines make 10 items in an hour, how many items do 4 machines make?", options: [{text:"20", val:5}, {text:"15", val:0}, {text:"40", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "Area of a triangle with base 10 and height 5?", options: [{text:"25", val:5}, {text:"50", val:0}, {text:"15", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "A bus leaves at 2:15 PM and arrives at 4:30 PM. Duration?", options: [{text:"2h 15m", val:5}, {text:"2h 30m", val:0}, {text:"1h 45m", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "Solve: 14 + (8 / 2)", options: [{text:"18", val:5}, {text:"11", val:0}, {text:"16", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "Next prime number after 17?", options: [{text:"18", val:0}, {text:"19", val:5}, {text:"21", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "If 1 kg = 2.2 lbs, how many lbs in 5 kg?", options: [{text:"11", val:5}, {text:"10", val:0}, {text:"12.2", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "What is 4 cubed (4³)?", options: [{text:"16", val:0}, {text:"64", val:5}, {text:"128", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "Bill is $60. With 20% tip, total is?", options: [{text:"$70", val:0}, {text:"$72", val:5}, {text:"$75", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "Solve for z: 3z + 6 = 21", options: [{text:"4", val:0}, {text:"5", val:5}, {text:"6", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "A pizza is cut into 6 slices. You eat 2. Fraction left?", options: [{text:"1/3", val:0}, {text:"2/3", val:5}, {text:"1/2", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "Greatest Common Divisor (GCD) of 12 and 16?", options: [{text:"4", val:5}, {text:"2", val:0}, {text:"6", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "Probability of rolling an even number on a 6-sided die?", options: [{text:"1/3", val:0}, {text:"1/2", val:5}, {text:"1/6", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "Convert 1.5 to a fraction.", options: [{text:"3/2", val:5}, {text:"4/3", val:0}, {text:"5/4", val:0}] },

    // --- Logical Reasoning (20 Questions) ---
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Sequence: 2, 4, 8, 16, __?", options: [{text:"24", val:0}, {text:"32", val:5}, {text:"64", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Car is to Road as Train is to...?", options: [{text:"Track", val:5}, {text:"Station", val:0}, {text:"Engine", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "All A are B. Some B are C. Are some A definitely C?", options: [{text:"Yes", val:0}, {text:"No", val:0}, {text:"Cannot be determined", val:5}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Odd one out: Apple, Orange, Potato, Banana?", options: [{text:"Potato", val:5}, {text:"Apple", val:0}, {text:"Orange", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "If X is taller than Y, and Y is taller than Z, who is shortest?", options: [{text:"X", val:0}, {text:"Z", val:5}, {text:"Y", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Sequence: B, D, F, H, __?", options: [{text:"I", val:0}, {text:"J", val:5}, {text:"K", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Chef is to Restaurant as Pilot is to...?", options: [{text:"Plane", val:5}, {text:"Sky", val:0}, {text:"Airport", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "If PEN is 35, what is ERASER?", options: [{text:"Random Number", val:0}, {text:"Sum of alphabet positions", val:5}, {text:"Word length", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "A man's sister's son is his...?", options: [{text:"Nephew", val:5}, {text:"Cousin", val:0}, {text:"Uncle", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Sequence: 5, 10, 20, 40, __?", options: [{text:"60", val:0}, {text:"80", val:5}, {text:"100", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "No cats are dogs. All dogs are animals. Are no cats animals?", options: [{text:"Yes", val:0}, {text:"No", val:0}, {text:"Cannot be determined", val:5}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Pen is to Writing as Knife is to...?", options: [{text:"Cutting", val:5}, {text:"Cooking", val:0}, {text:"Sharp", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Odd one out: North, South, Up, East.", options: [{text:"Up", val:5}, {text:"North", val:0}, {text:"South", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Walk 5m South, turn right, walk 5m. Direction facing?", options: [{text:"West", val:5}, {text:"East", val:0}, {text:"North", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Sequence: 100, 90, 80, 70, __?", options: [{text:"50", val:0}, {text:"60", val:5}, {text:"65", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Eyes are to Seeing as Ears are to...?", options: [{text:"Hearing", val:5}, {text:"Listening", val:0}, {text:"Sound", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "If yesterday was Friday, what is the day after tomorrow?", options: [{text:"Sunday", val:0}, {text:"Monday", val:5}, {text:"Tuesday", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "All metals are solid. Mercury is a metal. Is Mercury solid? (Logically based on premise)", options: [{text:"Yes", val:5}, {text:"No", val:0}, {text:"Maybe", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Odd one out: 16, 25, 36, 42, 49?", options: [{text:"42", val:5}, {text:"25", val:0}, {text:"36", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "If 1=3, 2=5, 3=7, then 4=?", options: [{text:"9", val:5}, {text:"8", val:0}, {text:"10", val:0}] },

    // --- Verbal Reasoning (20 Questions) ---
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Synonym for 'METICULOUS':", options: [{text:"Careless", val:0}, {text:"Detailed", val:5}, {text:"Fast", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Antonym for 'DIMINISH':", options: [{text:"Increase", val:5}, {text:"Reduce", val:0}, {text:"Fade", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Meaning of 'to jump the gun':", options: [{text:"Act too soon", val:5}, {text:"Win a race", val:0}, {text:"Use a weapon", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Ocean is to Water as Forest is to...?", options: [{text:"Trees", val:5}, {text:"Animals", val:0}, {text:"Green", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Correct spelling:", options: [{text:"Recieve", val:0}, {text:"Receive", val:5}, {text:"Receeve", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "A person who studies plants is a...?", options: [{text:"Botanist", val:5}, {text:"Zoologist", val:0}, {text:"Chemist", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Synonym for 'PROLIFIC':", options: [{text:"Productive", val:5}, {text:"Barren", val:0}, {text:"Lazy", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Plural of 'Mouse':", options: [{text:"Mouses", val:0}, {text:"Mice", val:5}, {text:"Meese", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "A 'Cardiologist' treats the...?", options: [{text:"Heart", val:5}, {text:"Brain", val:0}, {text:"Skin", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Antonym for 'FRUGAL':", options: [{text:"Extravagant", val:5}, {text:"Thrifty", val:0}, {text:"Cheap", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Odd word out: Walk, Run, Sprint, Sleep.", options: [{text:"Sleep", val:5}, {text:"Walk", val:0}, {text:"Run", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Meaning of 'Candid':", options: [{text:"Secretive", val:0}, {text:"Honest", val:5}, {text:"Angry", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Which is an adjective? (Quickly, Blue, Happiness)", options: [{text:"Quickly", val:0}, {text:"Blue", val:5}, {text:"Happiness", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "He ____ working here since 2010.", options: [{text:"is", val:0}, {text:"has been", val:5}, {text:"was", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Synonym for 'CANDIDATE':", options: [{text:"Applicant", val:5}, {text:"Employer", val:0}, {text:"Reviewer", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "A group of fish is called a...?", options: [{text:"School", val:5}, {text:"Pack", val:0}, {text:"Swarm", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Antonym for 'TRANSPARENT':", options: [{text:"Clear", val:0}, {text:"Opaque", val:5}, {text:"Thin", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Prefix 'Anti-' means:", options: [{text:"Before", val:0}, {text:"Against", val:5}, {text:"Inside", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "If something is 'Obsolete', it is:", options: [{text:"New", val:0}, {text:"Outdated", val:5}, {text:"Useful", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Meaning of 'Biannual':", options: [{text:"Twice a year", val:5}, {text:"Every two years", val:0}, {text:"Once a month", val:0}] },

    // ==========================================
    // MODULE B: INTERESTS - RIASEC (120 Questions)
    // ==========================================

    // --- Realistic (20 Questions) ---
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I prefer working outdoors rather than in an office." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I enjoy maintaining and fixing cars or engines." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I like jobs that require physical strength and stamina." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I would rather build a cabinet than design its blueprint." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I enjoy operating heavy equipment or driving trucks." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I like working with electrical wiring and circuits." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I am comfortable getting my hands dirty at work." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I enjoy farming, planting crops, or raising animals." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I would like to be a construction worker or site manager." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I like using precise measuring tools like calipers and levels." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I prefer hobbies like woodworking, metalworking, or masonry." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I enjoy resolving plumbing issues." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I like surveying land and working with topography." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I would enjoy a career as a wildlife ranger or park warden." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I like reading manuals about how mechanical systems operate." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I find sitting at a desk all day completely exhausting." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I prefer actions and physical results over words and theories." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I enjoy repairing home appliances when they break down." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I am interested in joining the military or law enforcement." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I like putting things together following step-by-step physical instructions." },

    // --- Investigative (20 Questions) ---
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I love reading non-fiction books about science and history." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I enjoy writing complex code or computer algorithms." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I like analyzing statistics to find market trends." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I am fascinated by how the human brain and biology work." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I prefer working independently in a quiet lab environment." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I enjoy debating abstract philosophical concepts." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I like using microscopes, telescopes, or technical scientific gear." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I want to discover the cure for a disease or invent a new technology." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I enjoy solving advanced calculus or physics equations." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I would like to be an academic professor or university researcher." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I like writing detailed, evidence-based research papers." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I enjoy studying geology, weather patterns, or environmental science." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I like diagnosing diseases based on medical symptoms." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I am highly critical and skeptical of claims without proof." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I would enjoy working as an economist or financial analyst." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I love watching documentaries and educational videos." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I enjoy evaluating evidence to solve a mystery or crime." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I like learning about aerospace engineering and rocket science." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I enjoy reading journals about the latest technological advancements." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I prefer deep, intellectual conversations over small talk." },

    // --- Artistic (20 Questions) ---
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I enjoy designing logos, websites, or user interfaces." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I like writing fiction, poetry, or engaging blog posts." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I am passionate about photography and film editing." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I prefer working in environments without a strict dress code." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I enjoy choreographing dances or directing plays." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I like decorating my living space to reflect my personality." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I am interested in learning different foreign languages." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I prefer creative problem solving over following a manual." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I enjoy reviewing and critiquing movies, art, or literature." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I would like a career as a fashion designer or stylist." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I find immense joy in composing or playing music." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I like creating beautiful culinary dishes or baking." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I am drawn to careers in advertising and creative marketing." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I believe that art is essential for a functioning society." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I enjoy experimenting with different mediums like clay or watercolor." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I would rather visit a foreign country to experience its culture." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I like writing lyrics or producing beats in a studio." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I enjoy performing on stage in front of a live audience." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I like designing the layout and aesthetic of physical magazines." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I constantly look for new ways to express my internal emotions." },

    // --- Social (20 Questions) ---
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I enjoy coaching sports teams or organizing group activities." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I like advising people on their career or relationship choices." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I want a career where I directly interact with patients or clients." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I enjoy working as a tutor to help students pass exams." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I am passionate about social justice and human rights." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I like leading support groups or group therapy sessions." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I prefer to resolve workplace conflicts through open dialogue." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I enjoy taking care of elderly people or young children." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I would like to work as a social worker or family advocate." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I like volunteering at food banks or homeless shelters." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I find great joy in actively listening to people's life stories." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I would enjoy a career as a physical therapist or speech pathologist." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I am motivated by a feeling of community and belonging." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I enjoy onboarding and training new employees at a job." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I like being a host or tour guide, ensuring everyone has fun." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I prefer working in the non-profit sector over corporate business." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I enjoy helping people navigate complex governmental aid programs." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I am patient when dealing with people who are angry or upset." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I would like to work in public health or community wellness." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I feel responsible for the well-being of the people around me." },

    // --- Enterprising (20 Questions) ---
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I enjoy pitching new business ideas to potential investors." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I like running for student council or local political office." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I am driven by the desire to be a CEO or high-level executive." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I enjoy trading stocks or learning about investment strategies." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I like the thrill of making a high-value sales deal." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I prefer leading a team rather than being a follower." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I am comfortable making risky decisions to maximize profit." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I enjoy networking events and collecting business cards." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I would like to be a real estate broker or property developer." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I like negotiating contracts and finding loopholes in agreements." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I enjoy organizing large-scale business conferences." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I am confident in my ability to persuade skeptical people." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I would enjoy a career as a public relations manager." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I am motivated by status, respect, and prestige in my career." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I enjoy analyzing competitors and finding ways to beat them." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I like managing a store, restaurant, or retail business." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I enjoy taking on immense responsibility, even if it is stressful." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I would like to work as a talent agent or sports manager." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I am skilled at turning a failing project into a profitable one." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I believe that confident leadership is the key to any success." },

    // --- Conventional (20 Questions) ---
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I enjoy writing out detailed project plans and timelines." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I like working with numbers in accounting software." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I prefer working 9-to-5 with no unexpected overtime." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I am excellent at catching spelling and formatting errors." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I enjoy keeping track of inventory and stock levels." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I like working as an office manager or administrative assistant." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I am highly comfortable with repetitive, structured tasks." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I enjoy filing taxes or filling out complex legal forms." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I like writing standard operating procedures (SOPs) for others to follow." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I would enjoy a career as a data entry specialist." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I enjoy balancing my checkbook and managing personal finances." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I prefer knowing exactly what is expected of me every single day." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I like maintaining secure records and confidential files." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I would enjoy working as a court clerk or legal secretary." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I value rules and regulations more than creative flexibility." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I like working with payroll systems and calculating wages." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I enjoy organizing digital files into neat, labeled folders." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I would like a career in library science or archiving." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I feel stressed when my desk is messy or disorganized." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I believe that strict organization is the foundation of a good business." },


    // ==========================================
    // MODULE C: PERSONALITY - BIG-5 (120 Questions)
    // ==========================================

    // --- Conscientiousness (24 Questions) ---
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I create a to-do list every morning." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I rarely lose my keys or wallet." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I finish projects well before the deadline." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I like to set long-term goals and track my progress." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I am bothered by messy people." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I maintain a highly organized inbox and calendar." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I rarely cancel plans at the last minute." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I review my work thoroughly before submitting it." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I believe that hard work is more important than talent." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I keep my promises, even if it is inconvenient." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I am very careful with how I spend my money." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I avoid leaving things until the very last minute." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I pride myself on my strong work ethic." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I like to map out all possible scenarios before acting." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I quickly reply to emails and messages." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I keep a strict sleep schedule." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I am rarely late to appointments." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I ensure my workspace is tidy before I leave." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I follow instructions to the letter." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I am persistent when facing difficult tasks." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I avoid impulsive or reckless behavior." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I prefer routine over spontaneity." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I take my responsibilities very seriously." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I am known as the reliable one in my friend group." },

    // --- Extraversion (24 Questions) ---
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I actively seek out leadership roles." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I love telling stories to large groups." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I feel energized after attending a loud concert or festival." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I talk louder than most people I know." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I frequently initiate conversations with strangers on public transit." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I am very expressive with my hand gestures." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I prefer working in a bustling coffee shop over a quiet library." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I find it easy to make friends in a new city." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I enjoy spontaneous road trips with large groups." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I often host dinners or house parties." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I speak up immediately if I disagree with something in a meeting." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I hate spending weekends alone." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I thrive in fast-paced, high-interaction environments." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I am quick to introduce myself to new team members." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I use exclamation points and emojis frequently." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I enjoy being in the spotlight during a presentation." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I have a wide, extensive network of acquaintances." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I am generally described as bubbly or upbeat." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I naturally cheer and applaud loudly at events." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I find silence to be awkward and try to fill it." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I enjoy debates and lively banter." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I prefer group fitness classes over working out alone." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I freely share my personal life details with others." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I consider myself a deeply social creature." },

    // --- Agreeableness (24 Questions) ---
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I naturally trust people until they give me a reason not to." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I hate conflict and will avoid arguments whenever possible." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I frequently donate to charity." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I feel terrible if I accidentally offend someone." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I am known for being polite and courteous." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I will go out of my way to help a struggling coworker." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I prefer collaborating over competing for the top spot." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I find it easy to empathize with people from different backgrounds." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I try to make sure everyone's voice is heard in a meeting." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I am quick to apologize if I make a mistake." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I rarely criticize others, even if they deserve it." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I believe human nature is inherently good." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I have a lot of patience for people who are learning." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I enjoy comforting friends who are going through breakups." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I often put the needs of my family above my own." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I dislike harsh sarcasm or mean-spirited jokes." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I am highly cooperative in team projects." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I listen more than I speak when someone is upset." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I believe forgiveness is better than revenge." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I regularly express gratitude to service workers." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I rarely demand special treatment." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I find it easy to compromise in a negotiation." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I am deeply moved by sad movies or books." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I believe that kindness is a sign of strength." },

    // --- Openness (24 Questions) ---
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I love exploring art museums and historical ruins." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I enjoy engaging in deep, philosophical debates." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I frequently read books outside of my field of study." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I enjoy trying bizarre or exotic foods." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I am highly imaginative and daydream often." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I like breaking the rules to see what happens." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I prefer avant-garde movies over standard blockbusters." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I am very open to radically changing my political or religious views." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I enjoy writing poetry or creating digital art." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I am deeply curious about how the universe works." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I like listening to a wide variety of music genres." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I am fascinated by foreign cultures and traditions." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I believe that tradition should be questioned frequently." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I like coming up with out-of-the-box solutions." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I enjoy spending time in nature, observing plants and animals." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I often think about the future of humanity and technology." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I enjoy learning new software or technical tools." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I prefer traveling without an itinerary." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I am drawn to complex, abstract mathematical concepts." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I appreciate architecture and interior design." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I believe there is rarely a single 'right' way to live." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I enjoy discussing politics and social issues." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I am quick to adapt when a major plan changes." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I feel bored if I have to do the exact same thing every day." },

    // --- Emotional Stability (Neuroticism Reversed) (24 Questions) ---
    // Note: Likert 1-5. High score = High Stability
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I rarely lose my temper, even when provoked." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I do not panic when facing a tight deadline." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I fall asleep quickly and rarely suffer from insomnia." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I am highly resilient in the face of tragedy." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I don't hold onto anger for very long." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I can easily separate my self-worth from my job performance." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I rarely feel overwhelmed in crowds." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I am able to think logically during a crisis." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I rarely experience intense jealousy." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I am comfortable with uncertainty in my life." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I do not constantly worry about my health." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I accept constructive criticism without getting defensive." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I maintain a steady, even mood throughout the day." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I am not easily startled or scared." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I can easily brush off rude comments from strangers." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I don't obsess over past mistakes." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I feel secure in my relationships." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I rarely feel lonely or isolated." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I do not require constant reassurance from others." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I can meditate or relax without my mind racing." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I view failures as temporary, not permanent." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I avoid catastrophizing when something small goes wrong." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I am generally very content with who I am." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I can watch the news without becoming deeply distressed." }
];