const questionsPart5 = [
    // ==========================================
    // MODULE A: APTITUDE & COGNITIVE ABILITY (60 Questions)
    // ==========================================

    // --- Numerical Aptitude (20 Questions) ---
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "What is 60% of 200?", options: [{text:"100", val:0}, {text:"120", val:5}, {text:"140", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "If 9c = 81, what is the value of c?", options: [{text:"7", val:0}, {text:"9", val:5}, {text:"11", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "A car travels 150 miles in 2.5 hours. What is its average speed?", options: [{text:"55 mph", val:0}, {text:"60 mph", val:5}, {text:"65 mph", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "What is the square root of 64?", options: [{text:"6", val:0}, {text:"8", val:5}, {text:"10", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "A $120 item is discounted by 10%. What is the new price?", options: [{text:"$108", val:5}, {text:"$110", val:0}, {text:"$100", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "Solve: 8 + (4 × 3)", options: [{text:"36", val:0}, {text:"20", val:5}, {text:"24", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "What is 1/8 as a decimal?", options: [{text:"0.125", val:5}, {text:"0.150", val:0}, {text:"0.180", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "If 6 builders complete a task in 5 days, how many days for 10 builders?", options: [{text:"2 days", val:0}, {text:"3 days", val:5}, {text:"4 days", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "Area of a triangle with base 12 and height 6?", options: [{text:"72", val:0}, {text:"36", val:5}, {text:"18", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "A meeting starts at 9:20 AM and ends at 11:05 AM. Duration?", options: [{text:"1h 35m", val:0}, {text:"1h 45m", val:5}, {text:"2h 05m", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "What is the square root of 169?", options: [{text:"13", val:5}, {text:"14", val:0}, {text:"17", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "Next prime number after 41?", options: [{text:"42", val:0}, {text:"43", val:5}, {text:"45", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "If 1 foot = 12 inches, how many inches in 4.5 feet?", options: [{text:"52", val:0}, {text:"54", val:5}, {text:"56", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "What is 8 cubed (8³)?", options: [{text:"512", val:5}, {text:"256", val:0}, {text:"128", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "A $60 bill split among 4 people is?", options: [{text:"$12", val:0}, {text:"$15", val:5}, {text:"$20", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "Solve for x: 2x - 5 = 15", options: [{text:"10", val:5}, {text:"12", val:0}, {text:"8", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "A pie has 8 slices. You eat 5. Fraction remaining?", options: [{text:"5/8", val:0}, {text:"3/8", val:5}, {text:"1/4", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "Least Common Multiple (LCM) of 6 and 9?", options: [{text:"18", val:5}, {text:"36", val:0}, {text:"27", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "Probability of rolling an odd number on a standard die?", options: [{text:"1/3", val:0}, {text:"1/2", val:5}, {text:"1/6", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "Convert 0.35 to a simplified fraction.", options: [{text:"7/20", val:5}, {text:"35/100", val:0}, {text:"1/3", val:0}] },

    // --- Logical Reasoning (20 Questions) ---
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Sequence: 5, 25, 125, 625, __?", options: [{text:"3125", val:5}, {text:"1250", val:0}, {text:"2500", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Bird is to Nest as Bee is to...?", options: [{text:"Hive", val:5}, {text:"Honey", val:0}, {text:"Tree", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "No apples are bananas. All bananas are fruit. Are all apples fruit?", options: [{text:"Yes", val:0}, {text:"No", val:0}, {text:"Cannot be determined", val:5}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Odd one out: Car, Truck, Motorcycle, Helicopter?", options: [{text:"Helicopter", val:5}, {text:"Motorcycle", val:0}, {text:"Car", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "If A < B and B < C, which is true?", options: [{text:"A > C", val:0}, {text:"A < C", val:5}, {text:"A = C", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Sequence: Z, W, T, Q, __?", options: [{text:"M", val:0}, {text:"N", val:5}, {text:"P", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Teacher is to Chalk as Painter is to...?", options: [{text:"Canvas", val:0}, {text:"Brush", val:5}, {text:"Museum", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "If BAT is 23, CAT is 24, what is RAT?", options: [{text:"38", val:0}, {text:"39", val:5}, {text:"40", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "My mother's father's only daughter is my...?", options: [{text:"Aunt", val:0}, {text:"Mother", val:5}, {text:"Sister", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Sequence: 10.0, 9.5, 9.0, 8.5, __?", options: [{text:"8.0", val:5}, {text:"7.5", val:0}, {text:"8.2", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "All squares are rectangles. All rectangles are polygons. Are squares polygons?", options: [{text:"Yes", val:5}, {text:"No", val:0}, {text:"Maybe", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Thread is to Needle as Ink is to...?", options: [{text:"Paper", val:0}, {text:"Pen", val:5}, {text:"Book", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Odd one out: Winter, Summer, Spring, Rain.", options: [{text:"Rain", val:5}, {text:"Spring", val:0}, {text:"Winter", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Walk 10m East, turn right, walk 10m. Direction facing?", options: [{text:"South", val:5}, {text:"West", val:0}, {text:"North", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Sequence: 2, 5, 10, 17, 26, __?", options: [{text:"37", val:5}, {text:"35", val:0}, {text:"39", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Battery is to Flashlight as Engine is to...?", options: [{text:"Car", val:5}, {text:"Key", val:0}, {text:"Fuel", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "If today is Monday, what is the day 14 days from now?", options: [{text:"Sunday", val:0}, {text:"Monday", val:5}, {text:"Tuesday", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Some cats are black. All black animals are stealthy. Are some cats stealthy?", options: [{text:"Yes", val:5}, {text:"No", val:0}, {text:"Cannot be determined", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Odd one out: 12, 14, 15, 16, 18?", options: [{text:"15", val:5}, {text:"14", val:0}, {text:"18", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "If A=1, C=3, E=5, then G=?", options: [{text:"6", val:0}, {text:"7", val:5}, {text:"8", val:0}] },

    // --- Verbal Reasoning (20 Questions) ---
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Synonym for 'INDIGENOUS':", options: [{text:"Native", val:5}, {text:"Foreign", val:0}, {text:"Wealthy", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Antonym for 'CONCEAL':", options: [{text:"Hide", val:0}, {text:"Reveal", val:5}, {text:"Keep", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Meaning of 'under the weather':", options: [{text:"Raining", val:0}, {text:"Feeling sick", val:5}, {text:"Being outside", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Bark is to Dog as Meow is to...?", options: [{text:"Cat", val:5}, {text:"Cow", val:0}, {text:"Mouse", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Correct spelling:", options: [{text:"Priviledge", val:0}, {text:"Privilege", val:5}, {text:"Privelige", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "A person who studies insects is an...?", options: [{text:"Entomologist", val:5}, {text:"Etymologist", val:0}, {text:"Botanist", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Synonym for 'ZEALOUS':", options: [{text:"Apathetic", val:0}, {text:"Enthusiastic", val:5}, {text:"Angry", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Plural of 'Tooth':", options: [{text:"Tooths", val:0}, {text:"Teeth", val:5}, {text:"Teeths", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "A 'Neurologist' treats the...?", options: [{text:"Nervous System", val:5}, {text:"Kidneys", val:0}, {text:"Lungs", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Antonym for 'SUPERFICIAL':", options: [{text:"Deep", val:5}, {text:"Shallow", val:0}, {text:"Quick", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Odd word out: Sprint, Dash, Jog, Stand.", options: [{text:"Stand", val:5}, {text:"Jog", val:0}, {text:"Dash", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Meaning of 'Meticulous':", options: [{text:"Careless", val:0}, {text:"Very careful", val:5}, {text:"Messy", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Which is a pronoun? (They, Run, Beautiful)", options: [{text:"They", val:5}, {text:"Run", val:0}, {text:"Beautiful", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "She ____ the book yesterday.", options: [{text:"read", val:5}, {text:"reading", val:0}, {text:"reads", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Synonym for 'CANDID':", options: [{text:"Direct", val:5}, {text:"Secret", val:0}, {text:"Fake", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "A group of bees is called a...?", options: [{text:"Swarm", val:5}, {text:"Herd", val:0}, {text:"Flock", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Antonym for 'ARID':", options: [{text:"Dry", val:0}, {text:"Wet", val:5}, {text:"Hot", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Prefix 'Sub-' means:", options: [{text:"Above", val:0}, {text:"Below", val:5}, {text:"Around", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "If something is 'Fragile', it is:", options: [{text:"Easily broken", val:5}, {text:"Very strong", val:0}, {text:"Heavy", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Meaning of 'Centennial':", options: [{text:"100 years", val:5}, {text:"10 years", val:0}, {text:"1000 years", val:0}] },

    // ==========================================
    // MODULE B: INTERESTS - RIASEC (120 Questions)
    // ==========================================

    // --- Realistic (20 Questions) ---
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I prefer working with physical materials like wood or metal." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I enjoy learning how to fix my own vehicle." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I like jobs that require me to be physically active most of the day." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I would rather lay tiles than design the floor plan." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I enjoy operating heavy machinery or industrial equipment." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I like working with mechanical gears, levers, and pulleys." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I am comfortable working outside in various weather conditions." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I enjoy hands-on agricultural work or farming." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I would like to be an aviation mechanic or technician." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I like using specialized hand tools to complete a job." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I prefer hobbies that result in a tangible, physical object." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I enjoy finding and fixing leaks in plumbing systems." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I like mapping out physical spaces for landscaping." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I would enjoy a career in commercial diving or offshore work." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I like understanding how physical forces apply to construction." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I find long periods of desk work mentally draining." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I prefer to learn by doing rather than by reading." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I enjoy maintaining, cleaning, and sharpening my personal tools." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I am interested in careers involving physical security or patrol." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I like following a step-by-step physical process to build something." },

    // --- Investigative (20 Questions) ---
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I enjoy reading about astrophysics or quantum mechanics." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I like analyzing code to optimize its performance." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I am intrigued by demographic data and population studies." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I prefer to research a topic thoroughly before forming an opinion." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I enjoy writing comprehensive literature reviews." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I like designing controlled experiments." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I want to present my data findings to a panel of experts." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I enjoy reading detailed accounts of archaeological discoveries." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I like using complex algorithms to predict market trends." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I would enjoy working as a virologist or immunologist." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I like tracing a systemic issue back to its root cause." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I am fascinated by cognitive science and psychology." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I enjoy writing SQL queries to manipulate large databases." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I am highly skeptical of claims that lack empirical evidence." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I would like to work as an artificial intelligence researcher." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I enjoy understanding the molecular structure of compounds." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I like solving abstract algebraic proofs." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I would rather attend a scientific symposium than a party." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I enjoy studying the etymology and evolution of words." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I believe objective truth is the most important pursuit." },

    // --- Artistic (20 Questions) ---
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I enjoy creating mood boards for visual projects." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I like composing original music or melodies." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I am passionate about costume design for stage or screen." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I prefer working in a chaotic but inspiring environment." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I enjoy writing persuasive and creative advertising copy." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I like reimagining the visual branding of existing companies." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I am interested in improvisational comedy or acting." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I prefer projects that allow for subjective interpretation." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I enjoy critiquing the cinematography of classic films." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I would like a career as a professional sculptor or potter." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I find joy in studying diverse architectural movements." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I like designing repeating patterns for wallpapers or fabrics." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I am drawn to careers in 3D animation and rigging." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I believe that a beautiful design is just as important as its function." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I enjoy altering and modifying my clothing to be unique." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I would rather visit a contemporary art gallery than a history museum." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I like writing character backstories for novels or games." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I enjoy learning about the evolution of modern art." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I like arranging furniture to maximize flow and aesthetic." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I constantly try to evoke a specific mood through my creations." },

    // --- Social (20 Questions) ---
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I enjoy leading group therapy or support sessions." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I like providing guidance to those going through a crisis." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I want a career in gerontology or elder care." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I enjoy managing volunteer teams for non-profits." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I am passionate about advocating for educational reform." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I like assisting new immigrants with integration." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I prefer roles that demand extreme patience and empathy." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I enjoy working as a career counselor for young adults." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I would like to work in disaster relief and humanitarian aid." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I like championing the rights of minority groups." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I find great joy in mentoring individuals coming out of the prison system." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I would enjoy a career in pediatric nursing." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I am motivated by building strong community bonds." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I enjoy developing rehabilitation programs." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I like guiding families through difficult medical decisions." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I prefer working in settings focused on emotional healing." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I enjoy helping opposing groups find a peaceful compromise." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I am patient when assisting individuals with severe anxiety." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I would like to work as an employee wellness coordinator." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I feel that dedicating my life to helping others is my true calling." },

    // --- Enterprising (20 Questions) ---
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I enjoy negotiating salaries and compensation packages." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I like drafting business proposals to secure funding." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I am driven by the thrill of outperforming my sales targets." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I enjoy analyzing stock portfolios to maximize returns." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I like stepping up to take charge when a project is failing." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I prefer compensation structures heavily reliant on commission." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I am comfortable making swift, high-stakes executive choices." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I enjoy mingling at exclusive VIP networking events." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I would like to be the general manager of a large franchise." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I like acting as the face of a company in press releases." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I enjoy distributing budgets across multiple departments." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I am confident I can persuade someone to buy a product they didn't know they needed." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I would enjoy a career as an angel investor." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I am highly motivated by the prospect of executive promotions." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I enjoy studying competitor marketing to find an edge." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I like the responsibility of staffing an entire new department." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I enjoy leading aggressive public relations campaigns." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I would like to work as a strategic business consultant." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I am skilled at turning cold leads into dedicated customers." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I believe that aggressive expansion is the key to business survival." },

    // --- Conventional (20 Questions) ---
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I enjoy cross-referencing financial accounts for accuracy." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I like maintaining highly secure data logs." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I prefer working in an environment with a rigid chain of command." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I am excellent at formatting legal documents perfectly." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I enjoy calculating and distributing employee payroll." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I like working as a regulatory auditor." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I am highly comfortable with monotonous, predictable tasks." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I enjoy ensuring all corporate actions are legally compliant." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I like mapping out decision trees for office protocols." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I would enjoy a career as a risk management analyst." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I enjoy managing physical archives in a secure facility." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I prefer being evaluated on a strict, numerical rubric." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I like categorizing books or media using the Dewey Decimal System." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I would enjoy working as a customs or border inspector." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I value flawless accuracy over speed in my work." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I like processing and approving procurement requests." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I enjoy transcribing audio accurately into text documents." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I would like a career in municipal or city administration." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I feel stressed when coworkers bypass standard operating procedures." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I believe that maintaining immaculate records is vital to any operation." },

    // ==========================================
    // MODULE C: PERSONALITY - BIG-5 (120 Questions)
    // ==========================================

    // --- Conscientiousness (24 Questions) ---
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I layout my clothing the night before." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I rarely forget to pay bills on time." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I prefer to complete difficult chores early in the morning." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I set daily targets for my personal productivity." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I am disturbed when books are not shelved properly." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I keep a comprehensive log of my dietary intake." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I always arrive early to secure a good seat." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I triple-check important emails before sending them." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I believe willpower is the most important human trait." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I fulfill my duties even when I am feeling unwell." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I strictly adhere to my budget, avoiding impulse buys." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I hate leaving emails unread in my inbox." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I am highly structured in my approach to learning." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I evaluate all risks before agreeing to a project." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I return missed calls immediately." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I strictly follow the manufacturer's maintenance schedule for appliances." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I never ignore warning signs or safety protocols." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I regularly review and update my digital security." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I follow exercise regimens without missing days." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I am relentless in my pursuit of accuracy." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I avoid making commitments I know I cannot keep." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I prefer structured syllabus over self-guided study." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I take immense pride in my perfect attendance record." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I am the one who always remembers important anniversaries." },

    // --- Extraversion (24 Questions) ---
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I usually step up to lead group discussions." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I enjoy organizing massive community events." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I feel depressed if I spend an entire weekend alone." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I naturally project my voice across large rooms." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I easily strike up conversations with people in elevators." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I am highly animated and use my whole body to tell a story." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I prefer crowded, high-energy collaborative workspaces." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I am quick to hand out my business card at events." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I love participating in lively group competitions." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I often initiate plans for happy hour after work." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I loudly defend my viewpoint in heated debates." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I hate the thought of traveling solo." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I thrive in bustling, chaotic environments." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I am quick to propose group outings to new places." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I have a very loud and recognizable laugh." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I enjoy being the master of ceremonies at weddings." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I maintain an extensive network of thousands of contacts." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I am generally described as highly exuberant." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I naturally gravitate toward the dance floor at parties." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I find solitary activities like knitting incredibly boring." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I enjoy participating in loud panel discussions." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I prefer playing highly interactive team sports." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I talk through my problems out loud with others." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I consider myself a highly gregarious person." },

    // --- Agreeableness (24 Questions) ---
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I assume people's slights are just misunderstandings." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I am very uncomfortable delivering bad news." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I regularly donate to local food banks." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I feel immense guilt when I must discipline someone." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I am known for being highly agreeable and sweet." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I will happily share my notes with a struggling classmate." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I prefer finding a middle ground over proving I am right." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I am highly empathetic toward homeless individuals." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I make sure to highlight others' successes publicly." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I am quick to absorb blame to keep the team unified." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I rarely judge people for their past criminal history." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I believe society should focus more on rehabilitation than punishment." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I have endless patience with confused elderly people." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I am the person my coworkers vent to when stressed." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I often sacrifice my savings to help family members." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I strongly dislike practical jokes that embarrass people." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I am highly accommodating when someone has dietary restrictions." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I am a comforting presence in times of tragedy." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I believe that anger only poisons the person who feels it." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I regularly buy coffee or treats for my peers." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I rarely insist on choosing the movie or restaurant." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I easily concede small points in negotiations." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I am deeply moved by videos of people rescuing animals." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I believe that mercy is a crucial component of justice." },

    // --- Openness (24 Questions) ---
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I love exploring obscure underground art exhibits." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I enjoy discussing complex moral and ethical paradoxes." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I frequently read articles about quantum computing." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I enjoy trying highly experimental or avant-garde cuisine." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I am highly creative when solving problems without a guide." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I like questioning the validity of historical narratives." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I prefer foreign-language films over domestic blockbusters." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I am open to exploring deeply alternative spiritual practices." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I enjoy writing stream-of-consciousness journal entries." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I am deeply curious about the psychology of mass movements." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I like listening to experimental noise or ambient music." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I am fascinated by ancient pantheons and mythology." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I believe that subversive art is necessary for cultural growth." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I like finding completely new applications for existing technology." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I enjoy visiting rare botanical gardens or conservatories." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I often think about the future implications of genetic engineering." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I enjoy learning about advanced cryptography and ciphers." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I prefer taking unknown, unmapped routes when traveling." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I am drawn to surrealist and abstract expressionist art." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I appreciate dense, complex world-building in sci-fi novels." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I believe legal systems must constantly evolve with society." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I enjoy discussing grand geopolitical and economic strategies." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I am quick to adopt alternative or minimalist lifestyles." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I feel intellectually stimulated by highly abstract concepts." },

    // --- Emotional Stability (Neuroticism Reversed) (24 Questions) ---
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I rarely express frustration in heavy traffic." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I do not panic when my technology fails during a presentation." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I wake up feeling optimistic about the day's challenges." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I am highly resilient when facing academic failures." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I don't hold onto anger after a severe disagreement." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I can easily accept harsh critical reviews of my creative work." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I rarely feel anxious in tightly packed spaces." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I am able to maintain clear thought during physical emergencies." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I rarely envy the financial success of my friends." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I am comfortable adapting to last-minute travel changes." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I do not constantly worry about losing my job." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I view rejection as a natural part of the learning process." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I maintain a stable, pleasant mood even when exhausted." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I am not easily disturbed by sudden loud alarms." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I can easily brush off hostile comments online." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I don't dwell on embarrassing social faux pas from the past." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I feel secure in my long-term relationship choices." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I rarely feel unsupported by my family." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I do not rely on social media likes for my self-esteem." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I can practice deep breathing to instantly calm my heart rate." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I view sudden changes in leadership as normal corporate behavior." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I avoid catastrophizing when major projects are delayed." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I am generally very content with my current level of intelligence." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I can discuss highly stressful topics without getting overwhelmed or crying." }
];