const questionsPart7 = [
    // ==========================================
    // MODULE A: APTITUDE & COGNITIVE ABILITY (60 Questions)
    // ==========================================

    // --- Numerical Aptitude (20 Questions) ---
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "What is 25% of 600?", options: [{text:"125", val:0}, {text:"150", val:5}, {text:"175", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "If 12e = 144, what is the value of e?", options: [{text:"11", val:0}, {text:"12", val:5}, {text:"13", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "A runner completes 10 miles in 1.5 hours. Average speed?", options: [{text:"6.67 mph", val:5}, {text:"7.5 mph", val:0}, {text:"8.2 mph", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "What is the square root of 289?", options: [{text:"15", val:0}, {text:"17", val:5}, {text:"19", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "A $250 laptop is discounted by 20%. What is the new price?", options: [{text:"$180", val:0}, {text:"$200", val:5}, {text:"$220", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "Solve: 50 - (6 × 4)", options: [{text:"26", val:5}, {text:"18", val:0}, {text:"24", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "What is 5/8 as a decimal?", options: [{text:"0.525", val:0}, {text:"0.625", val:5}, {text:"0.675", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "If 10 workers can build a wall in 8 days, how long will 20 workers take?", options: [{text:"3 days", val:0}, {text:"4 days", val:5}, {text:"5 days", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "Area of a triangle with base 14 and height 8?", options: [{text:"56", val:5}, {text:"112", val:0}, {text:"48", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "A train leaves at 4:30 PM and arrives at 8:15 PM. Duration?", options: [{text:"3h 30m", val:0}, {text:"3h 45m", val:5}, {text:"4h 15m", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "What is the square root of 324?", options: [{text:"16", val:0}, {text:"18", val:5}, {text:"20", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "Next prime number after 53?", options: [{text:"55", val:0}, {text:"57", val:0}, {text:"59", val:5}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "If 1 yard = 3 feet, how many feet in 7.5 yards?", options: [{text:"21.5", val:0}, {text:"22.5", val:5}, {text:"23.5", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "What is 10 cubed (10³)?", options: [{text:"100", val:0}, {text:"1000", val:5}, {text:"10000", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "A $400 prize divided among 8 people is?", options: [{text:"$40", val:0}, {text:"$50", val:5}, {text:"$60", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "Solve for z: 6z - 18 = 24", options: [{text:"6", val:0}, {text:"7", val:5}, {text:"8", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "A cake has 20 slices. You eat 5. Fraction remaining?", options: [{text:"3/4", val:5}, {text:"1/4", val:0}, {text:"1/5", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "Least Common Multiple (LCM) of 6 and 8?", options: [{text:"14", val:0}, {text:"24", val:5}, {text:"48", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "Probability of drawing a spade from a standard deck?", options: [{text:"1/2", val:0}, {text:"1/4", val:5}, {text:"1/13", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "Convert 0.55 to a simplified fraction.", options: [{text:"11/20", val:5}, {text:"55/100", val:0}, {text:"5/10", val:0}] },

    // --- Logical Reasoning (20 Questions) ---
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Sequence: 2, 8, 32, 128, __?", options: [{text:"256", val:0}, {text:"512", val:5}, {text:"1024", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Camera is to Photo as Printer is to...?", options: [{text:"Computer", val:0}, {text:"Document", val:5}, {text:"Ink", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "All planets are round. Earth is a planet. Is Earth round? (Based on premise)", options: [{text:"Yes", val:5}, {text:"No", val:0}, {text:"Cannot be determined", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Odd one out: Python, Java, C++, Keyboard?", options: [{text:"Keyboard", val:5}, {text:"Python", val:0}, {text:"Java", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "If M > N and N > O, who is the smallest?", options: [{text:"M", val:0}, {text:"N", val:0}, {text:"O", val:5}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Sequence: D, G, J, M, __?", options: [{text:"P", val:5}, {text:"O", val:0}, {text:"N", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Carpenter is to Wood as Tailor is to...?", options: [{text:"Needle", val:0}, {text:"Fabric", val:5}, {text:"Clothes", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "If SUN is 54, MOON is 57, what is STAR?", options: [{text:"58", val:5}, {text:"56", val:0}, {text:"60", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "My father's sister's only son is my...?", options: [{text:"Brother", val:0}, {text:"Cousin", val:5}, {text:"Nephew", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Sequence: 64, 32, 16, 8, __?", options: [{text:"4", val:5}, {text:"6", val:0}, {text:"2", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Some houses are white. All white things are clean. Are some houses clean?", options: [{text:"Yes", val:5}, {text:"No", val:0}, {text:"Cannot be determined", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Lock is to Key as Maze is to...?", options: [{text:"Puzzle", val:0}, {text:"Map", val:0}, {text:"Solution", val:5}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Odd one out: Mars, Jupiter, Moon, Saturn.", options: [{text:"Moon", val:5}, {text:"Mars", val:0}, {text:"Jupiter", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Walk 20m East, turn left, walk 5m North. Direction facing?", options: [{text:"East", val:0}, {text:"North", val:5}, {text:"West", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Sequence: 2, 4, 7, 11, 16, __?", options: [{text:"20", val:0}, {text:"22", val:5}, {text:"24", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Oven is to Baking as Fridge is to...?", options: [{text:"Cooling", val:5}, {text:"Food", val:0}, {text:"Ice", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "If the 3rd of the month is a Monday, what day is the 24th?", options: [{text:"Monday", val:5}, {text:"Tuesday", val:0}, {text:"Sunday", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "All trees have leaves. A pine is a tree. Does a pine have leaves? (Based strictly on premise)", options: [{text:"Yes", val:5}, {text:"No", val:0}, {text:"Cannot be determined", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Odd one out: 24, 36, 48, 54, 61?", options: [{text:"61", val:5}, {text:"54", val:0}, {text:"48", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "If A=1, B=2, C=3, then J=?", options: [{text:"9", val:0}, {text:"10", val:5}, {text:"11", val:0}] },

    // --- Verbal Reasoning (20 Questions) ---
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Synonym for 'TRANQUIL':", options: [{text:"Noisy", val:0}, {text:"Peaceful", val:5}, {text:"Angry", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Antonym for 'FLEXIBLE':", options: [{text:"Rigid", val:5}, {text:"Soft", val:0}, {text:"Smooth", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Meaning of 'beat around the bush':", options: [{text:"Avoid the main point", val:5}, {text:"Gardening", val:0}, {text:"Run fast", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Engine is to Car as CPU is to...?", options: [{text:"Computer", val:5}, {text:"Keyboard", val:0}, {text:"Screen", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Correct spelling:", options: [{text:"Neccessary", val:0}, {text:"Necessary", val:5}, {text:"Necesary", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "A person who studies the mind is a...?", options: [{text:"Psychologist", val:5}, {text:"Biologist", val:0}, {text:"Sociologist", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Synonym for 'GREGARIOUS':", options: [{text:"Sociable", val:5}, {text:"Shy", val:0}, {text:"Angry", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Plural of 'Thesis':", options: [{text:"Thesises", val:0}, {text:"Theses", val:5}, {text:"Thesis", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "A 'Pediatrician' treats...?", options: [{text:"Children", val:5}, {text:"Elderly", val:0}, {text:"Feet", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Antonym for 'ARROGANT':", options: [{text:"Humble", val:5}, {text:"Proud", val:0}, {text:"Loud", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Odd word out: Beautiful, Gorgeous, Stunning, Ugly.", options: [{text:"Ugly", val:5}, {text:"Beautiful", val:0}, {text:"Gorgeous", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Meaning of 'Ubiquitous':", options: [{text:"Rare", val:0}, {text:"Found everywhere", val:5}, {text:"Expensive", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Which is an adverb? (Quickly, House, Blue)", options: [{text:"Quickly", val:5}, {text:"House", val:0}, {text:"Blue", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "I have ____ my keys.", options: [{text:"loose", val:0}, {text:"lost", val:5}, {text:"losed", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Synonym for 'Amiable':", options: [{text:"Hostile", val:0}, {text:"Friendly", val:5}, {text:"Quiet", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "A group of sheep is called a...?", options: [{text:"Flock", val:5}, {text:"Herd", val:0}, {text:"Pack", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Antonym for 'GENUINE':", options: [{text:"Fake", val:5}, {text:"Real", val:0}, {text:"Solid", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Prefix 'Pro-' means:", options: [{text:"Against", val:0}, {text:"For/Before", val:5}, {text:"After", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "If something is 'Opaque', it is:", options: [{text:"Clear", val:0}, {text:"Not letting light through", val:5}, {text:"Fragile", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Meaning of 'Biennial':", options: [{text:"Every two years", val:5}, {text:"Twice a year", val:0}, {text:"Once a year", val:0}] },

    // ==========================================
    // MODULE B: INTERESTS - RIASEC (120 Questions)
    // ==========================================

    // --- Realistic (20 Questions) ---
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I enjoy assembling furniture from flat-pack boxes." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I would rather be moving around than sitting at a desk." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I like fixing broken electronics around the house." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I enjoy working in construction or carpentry." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I like tasks that require physical endurance." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I prefer practical, hands-on learning over reading textbooks." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I enjoy maintaining and caring for outdoor landscapes." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I like operating complex machinery or heavy equipment." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I am comfortable working with tools like drills and saws." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I enjoy troubleshooting mechanical problems in vehicles." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I prefer hobbies like model building or woodworking." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I like understanding how different parts fit together." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I find satisfaction in seeing a physical project completed." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I enjoy tasks that involve physical precision and coordination." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I would like a career that involves working with animals or agriculture." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I like learning survival skills or outdoor techniques." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I prefer environments where I can work with my hands." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I enjoy the physical challenge of demanding work." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I like using specialized equipment for specific tasks." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I am interested in careers like plumbing, electrical, or HVAC." },

    // --- Investigative (20 Questions) ---
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I enjoy reading scientific journals and articles." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I like analyzing data to find hidden trends." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I am fascinated by how biological systems function." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I prefer solving complex puzzles over simple tasks." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I enjoy writing detailed research papers." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I like testing hypotheses through experimentation." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I want to discover new information in my field." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I enjoy studying subjects like chemistry or physics." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I like using logic to evaluate different arguments." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I would enjoy working as a laboratory researcher." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I like investigating the root causes of problems." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I am interested in learning about artificial intelligence." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I enjoy analyzing historical data to understand events." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I am critical of information that lacks evidence." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I would like to work as an academic or professor." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I enjoy understanding the mathematics behind concepts." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I like working independently on challenging intellectual tasks." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I would rather attend a seminar on new technology than a party." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I enjoy exploring complex philosophical or ethical questions." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I believe that rational analysis is the key to progress." },

    // --- Artistic (20 Questions) ---
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I enjoy painting, drawing, or other visual arts." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I like expressing my feelings through creative writing." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I am passionate about acting or performing on stage." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I prefer environments that allow for creative freedom." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I enjoy designing the layout of documents or presentations." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I like creating original music or playing an instrument." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I am interested in fashion design or styling." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I prefer tasks that require imagination and originality." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I enjoy analyzing literature or film for hidden meanings." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I would like a career as a creative director." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I find joy in visiting museums and art exhibitions." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I like developing unique concepts for projects." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I am drawn to careers in architecture or interior design." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I believe that aesthetics are an important part of life." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I enjoy experimenting with different artistic mediums." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I would rather watch an indie film than a blockbuster." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I like brainstorming creative solutions to problems." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I enjoy learning about different cultural art forms." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I like personalizing my workspace with art and decorations." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I constantly seek inspiration for my creative projects." },

    // --- Social (20 Questions) ---
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I enjoy helping people solve their personal problems." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I like teaching or training others in new skills." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I want a career where I can make a positive impact on society." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I enjoy volunteering for community service projects." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I am passionate about counseling and mental health." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I like working collaboratively in a team environment." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I prefer roles that require empathy and understanding." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I enjoy advising students on their academic or career goals." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I would like to work in healthcare or nursing." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I like mediating conflicts and helping people compromise." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I find great joy in seeing others succeed." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I would enjoy a career as a social worker." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I am motivated by a desire to support and uplift others." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I enjoy organizing group activities or social events." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I like providing care for children or the elderly." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I prefer working in environments focused on human services." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I enjoy listening to people's concerns and offering support." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I am patient when communicating with individuals who are upset." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I would like to work in human resources, focusing on employee well-being." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I feel that building strong relationships is the most important part of a job." },

    // --- Enterprising (20 Questions) ---
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I enjoy leading projects and taking charge of a team." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I like pitching ideas or products to clients." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I am driven by the opportunity to start my own business." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I enjoy developing strategies to increase profitability." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I like making decisions that impact the direction of an organization." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I prefer roles that offer leadership and management opportunities." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I am comfortable negotiating deals and contracts." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I enjoy participating in competitive business environments." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I would like to be a political leader or campaign manager." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I like networking and building professional connections." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I enjoy giving presentations to influence an audience." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I am confident in my ability to persuade others to my point of view." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I would enjoy a career as an executive or CEO." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I am highly motivated by financial rewards and status." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I enjoy analyzing market trends to find new business opportunities." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I like the challenge of managing a large budget." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I enjoy leading marketing or promotional campaigns." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I would like to work as a real estate broker or agent." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I am skilled at motivating a team to achieve high goals." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I believe that strong leadership is necessary for organizational success." },

    // --- Conventional (20 Questions) ---
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I enjoy organizing data in spreadsheets or databases." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I like keeping accurate financial records." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I prefer working in an environment with clear rules and procedures." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I am excellent at paying attention to small details." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I enjoy tasks that require high levels of accuracy and precision." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I like working as an accountant or bookkeeper." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I am highly comfortable with structured, routine work." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I enjoy ensuring compliance with regulations and standards." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I like creating filing systems to keep documents organized." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I would enjoy a career in administrative support or office management." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I enjoy categorizing information systematically." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I prefer clear expectations and well-defined tasks." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I like reviewing documents for errors or inconsistencies." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I would enjoy working as a data entry specialist." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I value efficiency and order in my workspace." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I like processing forms and applications." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I enjoy managing inventory or supply chains." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I would like a career in banking or finance operations." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I feel stressed when work processes are disorganized." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I believe that careful planning and documentation prevent errors." },

    // ==========================================
    // MODULE C: PERSONALITY - BIG-5 (120 Questions)
    // ==========================================

    // --- Conscientiousness (24 Questions) ---
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I plan my work schedule carefully." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I rarely miss deadlines." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I prefer to tackle the most important tasks first." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I set specific goals for my projects." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I am disturbed when things are left incomplete." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I keep a detailed calendar of my appointments." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I consistently follow through on my promises." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I rigorously check my facts before presenting them." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I believe that being organized reduces stress." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I complete my chores before engaging in leisure activities." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I strictly adhere to established procedures." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I hate feeling unprepared for a meeting." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I am highly focused when working on complex tasks." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I evaluate all details before starting a task." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I promptly handle administrative duties." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I follow rules carefully, even when unsupervised." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I never leave my workspace messy." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I regularly review my progress toward goals." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I follow my daily routines consistently." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I am determined to meet high standards of quality." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I avoid acting impulsively in professional settings." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I prefer working in environments with clear structures." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I take pride in my attention to detail." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I am known for my methodical approach to work." },

    // --- Extraversion (24 Questions) ---
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I typically enjoy being the center of attention." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I enjoy hosting parties and gatherings." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I feel energized after interacting with a large group." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I naturally take charge in social situations." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I easily make friends wherever I go." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I am highly expressive and talkative." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I prefer working on collaborative team projects." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I am quick to engage in conversation with strangers." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I love participating in group discussions." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I often initiate social activities with colleagues." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I confidently share my ideas in meetings." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I dislike working in isolation for extended periods." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I thrive in dynamic and interactive environments." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I am quick to suggest new group initiatives." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I have a lively and energetic demeanor." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I enjoy speaking publicly." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I maintain a wide circle of friends and acquaintances." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I am generally described as enthusiastic." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I naturally seek out opportunities for networking." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I find solitary tasks to be less engaging." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I enjoy participating in brainstorming sessions." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I prefer working in lively settings." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I tend to communicate my thoughts openly and frequently." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I consider myself a highly sociable individual." },

    // --- Agreeableness (24 Questions) ---
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I assume people are generally honest." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I am uncomfortable with confrontation." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I regularly offer help to those in need." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I feel bad when I have to deliver negative feedback." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I am known for being cooperative and supportive." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I will go out of my way to assist a team member." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I prefer to reach a consensus rather than argue." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I am highly sympathetic to others' problems." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I make sure to acknowledge the efforts of others." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I try to maintain harmony in group settings." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I rarely hold grudges." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I believe people should be treated with kindness and respect." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I have a lot of patience when dealing with difficult situations." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I am often the one people turn to for a sympathetic ear." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I often put the needs of others before my own." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I dislike seeing others treated unfairly." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I am very considerate of others' feelings." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I listen carefully when others share their concerns." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I believe that cooperation is better than competition." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I regularly express thanks for others' help." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I rarely demand my own way in a group." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I easily compromise to avoid arguments." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I am deeply moved by stories of human kindness." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I believe that understanding others is a key to success." },

    // --- Openness (24 Questions) ---
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I love exploring new ideas and concepts." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I enjoy discussing theoretical topics." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I frequently read about subjects outside my expertise." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I enjoy trying new activities or hobbies." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I am highly imaginative." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I like questioning traditional ways of doing things." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I prefer tasks that require creative problem-solving." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I am open to reconsidering my beliefs." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I enjoy engaging with art and literature." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I am deeply curious about how different cultures operate." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I like listening to diverse types of music." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I am fascinated by abstract concepts." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I believe society benefits from diversity of thought." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I like finding new solutions to old problems." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I enjoy visiting places I have never been to before." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I often think about philosophical or ethical questions." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I enjoy learning about new scientific discoveries." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I prefer to be flexible and adaptable in my plans." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I am drawn to creative and artistic pursuits." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I appreciate deep and meaningful conversations." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I believe it's important to keep an open mind." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I enjoy discussing different political perspectives." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I am quick to embrace new experiences." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I feel intellectually stimulated by learning." },

    // --- Emotional Stability (Neuroticism Reversed) (24 Questions) ---
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I rarely feel overwhelmed by stress." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I do not panic when things go wrong." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I generally maintain a calm demeanor." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I am highly resilient in the face of difficulties." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I don't hold onto negative emotions for long." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I can handle criticism without becoming defensive." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I rarely feel anxious about everyday situations." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I am able to stay focused under pressure." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I rarely feel envious of others." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I am comfortable dealing with uncertainty." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I do not spend a lot of time worrying." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I view challenges as opportunities for growth." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I maintain an even temper." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I am not easily rattled by unexpected events." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I can easily let go of minor frustrations." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I don't dwell on past regrets." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I feel secure in my abilities." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I rarely feel insecure or inadequate." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I do not rely on others to validate my self-worth." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I can easily relax after a stressful day." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I view change as a normal part of life." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I avoid catastrophizing." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I am generally satisfied with myself." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I can discuss difficult topics calmly." }
];