const questionsPart10 = [
    // ==========================================
    // MODULE A: APTITUDE & COGNITIVE ABILITY (60 Questions)
    // ==========================================

    // --- Numerical Aptitude (20 Questions) ---
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "What is 55% of 300?", options: [{text:"150", val:0}, {text:"165", val:5}, {text:"180", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "If 14h = 168, what is the value of h?", options: [{text:"11", val:0}, {text:"12", val:5}, {text:"13", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "A pilot flies 450 miles in 1.5 hours. Average speed?", options: [{text:"250 mph", val:0}, {text:"300 mph", val:5}, {text:"350 mph", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "What is the square root of 529?", options: [{text:"21", val:0}, {text:"23", val:5}, {text:"25", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "A $600 sofa is discounted by 30%. What is the new price?", options: [{text:"$400", val:0}, {text:"$420", val:5}, {text:"$450", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "Solve: (18 / 3) × 4", options: [{text:"20", val:0}, {text:"24", val:5}, {text:"28", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "What is 7/8 as a decimal?", options: [{text:"0.825", val:0}, {text:"0.875", val:5}, {text:"0.925", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "If 5 programmers can build an app in 6 days, how long will 10 programmers take?", options: [{text:"2 days", val:0}, {text:"3 days", val:5}, {text:"4 days", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "Area of a rectangle with length 25 and width 10?", options: [{text:"200", val:0}, {text:"250", val:5}, {text:"300", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "A workshop starts at 8:45 AM and ends at 11:30 AM. Duration?", options: [{text:"2h 30m", val:0}, {text:"2h 45m", val:5}, {text:"3h 15m", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "What is the square root of 1225?", options: [{text:"30", val:0}, {text:"35", val:5}, {text:"45", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "Next prime number after 79?", options: [{text:"81", val:0}, {text:"83", val:5}, {text:"85", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "If 1 pound = 16 ounces, how many ounces in 5.5 pounds?", options: [{text:"80", val:0}, {text:"88", val:5}, {text:"96", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "What is 4 to the power of 4 (4^4)?", options: [{text:"128", val:0}, {text:"256", val:5}, {text:"512", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "A $800 jackpot divided among 5 people is?", options: [{text:"$140", val:0}, {text:"$160", val:5}, {text:"$180", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "Solve for v: 8v - 16 = 48", options: [{text:"6", val:0}, {text:"8", val:5}, {text:"10", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "A pie has 12 slices. You eat 8. Fraction remaining?", options: [{text:"1/4", val:0}, {text:"1/3", val:5}, {text:"1/2", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "Least Common Multiple (LCM) of 9 and 15?", options: [{text:"30", val:0}, {text:"45", val:5}, {text:"60", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "Probability of rolling a number less than 3 on a standard die?", options: [{text:"1/6", val:0}, {text:"1/3", val:5}, {text:"1/2", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "Convert 0.65 to a simplified fraction.", options: [{text:"11/20", val:0}, {text:"13/20", val:5}, {text:"65/100", val:0}] },

    // --- Logical Reasoning (20 Questions) ---
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Sequence: 3, 12, 48, 192, __?", options: [{text:"384", val:0}, {text:"768", val:5}, {text:"576", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Train is to Tracks as Boat is to...?", options: [{text:"Water", val:5}, {text:"Sail", val:0}, {text:"Anchor", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "All poets are writers. Some writers are famous. Are some poets famous?", options: [{text:"Yes", val:0}, {text:"No", val:0}, {text:"Cannot be determined", val:5}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Odd one out: Brick, Cement, Glass, Cloud?", options: [{text:"Cloud", val:5}, {text:"Glass", val:0}, {text:"Cement", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "If A > B and B = C, which is true?", options: [{text:"A < C", val:0}, {text:"A = C", val:0}, {text:"A > C", val:5}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Sequence: M, K, I, G, __?", options: [{text:"E", val:5}, {text:"F", val:0}, {text:"D", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Plumber is to Pipe as Electrician is to...?", options: [{text:"Wire", val:5}, {text:"Switch", val:0}, {text:"Light", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "If ONE is 3, TWO is 3, what is THREE?", options: [{text:"3", val:0}, {text:"4", val:0}, {text:"5", val:5}] }, // Based on letter count
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "My brother's wife's father is my sister-in-law's...?", options: [{text:"Brother", val:0}, {text:"Father", val:5}, {text:"Uncle", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Sequence: 500, 100, 20, 4, __?", options: [{text:"1", val:0}, {text:"0.8", val:5}, {text:"0.4", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Some cars are fast. All fast things are dangerous. Are some cars dangerous?", options: [{text:"Yes", val:5}, {text:"No", val:0}, {text:"Cannot be determined", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Keyboard is to Typing as Screen is to...?", options: [{text:"Displaying", val:5}, {text:"Watching", val:0}, {text:"Touching", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Odd one out: Triangle, Hexagon, Circle, Octagon.", options: [{text:"Circle", val:5}, {text:"Hexagon", val:0}, {text:"Triangle", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Walk 5m East, turn left, walk 20m. Direction facing?", options: [{text:"North", val:5}, {text:"West", val:0}, {text:"South", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Sequence: 1, 5, 14, 30, 55, __?", options: [{text:"81", val:0}, {text:"91", val:5}, {text:"101", val:0}] }, // Differences: 4, 9, 16, 25, 36 (Squares)
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Broom is to Sweeping as Mop is to...?", options: [{text:"Mopping", val:5}, {text:"Cleaning", val:0}, {text:"Floor", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "If the 7th of the month is a Saturday, what day is the 21st?", options: [{text:"Saturday", val:5}, {text:"Sunday", val:0}, {text:"Friday", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "All mammals have hair. A dolphin is a mammal. Does a dolphin have hair? (Based strictly on premise)", options: [{text:"Yes", val:5}, {text:"No", val:0}, {text:"Cannot be determined", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Odd one out: 27, 45, 63, 72, 83?", options: [{text:"83", val:5}, {text:"72", val:0}, {text:"63", val:0}] }, // Others are divisible by 9
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "If D=4, H=8, L=12, then P=?", options: [{text:"14", val:0}, {text:"16", val:5}, {text:"18", val:0}] },

    // --- Verbal Reasoning (20 Questions) ---
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Synonym for 'ADVOCATE':", options: [{text:"Opponent", val:0}, {text:"Supporter", val:5}, {text:"Judge", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Antonym for 'TANGIBLE':", options: [{text:"Abstract", val:5}, {text:"Solid", val:0}, {text:"Real", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Meaning of 'cut corners':", options: [{text:"Do something poorly to save time", val:5}, {text:"Build a box", val:0}, {text:"Run fast", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Roots are to Tree as Foundation is to...?", options: [{text:"Building", val:5}, {text:"Cement", val:0}, {text:"Ground", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Correct spelling:", options: [{text:"Reccommend", val:0}, {text:"Recommend", val:5}, {text:"Recomend", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "A person who studies the ocean is an...?", options: [{text:"Oceanographer", val:5}, {text:"Astronomer", val:0}, {text:"Geologist", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Synonym for 'LUCID':", options: [{text:"Confusing", val:0}, {text:"Clear", val:5}, {text:"Dark", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Plural of 'Datum':", options: [{text:"Datums", val:0}, {text:"Data", val:5}, {text:"Datas", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "An 'Oncologist' treats...?", options: [{text:"Cancer", val:5}, {text:"Bones", val:0}, {text:"Teeth", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Antonym for 'HOSTILE':", options: [{text:"Friendly", val:5}, {text:"Angry", val:0}, {text:"Loud", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Odd word out: Trivial, Minor, Insignificant, Crucial.", options: [{text:"Crucial", val:5}, {text:"Trivial", val:0}, {text:"Minor", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Meaning of 'Frugal':", options: [{text:"Extravagant", val:0}, {text:"Economical", val:5}, {text:"Angry", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Which is an adjective? (Run, Beautiful, Quickly)", options: [{text:"Beautiful", val:5}, {text:"Run", val:0}, {text:"Quickly", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "She ____ written the report already.", options: [{text:"has", val:5}, {text:"have", val:0}, {text:"is", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Synonym for 'PRAGMATIC':", options: [{text:"Practical", val:5}, {text:"Idealistic", val:0}, {text:"Theoretical", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "A group of fish is called a...?", options: [{text:"School", val:5}, {text:"Pack", val:0}, {text:"Herd", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Antonym for 'VAGUE':", options: [{text:"Clear", val:5}, {text:"Unclear", val:0}, {text:"Dim", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Prefix 'Trans-' means:", options: [{text:"Under", val:0}, {text:"Across/Beyond", val:5}, {text:"Before", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "If something is 'Infallible', it is:", options: [{text:"Incapable of making mistakes", val:5}, {text:"Likely to fail", val:0}, {text:"Weak", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Meaning of 'Centennial':", options: [{text:"Every 100 years", val:5}, {text:"Every 10 years", val:0}, {text:"Every 1000 years", val:0}] },

    // ==========================================
    // MODULE B: INTERESTS - RIASEC (120 Questions)
    // ==========================================

    // --- Realistic (20 Questions) ---
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I prefer working on tangible products rather than abstract ideas." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I enjoy learning how to weld or solder metals." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I like jobs that require me to be outdoors in nature." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I would rather build a bridge than write a report about one." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I enjoy operating commercial vehicles or trains." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I like working with mechanical schematics and blueprints." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I am comfortable working in physically hazardous environments safely." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I enjoy working with timber and building wooden structures." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I would like to be a commercial pilot or ship captain." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I like using heavy duty power tools on a daily basis." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I prefer hobbies that require me to fix broken items around the house." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I enjoy troubleshooting complex machinery when it fails." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I like installing physical network cables or fiber optics." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I would enjoy a career as a general contractor." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I like understanding the aerodynamics or physics of physical objects." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I find writing essays and attending meetings to be tedious." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I prefer learning through apprenticeship and physical repetition." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I enjoy taking care of horses, cattle, or livestock." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I am interested in careers involving maritime or ocean work." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I like physically turning raw materials into finished goods." },

    // --- Investigative (20 Questions) ---
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I enjoy reading complex manuals about how software works." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I like analyzing large spreadsheets to locate anomalies." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I am fascinated by the study of microscopic organisms." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I prefer conducting independent research over group discussions." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I enjoy writing white papers detailing scientific phenomena." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I like formulating mathematical models to describe reality." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I want to publish a groundbreaking study in my field." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I enjoy studying geology and the formation of the earth." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I like using logic to dismantle flawed arguments." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I would enjoy working as a quantitative analyst." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I like investigating complex technical failures to find the exact cause." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I am interested in learning about advanced robotics." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I enjoy analyzing behavioral data to predict human actions." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I am critical of subjective opinions pretending to be facts." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I would like to work as a data scientist or statistician." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I enjoy understanding the algorithms that drive search engines." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I like working on problems that take days or weeks to fully solve." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I would rather visit an observatory than an art gallery." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I enjoy exploring complex astronomical concepts." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I believe that the scientific method is the ultimate tool for truth." },

    // --- Artistic (20 Questions) ---
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I enjoy creating 3D models or digital sculptures." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I like writing screenplays for independent films." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I am passionate about expressing my identity through fashion." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I prefer workspaces that have vibrant colors and unique decor." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I enjoy writing melodic compositions for different instruments." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I like sketching concepts for video game characters." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I am interested in directing stage productions." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I prefer assignments that let me interpret the rules creatively." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I enjoy analyzing the brush strokes and techniques in classic paintings." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I would like a career as a concept artist." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I find joy in visiting underground music venues." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I like developing intricate plots for stories." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I am drawn to careers in landscape architecture." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I believe that creativity is just as important as logic." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I enjoy experimenting with digital photography editing." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I would rather read a book of poems than an encyclopedia." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I like brainstorming visually striking marketing campaigns." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I enjoy learning about the evolution of typography and fonts." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I like arranging physical spaces to create a specific emotional response." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I constantly seek out new forms of media to inspire my own work." },

    // --- Social (20 Questions) ---
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I enjoy helping individuals navigate the healthcare system." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I like teaching language skills to non-native speakers." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I want a career where my primary goal is community enrichment." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I enjoy volunteering at local animal shelters or rescues." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I am passionate about providing grief counseling." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I like working collaboratively to resolve community disputes." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I prefer roles that require me to deeply understand others' backgrounds." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I enjoy advising teenagers on overcoming peer pressure." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I would like to work as a specialized therapist." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I like mediating conflicts between family members." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I find great joy in assisting people in their personal recovery." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I would enjoy a career as a public health advocate." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I am motivated by a desire to ensure everyone feels included." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I enjoy organizing support networks for vulnerable populations." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I like providing direct care for those recovering from surgery." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I prefer working in environments focused on holistic wellness." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I enjoy listening to people who feel they have no one else to talk to." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I am patient when communicating with individuals who are confused." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I would like to work in a role focused entirely on employee satisfaction." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I feel that helping society's most vulnerable is a moral duty." },

    // --- Enterprising (20 Questions) ---
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I enjoy leading aggressive sales initiatives." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I like pitching high-risk, high-reward concepts to executives." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I am driven by the opportunity to dominate a market." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I enjoy developing strategies to drastically cut corporate costs." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I like making executive decisions that affect hundreds of employees." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I prefer roles that offer immense public visibility and status." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I am comfortable negotiating aggressive corporate mergers." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I enjoy participating in highly competitive corporate environments." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I would like to be an elected public official." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I like networking with billionaires and industry titans." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I enjoy giving presentations to convince shareholders." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I am confident in my ability to persuade almost anyone." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I would enjoy a career as an aggressive litigation attorney." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I am highly motivated by accumulating wealth and power." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I enjoy analyzing global markets to find lucrative trade opportunities." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I like the challenge of managing a massive, multi-national budget." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I enjoy leading massive product launches." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I would like to work as a high-end corporate consultant." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I am skilled at motivating a lazy team to hit record numbers." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I believe that ruthless competition breeds the best results." },

    // --- Conventional (20 Questions) ---
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I enjoy organizing raw data into perfectly formatted tables." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I like keeping flawless tax records." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I prefer working in an environment with absolutely strict rules." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I am excellent at catching micro-errors in massive documents." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I enjoy tasks that require 100% adherence to standard operating procedure." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I like working as a strictly regulated financial auditor." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I am highly comfortable with monotonous, predictable, and quiet work." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I enjoy ensuring compliance with complex international shipping laws." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I like creating exhaustive filing systems for corporate use." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I would enjoy a career as a highly structured paralegal." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I enjoy categorizing massive physical archives." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I prefer jobs where creativity is not required." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I like reviewing databases for duplicate or erroneous entries." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I would enjoy working as an advanced data entry specialist." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I value efficiency, order, and predictability above all else." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I like processing endless stacks of identical forms." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I enjoy managing strictly controlled inventory warehouses." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I would like a career in municipal court administration." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I feel stressed when my coworkers skip required paperwork." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I believe that following the rules precisely prevents all workplace issues." },

    // ==========================================
    // MODULE C: PERSONALITY - BIG-5 (120 Questions)
    // ==========================================

    // --- Conscientiousness (24 Questions) ---
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I mentally review my tasks before sleep." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I rarely ever miss a loan or rent payment." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I prefer to finish assignments weeks in advance." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I set daily, weekly, and monthly targets for myself." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I am disturbed when someone moves items on my desk." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I keep a precise log of my vehicle's mileage." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I consistently arrive 15 minutes early for flights or trains." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I rigorously check my work for formatting errors." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I believe that organization is the key to mental peace." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I complete my most dreaded chores first thing in the morning." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I strictly adhere to corporate policies." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I hate feeling like I am unprepared for an exam." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I am highly focused when reading dense manuals." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I evaluate all minor details before starting a large task." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I promptly handle all boring administrative duties." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I follow instructions carefully, even if no one is watching." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I never leave my car or room disorganized." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I regularly review my progress toward long-term goals." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I follow my morning and evening routines without fail." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I am determined to meet exceptionally high standards." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I avoid acting impulsively when dealing with money." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I prefer working in environments with obvious hierarchy." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I take great pride in my perfectionism." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I am known for my intensely methodical approach." },

    // --- Extraversion (24 Questions) ---
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I typically enjoy being the absolute center of attention." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I enjoy hosting massive block parties." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I feel invigorated after interacting with a huge crowd." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I naturally take the microphone at events." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I easily make friends with people on airplanes." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I am highly dramatic and expressive when speaking." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I prefer extremely energetic, open-office settings." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I am quick to introduce myself to executives." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I love participating in loud group celebrations." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I often initiate weekend trips with large groups." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I confidently challenge the speaker during a lecture." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I dislike working alone in a closed room." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I thrive in loud, fast-paced trading floors or sales floors." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I am quick to suggest jumping on a stage or dance floor." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I have a very piercing and infectious laugh." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I enjoy speaking into a megaphone." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I maintain an enormous circle of casual friends." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I am generally described as deeply extroverted." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I naturally seek out the most crowded parts of a venue." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I find reading alone to be torturously boring." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I enjoy participating in fiery shouting matches or debates." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I prefer chaotic team sports over quiet gym workouts." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I tend to communicate constantly via texts and calls." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I consider myself the ultimate 'people person'." },

    // --- Agreeableness (24 Questions) ---
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I assume strangers have my best interests at heart." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I am entirely uncomfortable confronting a bad employee." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I regularly volunteer at homeless shelters." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I feel crushing guilt when I let my team down." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I am known for being overwhelmingly sweet." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I will do a coworker's job for them if they are stressed." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I prefer surrendering an argument to keep the peace." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I am highly sympathetic to criminals who had bad childhoods." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I make sure to write thank-you notes for every gift." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I try to instantly defuse any hostility in a room." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I rarely hold prejudice against people with different views." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I believe universal basic income is a moral necessity." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I have endless patience with complaining customers." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I am the designated therapist among my friend group." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I often put the financial needs of others before my own." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I deeply despise cruel or dark humor." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I am extremely passive when deciding where to eat." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I listen carefully without judging when someone confesses a flaw." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I believe that vengeance is completely useless." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I regularly buy lunch for my subordinates." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I rarely demand the spotlight or recognition." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I easily back down in debates over politics." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I am deeply moved to tears by sad documentaries." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I believe that kindness is the only thing that truly matters." },

    // --- Openness (24 Questions) ---
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I love exploring highly controversial new ideas." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I enjoy discussing the simulation theory of the universe." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I frequently read obscure academic journals." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I enjoy trying sensory deprivation tanks or meditation retreats." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I am highly imaginative when writing fiction." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I like deeply questioning my own cultural biases." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I prefer art house cinema over reality television." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I am open to exploring pagan or esoteric belief systems." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I enjoy writing bizarre or surrealist poetry." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I am deeply curious about evolutionary psychology." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I like listening to extremely niche foreign music." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I am fascinated by quantum physics and alternate dimensions." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I believe society is fundamentally flawed and needs redesigning." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I like inventing totally new words or slang." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I enjoy visiting ancient, mystical ruins." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I often think about the philosophy of consciousness." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I enjoy learning obscure coding languages." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I prefer to backpack through unfamiliar countries." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I am drawn to highly experimental, non-traditional art forms." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I appreciate the lore of massive fantasy universes." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I believe that traditional marriage might be an outdated concept." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I enjoy discussing anarcho-capitalism or pure socialism." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I am quick to embrace drastic dietary changes like veganism." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I feel stimulated by deeply confusing riddles." },

    // --- Emotional Stability (Neuroticism Reversed) (24 Questions) ---
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I rarely ever scream or yell in frustration." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I do not panic when my flight is suddenly canceled." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I wake up feeling at absolute peace with the world." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I am highly resilient when getting fired or laid off." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I never hold onto resentment after a breakup." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I can easily accept brutal honesty about my flaws." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I rarely feel anxious about public speaking." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I am able to stay fully focused during a medical emergency." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I rarely feel envious of celebrities or billionaires." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I am totally comfortable with the idea of moving to a new city." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I do not worry about aging or getting older." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I view intense hardship as an exciting trial to overcome." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I maintain a stoic, unflappable temper at work." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I am not easily rattled by horror movies or jump scares." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I can easily laugh off a coffee spill on my new shirt." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I don't dwell on what I could have done differently in high school." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I feel incredibly secure in my physical capabilities." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I rarely feel 'FOMO' (Fear Of Missing Out)." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I do not rely on romantic partners to feel complete." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I can easily fall back asleep if woken in the night." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I view economic recessions as cyclical and not terrifying." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I completely avoid catastrophizing when I feel mildly sick." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I am completely at peace with my current social status." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I can discuss death and mortality without anxiety." }
];