const questionsPart3 = [
    // ==========================================
    // MODULE A: APTITUDE & COGNITIVE ABILITY (60 Questions)
    // ==========================================

    // --- Numerical Aptitude (20 Questions) ---
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "What is 40% of 500?", options: [{text:"150", val:0}, {text:"200", val:5}, {text:"250", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "If 7a = 56, what is the value of a?", options: [{text:"7", val:0}, {text:"8", val:5}, {text:"9", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "A train covers 300 miles in 5 hours. Average speed?", options: [{text:"50 mph", val:0}, {text:"60 mph", val:5}, {text:"70 mph", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "What is the square root of 225?", options: [{text:"15", val:5}, {text:"25", val:0}, {text:"35", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "A $50 shirt is on sale for 20% off. What is the new price?", options: [{text:"$45", val:0}, {text:"$40", val:5}, {text:"$30", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "Solve: 10 + 2 × 5", options: [{text:"20", val:5}, {text:"60", val:0}, {text:"17", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "What is 2/5 as a percentage?", options: [{text:"20%", val:0}, {text:"40%", val:5}, {text:"50%", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "If 3 painters paint a house in 6 days, how long will it take 9 painters?", options: [{text:"2 days", val:5}, {text:"3 days", val:0}, {text:"4 days", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "Area of a rectangle with length 12 and width 4?", options: [{text:"48", val:5}, {text:"36", val:0}, {text:"24", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "A movie starts at 7:45 PM and ends at 9:20 PM. How long is it?", options: [{text:"1h 35m", val:5}, {text:"1h 45m", val:0}, {text:"1h 25m", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "Solve: (20 / 4) + 7", options: [{text:"12", val:5}, {text:"11", val:0}, {text:"13", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "What is the next prime number after 23?", options: [{text:"25", val:0}, {text:"27", val:0}, {text:"29", val:5}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "If 1 gallon = 3.78 liters, how many liters in 4 gallons?", options: [{text:"12.5", val:0}, {text:"15.12", val:5}, {text:"16.0", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "What is 6 cubed (6³)?", options: [{text:"36", val:0}, {text:"216", val:5}, {text:"126", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "A $200 bill split equally among 5 people is how much per person?", options: [{text:"$30", val:0}, {text:"$40", val:5}, {text:"$50", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "Solve for x: 4x - 8 = 16", options: [{text:"4", val:0}, {text:"6", val:5}, {text:"8", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "A cake is cut into 10 slices. You eat 4. What percentage is left?", options: [{text:"40%", val:0}, {text:"60%", val:5}, {text:"50%", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "Least Common Multiple (LCM) of 3 and 8?", options: [{text:"24", val:5}, {text:"16", val:0}, {text:"12", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "Probability of drawing a heart from a standard deck of cards?", options: [{text:"1/2", val:0}, {text:"1/4", val:5}, {text:"1/13", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "Convert 0.8 to a fraction.", options: [{text:"4/5", val:5}, {text:"3/4", val:0}, {text:"8/100", val:0}] },

    // --- Logical Reasoning (20 Questions) ---
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Sequence: 3, 9, 27, 81, __?", options: [{text:"162", val:0}, {text:"243", val:5}, {text:"300", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Glove is to Hand as Shoe is to...?", options: [{text:"Foot", val:5}, {text:"Leg", val:0}, {text:"Sock", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "All X are Y. No Y are Z. Can an X be a Z?", options: [{text:"Yes", val:0}, {text:"No", val:5}, {text:"Cannot be determined", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Odd one out: Desk, Chair, Table, Apple?", options: [{text:"Apple", val:5}, {text:"Desk", val:0}, {text:"Chair", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "If P > Q and R > P, who is the largest?", options: [{text:"P", val:0}, {text:"Q", val:0}, {text:"R", val:5}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Sequence: C, F, I, L, __?", options: [{text:"O", val:5}, {text:"M", val:0}, {text:"N", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Author is to Book as Architect is to...?", options: [{text:"Building", val:5}, {text:"Blueprint", val:0}, {text:"Cement", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "If APPLE is 5, BANANA is 6, what is CHERRY?", options: [{text:"5", val:0}, {text:"6", val:5}, {text:"7", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "My father's father's only son is my...?", options: [{text:"Uncle", val:0}, {text:"Grandfather", val:0}, {text:"Father", val:5}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Sequence: 100, 50, 25, 12.5, __?", options: [{text:"6.25", val:5}, {text:"6.0", val:0}, {text:"10", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Some squares are blue. All blue things are heavy. Are some squares heavy?", options: [{text:"Yes", val:5}, {text:"No", val:0}, {text:"Cannot be determined", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Scissors is to Cutting as Glue is to...?", options: [{text:"Paper", val:0}, {text:"Sticking", val:5}, {text:"Bottle", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Odd one out: Paris, London, Rome, Africa.", options: [{text:"Africa", val:5}, {text:"Paris", val:0}, {text:"Rome", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Walk 20m North, turn around, walk 10m South. Direction facing?", options: [{text:"North", val:0}, {text:"South", val:5}, {text:"East", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Sequence: 1, 3, 6, 10, 15, __?", options: [{text:"20", val:0}, {text:"21", val:5}, {text:"22", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Microphone is to Speaking as Camera is to...?", options: [{text:"Picture", val:5}, {text:"Lens", val:0}, {text:"Flash", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "If the 1st of the month is Monday, what day is the 15th?", options: [{text:"Monday", val:5}, {text:"Sunday", val:0}, {text:"Tuesday", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "All ice is cold. Snow is cold. Is snow ice?", options: [{text:"Yes", val:0}, {text:"No", val:0}, {text:"Cannot be determined", val:5}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Odd one out: 2, 4, 6, 9, 10, 12?", options: [{text:"9", val:5}, {text:"6", val:0}, {text:"10", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "If Z=26, Y=25, X=24, then C=?", options: [{text:"1", val:0}, {text:"2", val:0}, {text:"3", val:5}] },

    // --- Verbal Reasoning (20 Questions) ---
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Synonym for 'AUSTERE':", options: [{text:"Severe", val:5}, {text:"Joyful", val:0}, {text:"Complex", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Antonym for 'IGNITE':", options: [{text:"Extinguish", val:5}, {text:"Burn", val:0}, {text:"Start", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Meaning of 'let the cat out of the bag':", options: [{text:"Buy a pet", val:0}, {text:"Reveal a secret", val:5}, {text:"Make a mistake", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Wheel is to Car as Blade is to...?", options: [{text:"Knife", val:5}, {text:"Handle", val:0}, {text:"Steel", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Correct spelling:", options: [{text:"Embarass", val:0}, {text:"Embarrass", val:5}, {text:"Embaras", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "A person who studies weather is a...?", options: [{text:"Meteorologist", val:5}, {text:"Geologist", val:0}, {text:"Astronomer", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Synonym for 'TACITURN':", options: [{text:"Talkative", val:0}, {text:"Reserved", val:5}, {text:"Loud", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Plural of 'Cactus':", options: [{text:"Cactuses", val:0}, {text:"Cacti", val:5}, {text:"Cactees", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "A 'Dermatologist' treats the...?", options: [{text:"Skin", val:5}, {text:"Bones", val:0}, {text:"Heart", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Antonym for 'HARMONY':", options: [{text:"Peace", val:0}, {text:"Discord", val:5}, {text:"Melody", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Odd word out: Whisper, Mumble, Shout, Mutter.", options: [{text:"Shout", val:5}, {text:"Mumble", val:0}, {text:"Whisper", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Meaning of 'Gullible':", options: [{text:"Easily tricked", val:5}, {text:"Very smart", val:0}, {text:"Angry", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Which is a pronoun? (He, House, Quickly)", options: [{text:"He", val:5}, {text:"House", val:0}, {text:"Quickly", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "I have ____ my homework already.", options: [{text:"did", val:0}, {text:"done", val:5}, {text:"do", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Synonym for 'LUDICROUS':", options: [{text:"Absurd", val:5}, {text:"Logical", val:0}, {text:"Serious", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "A group of wolves is called a...?", options: [{text:"Pack", val:5}, {text:"Flock", val:0}, {text:"Herd", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Antonym for 'OPTIMISTIC':", options: [{text:"Pessimistic", val:5}, {text:"Happy", val:0}, {text:"Hopeful", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Prefix 'Pre-' means:", options: [{text:"After", val:0}, {text:"Before", val:5}, {text:"During", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "If something is 'Lethal', it is:", options: [{text:"Safe", val:0}, {text:"Deadly", val:5}, {text:"Soft", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Meaning of 'Nocturnal':", options: [{text:"Active at night", val:5}, {text:"Sleeping always", val:0}, {text:"Active by day", val:0}] },

    // ==========================================
    // MODULE B: INTERESTS - RIASEC (120 Questions)
    // ==========================================

    // --- Realistic (20 Questions) ---
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I enjoy assembling parts to build a functioning machine." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I would rather work in a warehouse than a corporate office." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I like jobs where I have to be on my feet all day." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I find it relaxing to do maintenance on my bicycle or car." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I enjoy using precision tools like micrometers or lasers." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I would like a career in plumbing, welding, or electrical work." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I like working with animals, such as in veterinary care or farming." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I enjoy learning survival tactics for the wilderness." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I am comfortable working with hazardous materials safely." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I prefer practical tasks that have an immediate physical result." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I enjoy watching shows about how factories make products." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I would like to drive a commercial vehicle for a living." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I like building structures out of brick or concrete." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I enjoy repairing torn clothing or fixing broken zippers." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I prefer sports that require physical endurance and toughness." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I like troubleshooting computer hardware when it fails." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I would enjoy a career as a firefighter or emergency responder." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I like understanding the layout of architectural floor plans." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I feel a sense of accomplishment after exhausting physical work." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I prefer working with tangible objects rather than abstract concepts." },

    // --- Investigative (20 Questions) ---
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I enjoy reading about quantum physics or advanced chemistry." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I like finding software bugs and writing code to fix them." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I am intrigued by how the economy fluctuates." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I prefer asking questions and gathering data before acting." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I enjoy participating in academic debates." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I like testing different hypotheses to see which is correct." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I want to publish my own findings in a scientific journal." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I enjoy reading non-fiction biographies of great inventors." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I like predicting future trends based on historical data." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I would enjoy working as a meteorologist tracking storms." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I like dissecting a problem until I find the root cause." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I am fascinated by marine biology and oceanography." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I enjoy using complex software to visualize data." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I am skeptical of information that lacks statistical backing." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I would like to analyze crime scenes as a forensic expert." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I enjoy learning about anatomy and human physiology." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I like solving advanced Sudoku or logic grid puzzles." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I would rather watch an educational lecture than a sitcom." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I enjoy studying ancient languages or archaeology." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I believe that rational thought is superior to emotional intuition." },

    // --- Artistic (20 Questions) ---
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I enjoy sketching cartoons or creating digital illustrations." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I like editing videos and adding special effects." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I am passionate about theater and dramatic performance." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I prefer having a workspace that is visually inspiring." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I enjoy writing opinion pieces or journalistic articles." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I like brainstorming brand names and marketing slogans." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I am interested in learning classical or contemporary dance." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I prefer open-ended assignments over highly structured ones." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I enjoy analyzing the themes and symbolism in movies." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I would like a career as a professional author or novelist." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I find joy in discovering new independent music artists." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I like experimenting with new recipes and culinary presentations." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I am drawn to careers in animation and 3D modeling." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I believe that culture and art drive human progress." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I enjoy restoring old furniture and giving it a new look." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I would rather visit a poetry slam than a tech convention." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I like writing scripts for short films or commercials." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I enjoy learning about the history of fashion and trends." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I like curating aesthetic feeds on social media." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I constantly seek to evoke emotion through my work." },

    // --- Social (20 Questions) ---
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I enjoy leading youth groups or summer camps." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I like providing emotional support to grieving individuals." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I want a career in special education or disability services." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I enjoy organizing fundraisers for local charities." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I am passionate about improving community mental health." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I like welcoming new members to a club or organization." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I prefer to address interpersonal issues directly and kindly." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I enjoy working as a peer mediator in schools or offices." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I would like to work in international humanitarian aid." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I like advocating for the rights of marginalized groups." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I find great joy in seeing someone overcome a personal struggle." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I would enjoy a career in marriage or family counseling." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I am motivated by creating an inclusive environment." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I enjoy teaching life skills to young adults." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I like assisting people with their spiritual or religious growth." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I prefer working in environments focused on rehabilitation." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I enjoy helping immigrants or refugees settle into a new country." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I am patient when caring for those with severe illnesses." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I would like to work as a customer success representative." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I feel that empathy is more important than efficiency." },

    // --- Enterprising (20 Questions) ---
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I enjoy securing sponsorships for events or clubs." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I like developing strategies to outsmart business competitors." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I am driven by the idea of scaling a small business into an empire." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I enjoy trading cryptocurrency or flipping items for profit." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I like giving motivational speeches to inspire a team." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I prefer environments where performance directly dictates my salary." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I am comfortable asserting my authority when I am in charge." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I enjoy mingling at high-profile corporate galas." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I would like to be a hotel manager or hospitality executive." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I like acting as the official spokesperson for a brand." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I enjoy overseeing large budgets and allocating funds." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I am confident in my ability to close a difficult sale." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I would enjoy a career as an entrepreneur or founder." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I am motivated by winning awards and industry recognition." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I enjoy identifying market gaps and launching new products." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I like being the person who hires and fires employees." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I enjoy managing political campaigns or public lobbying." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I would like to work as a travel agent or tour operator." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I am skilled at turning a 'no' into a 'yes'." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I believe that taking calculated risks is essential for success." },

    // --- Conventional (20 Questions) ---
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I enjoy auditing financial records for discrepancies." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I like maintaining highly accurate inventory logs." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I prefer working in a quiet, structured cubicle environment." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I am excellent at formatting documents according to strict guidelines." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I enjoy processing payroll and managing employee benefits." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I like working as a paralegal researching legal precedents." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I am highly comfortable with daily, repetitive administrative routines." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I enjoy ensuring a company complies with all state laws." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I like writing clear, step-by-step user manuals." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I would enjoy a career in quality control or safety inspection." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I enjoy sorting physical mail and managing office correspondence." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I prefer knowing my exact responsibilities before a project begins." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I like categorizing data into complex hierarchical structures." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I would enjoy working as a medical records technician." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I value punctuality and exactness over creativity." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I like processing invoices and tracking expenses." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I enjoy keeping track of meeting minutes and agendas." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I would like a career in government bureaucracy or administration." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I feel stressed when plans change abruptly." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I believe that following established protocols prevents disaster." },


    // ==========================================
    // MODULE C: PERSONALITY - BIG-5 (120 Questions)
    // ==========================================

    // --- Conscientiousness (24 Questions) ---
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I always review my calendar the night before." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I rarely misplace important documents." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I prefer to tackle the hardest tasks first." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I set weekly goals for my personal development." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I am disturbed by disorganized shared spaces." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I keep a strict budget and track my spending." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I arrive at least 10 minutes early to meetings." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I proofread all of my emails before hitting send." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I believe discipline is the key to all success." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I honor my commitments even when I am tired." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I keep my promises to myself regarding diet and exercise." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I hate rushing at the last minute to finish a project." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I am highly focused when I am working." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I weigh all pros and cons before making a purchase." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I return borrowed items promptly and in good condition." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I always follow a recipe exactly as it is written." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I never skip steps when assembling something." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I make sure my car is regularly serviced." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I follow safety guidelines without exception." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I am relentless when trying to solve a problem." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I avoid making decisions when I am emotional." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I prefer predictability over unexpected surprises." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I take pride in my dependability." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I am the one people turn to when something must get done." },

    // --- Extraversion (24 Questions) ---
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I usually take the lead in group assignments." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I enjoy being the host of social gatherings." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I feel drained if I spend too much time alone." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I project my voice so everyone in the room can hear me." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I easily strike up conversations in waiting rooms." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I use a lot of facial expressions when I talk." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I prefer open-plan offices where I can chat with coworkers." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I am usually the first to introduce myself to newcomers." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I love participating in group games and sports." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I often throw parties just to see my friends." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I assert my opinions boldly in discussions." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I hate eating alone at a restaurant." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I thrive in busy, noisy environments." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I am quick to suggest plans for the weekend." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I laugh loudly and frequently." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I enjoy speaking on stage or in front of cameras." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I maintain a massive list of contacts." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I am generally described as an 'open book'." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I naturally gravitate toward the center of the crowd." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I find quiet retreats boring." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I enjoy intense, competitive debates." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I prefer working out in a crowded gym." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I share my thoughts before fully processing them." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I consider myself a highly energetic person." },

    // --- Agreeableness (24 Questions) ---
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I assume people are telling the truth until proven otherwise." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I am uncomfortable giving people negative feedback." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I regularly volunteer for causes I care about." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I feel guilty when I have to say 'no' to a request." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I am known for being gentle and soft-spoken." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I will cover a shift for a coworker in an emergency." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I prefer group harmony over getting my own way." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I am highly empathetic toward people suffering from illness." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I make sure to acknowledge everyone's contributions." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I am quick to take the blame to resolve a tense situation." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I rarely judge people for their past mistakes." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I believe society should prioritize caring for the vulnerable." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I have a lot of patience with difficult children." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I am the person my friends call when they need to cry." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I often sacrifice my free time to help my family." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I dislike humor that involves teasing or mocking." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I am highly accommodating in group travel plans." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I am an active listener when someone is venting." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I believe holding grudges is toxic to the soul." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I regularly leave generous tips." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I rarely ask for the best seat or the biggest portion." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I easily yield in arguments just to end them." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I am deeply moved by stories of heroism and sacrifice." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I believe that compassion is more important than intelligence." },

    // --- Openness (24 Questions) ---
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I love exploring ancient ruins and historical sites." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I enjoy discussing the origins of the universe." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I frequently read non-fiction about diverse topics." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I enjoy trying experimental or fusion cuisine." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I am highly creative and constantly generating new ideas." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I like questioning authority to understand their motives." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I prefer independent films over mainstream cinema." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I am open to changing my worldview if presented with new evidence." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I enjoy writing short stories or engaging in world-building." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I am deeply curious about the inner workings of the human mind." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I like listening to obscure or niche music genres." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I am fascinated by indigenous cultures and forgotten histories." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I believe that societal norms should constantly evolve." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I like finding unconventional uses for common objects." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I enjoy hiking in remote, unexplored natural areas." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I often think about the ethical implications of artificial intelligence." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I enjoy learning how to code or use new digital platforms." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I prefer taking spontaneous detours while traveling." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I am drawn to abstract art that requires interpretation." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I appreciate beautiful typography and layout design." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I believe morality is subjective and depends on culture." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I enjoy discussing macroeconomic theories." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I am quick to embrace radical lifestyle changes." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I feel stagnated if I do not learn something new every week." },

    // --- Emotional Stability (Neuroticism Reversed) (24 Questions) ---
    // Note: Likert 1-5. High score = High Stability
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I rarely raise my voice in anger." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I do not panic when I lose something important." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I wake up feeling refreshed and ready for the day." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I am highly resilient when facing personal rejection." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I don't hold onto frustration after an argument." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I can easily accept failure without feeling inadequate." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I rarely feel claustrophobic or trapped." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I am able to maintain focus during chaotic situations." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I rarely envy the success of my peers." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I am comfortable with sudden changes in plans." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I do not constantly worry about financial ruin." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I view critical feedback as an opportunity, not an attack." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I maintain a calm demeanor even when I am upset." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I am not easily disturbed by loud noises or sudden events." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I can easily brush off rude drivers or minor inconveniences." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I don't lose sleep replaying embarrassing memories." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I feel secure in my current career trajectory." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I rarely feel abandoned by my friends." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I do not require external validation to feel good." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I can practice mindfulness without distraction." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I view breakups or losses as natural parts of life." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I avoid assuming the worst when someone doesn't reply quickly." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I am generally very content with my physical appearance." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I can read about tragedies without suffering lingering sadness." }
];