const questionsPart4 = [
    // ==========================================
    // MODULE A: APTITUDE & COGNITIVE ABILITY (60 Questions)
    // ==========================================

    // --- Numerical Aptitude (20 Questions) ---
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "If 8b = 72, what is the value of b?", options: [{text:"8", val:0}, {text:"9", val:5}, {text:"10", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "A marathon is 26.2 miles. If you run half, how far did you run?", options: [{text:"13.1 miles", val:5}, {text:"13.5 miles", val:0}, {text:"12.8 miles", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "What is 75% of 400?", options: [{text:"250", val:0}, {text:"300", val:5}, {text:"350", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "Solve: (15 - 3) × 2", options: [{text:"24", val:5}, {text:"20", val:0}, {text:"18", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "What is 4/5 as a decimal?", options: [{text:"0.80", val:5}, {text:"0.75", val:0}, {text:"0.85", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "If 5 bakers can paint a room in 4 hours, how long for 10 bakers?", options: [{text:"2 hours", val:5}, {text:"3 hours", val:0}, {text:"4 hours", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "Area of a circle with radius 3? (Use π ≈ 3.14)", options: [{text:"28.26", val:5}, {text:"18.84", val:0}, {text:"9.42", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "A flight departs at 8:15 AM and arrives at 11:45 AM. Duration?", options: [{text:"3h 30m", val:5}, {text:"3h 15m", val:0}, {text:"4h 30m", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "What is the square root of 400?", options: [{text:"20", val:5}, {text:"40", val:0}, {text:"10", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "If a $80 jacket is 25% off, what is the new price?", options: [{text:"$60", val:5}, {text:"$65", val:0}, {text:"$70", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "Next prime number after 31?", options: [{text:"37", val:5}, {text:"33", val:0}, {text:"35", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "If 1 mile = 1.6 km, how many km in 5 miles?", options: [{text:"8.0", val:5}, {text:"7.5", val:0}, {text:"8.5", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "What is 7 cubed (7³)?", options: [{text:"343", val:5}, {text:"243", val:0}, {text:"443", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "A $150 dinner divided by 6 people is?", options: [{text:"$25", val:5}, {text:"$30", val:0}, {text:"$20", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "Solve for c: 5c + 10 = 35", options: [{text:"5", val:5}, {text:"6", val:0}, {text:"7", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "A pizza has 12 slices. You eat 3. Fraction eaten?", options: [{text:"1/4", val:5}, {text:"1/3", val:0}, {text:"1/5", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "Least Common Multiple (LCM) of 5 and 7?", options: [{text:"35", val:5}, {text:"25", val:0}, {text:"40", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "Probability of rolling a 1 or 2 on a 6-sided die?", options: [{text:"1/3", val:5}, {text:"1/6", val:0}, {text:"1/2", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "Convert 0.6 to a fraction.", options: [{text:"3/5", val:5}, {text:"2/5", val:0}, {text:"4/5", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "numerical", text: "Solve: (30 / 6) + (4 × 3)", options: [{text:"17", val:5}, {text:"15", val:0}, {text:"19", val:0}] },

    // --- Logical Reasoning (20 Questions) ---
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Sequence: 2, 6, 18, 54, __?", options: [{text:"162", val:5}, {text:"108", val:0}, {text:"216", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Cloud is to Rain as Sun is to...?", options: [{text:"Light", val:5}, {text:"Moon", val:0}, {text:"Sky", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "No trees are cars. Some cars are fast. Are some trees fast?", options: [{text:"Cannot be determined", val:5}, {text:"Yes", val:0}, {text:"No", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Odd one out: Piano, Guitar, Violin, Drum?", options: [{text:"Drum", val:5}, {text:"Piano", val:0}, {text:"Guitar", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "If A > B and C > A, who is the smallest?", options: [{text:"B", val:5}, {text:"A", val:0}, {text:"C", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Sequence: E, H, K, N, __?", options: [{text:"Q", val:5}, {text:"P", val:0}, {text:"O", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Baker is to Bread as Sculptor is to...?", options: [{text:"Statue", val:5}, {text:"Clay", val:0}, {text:"Museum", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "If DOG is 3, ELEPHANT is 8, what is LION?", options: [{text:"4", val:5}, {text:"5", val:0}, {text:"6", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "My mother's brother's only sister is my...?", options: [{text:"Mother", val:5}, {text:"Aunt", val:0}, {text:"Grandmother", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Sequence: 200, 100, 50, 25, __?", options: [{text:"12.5", val:5}, {text:"10", val:0}, {text:"15", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "All birds lay eggs. A bat is a bird. Does a bat lay eggs? (Based on premise)", options: [{text:"Yes", val:5}, {text:"No", val:0}, {text:"Cannot be determined", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Brush is to Painting as Wrench is to...?", options: [{text:"Fixing", val:5}, {text:"Tool", val:0}, {text:"Mechanic", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Odd one out: Tokyo, Madrid, Berlin, Brazil.", options: [{text:"Africa", val:5}, {text:"Tokyo", val:0}, {text:"Madrid", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Walk 15m West, turn left, walk 10m. Direction facing?", options: [{text:"South", val:5}, {text:"North", val:0}, {text:"East", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Sequence: 1, 4, 9, 16, 25, __?", options: [{text:"36", val:5}, {text:"30", val:0}, {text:"49", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Key is to Lock as Password is to...?", options: [{text:"Account", val:5}, {text:"Computer", val:0}, {text:"Typing", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "If today is Wednesday, what is the day 10 days from now?", options: [{text:"Saturday", val:5}, {text:"Sunday", val:0}, {text:"Friday", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "All fish swim. Some swimmers are fast. Are some fish fast?", options: [{text:"Cannot be determined", val:5}, {text:"Yes", val:0}, {text:"No", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "Odd one out: 3, 5, 7, 9, 11, 13?", options: [{text:"9", val:5}, {text:"5", val:0}, {text:"7", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "logical", text: "If M=13, N=14, O=15, then P=?", options: [{text:"16", val:5}, {text:"17", val:0}, {text:"15", val:0}] },

    // --- Verbal Reasoning (20 Questions) ---
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Synonym for 'OBSOLETE':", options: [{text:"Outdated", val:5}, {text:"Current", val:0}, {text:"Useful", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Antonym for 'ABUNDANT':", options: [{text:"Scarce", val:5}, {text:"Plentiful", val:0}, {text:"Heavy", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Meaning of 'bite the bullet':", options: [{text:"Face a difficult situation", val:5}, {text:"Eat quickly", val:0}, {text:"Be brave", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Feather is to Bird as Scale is to...?", options: [{text:"Fish", val:5}, {text:"Lizard", val:0}, {text:"Weight", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Correct spelling:", options: [{text:"Definately", val:0}, {text:"Definitely", val:5}, {text:"Definitly", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "A person who studies space is an...?", options: [{text:"Astronomer", val:5}, {text:"Astrologer", val:0}, {text:"Astronaut", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Synonym for 'CANDID':", options: [{text:"Honest", val:5}, {text:"Secretive", val:0}, {text:"Quiet", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Plural of 'Goose':", options: [{text:"Gooses", val:0}, {text:"Geese", val:5}, {text:"Geeses", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "An 'Orthodontist' treats the...?", options: [{text:"Teeth", val:5}, {text:"Bones", val:0}, {text:"Eyes", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Antonym for 'COMPLEX':", options: [{text:"Simple", val:5}, {text:"Hard", val:0}, {text:"Easy", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Odd word out: Gaze, Stare, Glance, Bling.", options: [{text:"Bling", val:5}, {text:"Gaze", val:0}, {text:"Stare", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Meaning of 'Amicable':", options: [{text:"Friendly", val:5}, {text:"Hostile", val:0}, {text:"Quiet", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Which is a conjunction? (And, Red, Slowly)", options: [{text:"And", val:5}, {text:"Red", val:0}, {text:"Slowly", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "They ____ going to the park later.", options: [{text:"is", val:0}, {text:"are", val:5}, {text:"was", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Synonym for 'ELUSIVE':", options: [{text:"Hard to catch", val:5}, {text:"Easy to find", val:0}, {text:"Common", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "A group of crows is called a...?", options: [{text:"Murder", val:5}, {text:"Flock", val:0}, {text:"Pack", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Antonym for 'DILIGENT':", options: [{text:"Lazy", val:5}, {text:"Hardworking", val:0}, {text:"Careful", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Prefix 'Post-' means:", options: [{text:"After", val:5}, {text:"Before", val:0}, {text:"Under", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "If something is 'Vague', it is:", options: [{text:"Unclear", val:5}, {text:"Clear", val:0}, {text:"Loud", val:0}] },
    { module: "Module A: Aptitude", type: "mcq", traitType: "aptitude", trait: "verbal", text: "Meaning of 'Biennial':", options: [{text:"Every two years", val:5}, {text:"Twice a year", val:0}, {text:"Once a year", val:0}] },

    // ==========================================
    // MODULE B: INTERESTS - RIASEC (120 Questions)
    // ==========================================

    // --- Realistic (20 Questions) ---
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I prefer practical activities over conceptual thinking." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I enjoy learning how to fix household plumbing." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I like jobs that involve physical coordination and agility." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I would rather lay bricks than design the building's facade." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I enjoy operating machinery like forklifts or cranes." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I like working with mechanical parts and gears." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I am comfortable working in environments with dust or dirt." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I enjoy agricultural work, like operating tractors." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I would like to be a mechanic specializing in heavy vehicles." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I like using tools like wrenches, pliers, and hammers." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I prefer hobbies that result in a tangible, usable object." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I enjoy resolving issues with HVAC systems." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I like mapping out physical spaces for construction." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I would enjoy a career in forestry or logging." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I like understanding the practical application of physical laws." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I find long meetings and discussions draining." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I prefer a hands-on approach to learning." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I enjoy maintaining and sharpening my own tools." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I am interested in careers involving physical security or guarding." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "realistic", text: "I like following a physical process from start to finish." },

    // --- Investigative (20 Questions) ---
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I enjoy reading about genetics and DNA." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I like analyzing system logs to find software errors." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I am intrigued by sociological trends and data." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I prefer to investigate all possibilities before concluding." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I enjoy writing literature reviews for academic topics." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I like designing experiments to test variables." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I want to present findings at a scientific conference." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I enjoy reading detailed reports on historical discoveries." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I like using statistical models to forecast outcomes." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I would enjoy working as an epidemiologist." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I like tracing complex issues back to their origin." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I am fascinated by neuroscience and brain function." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I enjoy writing queries to extract data from databases." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I am hesitant to accept facts without reviewing the methodology." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I would like to work as a data scientist." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I enjoy understanding the chemical composition of materials." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I like working through complex mathematical proofs." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I would rather attend a seminar than a social mixer." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I enjoy studying linguistics and language evolution." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "investigative", text: "I believe that empirical data is the best way to understand the world." },

    // --- Artistic (20 Questions) ---
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I enjoy creating storyboards for visual projects." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I like mixing audio tracks or sound design." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I am passionate about set design for theater." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I prefer workspaces that allow for personal expression." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I enjoy writing compelling copy for advertisements." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I like conceptualizing new visual identities for brands." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I am interested in improvisational performance." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I prefer projects that have no definitive 'right' answer." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I enjoy interpreting the meaning behind abstract paintings." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I would like a career as a freelance illustrator." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I find joy in discovering unique architectural styles." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I like designing unique patterns for textiles." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I am drawn to careers in industrial design." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I believe that aesthetic value is as important as functionality." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I enjoy upcycling vintage clothing." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I would rather visit an independent film festival than a theme park." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I like developing character arcs for stories." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I enjoy learning about art history movements." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I like arranging spaces to be visually pleasing." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "artistic", text: "I constantly seek inspiration from the world around me." },

    // --- Social (20 Questions) ---
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I enjoy facilitating workshops for community development." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I like providing crisis intervention support." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I want a career in early childhood education." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I enjoy coordinating volunteer schedules." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I am passionate about advocating for public health initiatives." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I like helping new students adjust to school." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I prefer roles that require high emotional intelligence." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I enjoy working as an academic advisor." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I would like to work in global health aid." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I like championing causes for underprivileged communities." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I find great joy in mentoring at-risk youth." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I would enjoy a career in occupational therapy." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I am motivated by fostering teamwork and unity." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I enjoy developing training programs for adults." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I like guiding people through difficult life transitions." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I prefer working in settings focused on community support." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I enjoy helping diverse groups find common ground." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I am patient when assisting individuals with learning disabilities." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I would like to work as a human resources generalist." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "social", text: "I feel that supporting others is the most rewarding work." },

    // --- Enterprising (20 Questions) ---
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I enjoy negotiating vendor contracts." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I like creating business plans for startups." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I am driven by achieving high sales quotas." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I enjoy analyzing real estate markets for investment." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I like rallying a team behind a new corporate vision." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I prefer roles where I can earn commissions or bonuses." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I am comfortable making executive decisions under pressure." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I enjoy attending industry networking mixers." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I would like to be a regional manager for a retail chain." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I like representing my company at trade shows." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I enjoy forecasting quarterly revenues." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I am confident in my ability to pitch products to executives." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I would enjoy a career as a venture capitalist." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I am motivated by rapid career progression." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I enjoy studying consumer behavior to boost sales." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I like managing the hiring process for executive roles." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I enjoy organizing corporate fundraising events." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I would like to work as a business development manager." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I am skilled at turning prospects into loyal clients." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "enterprising", text: "I believe that bold strategies are necessary for growth." },

    // --- Conventional (20 Questions) ---
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I enjoy reconciling bank statements." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I like maintaining comprehensive equipment logs." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I prefer working in an environment with established hierarchy." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I am excellent at adhering to corporate style guides." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I enjoy processing insurance claims." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I like working as a compliance officer." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I am highly comfortable with standardized testing procedures." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I enjoy ensuring all documentation is legally sound." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I like creating flowcharts for standard processes." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I would enjoy a career as an actuary." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I enjoy managing digital archives." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I prefer clear rubrics over subjective evaluations." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I like indexing library materials." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I would enjoy working as a tax examiner." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I value accuracy and consistency in reporting." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I like managing purchasing orders." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I enjoy keeping precise meeting records." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I would like a career in civil service administration." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I feel stressed when procedures are ignored." },
    { module: "Module B: Interests", type: "likert", traitType: "riasec", trait: "conventional", text: "I believe that strict record-keeping prevents errors." },

    // ==========================================
    // MODULE C: PERSONALITY - BIG-5 (120 Questions)
    // ==========================================

    // --- Conscientiousness (24 Questions) ---
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I plan my outfits for the week." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I rarely forget to return borrowed money." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I prefer to finish assignments days before they are due." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I set monthly financial goals." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I am disturbed when files are out of alphabetical order." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I keep a detailed log of my car's maintenance." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I always RSVP to events promptly." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I double-check calculations before submitting them." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I believe consistency is more important than bursts of effort." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I honor my obligations even when I want to quit." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I keep my workspace completely clear of clutter." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I hate leaving tasks half-finished." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I am highly disciplined in my daily habits." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I evaluate all options before signing a contract." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I return calls and texts as soon as possible." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I strictly follow software installation guides." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I never bypass security protocols." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I regularly update my passwords." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I follow dietary plans without cheating." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I am relentless in verifying facts." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I avoid making hasty financial investments." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I prefer structured courses over independent study." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I take pride in my punctuality." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "conscientiousness", text: "I am the one who always remembers birthdays." },

    // --- Extraversion (24 Questions) ---
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I usually volunteer to be the group spokesperson." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I enjoy organizing large family reunions." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I feel lonely if I work from home too often." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I naturally speak louder when I am excited." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I easily make small talk with cashiers." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I am animated when recounting a story." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I prefer team-building retreats over solitary work." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I am quick to greet people at networking events." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I love participating in group fitness challenges." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I often suggest after-work drinks." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I defend my ideas vigorously in meetings." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I hate commuting alone." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I thrive in open-office environments." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I am quick to propose group vacations." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I am known for my boisterous laugh." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I enjoy acting as the MC for events." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I have connections in many different industries." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I am generally described as highly outgoing." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I naturally gravitate toward the busiest part of the room." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I find solitary hobbies unfulfilling." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I enjoy participating in panel discussions." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I prefer playing team sports over individual ones." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I verbally process my ideas." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "extraversion", text: "I consider myself a 'people person'." },

    // --- Agreeableness (24 Questions) ---
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I assume people's mistakes are accidental." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I am uncomfortable giving harsh performance reviews." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I regularly donate to crowd-funding campaigns." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I feel guilty when I have to cancel plans." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I am known for being a peacemaker." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I will take on extra work to help a stressed colleague." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I prefer building consensus over winning an argument." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I am highly empathetic toward those facing hardships." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I make sure to praise people for their efforts." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I am quick to de-escalate tension." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I rarely judge people for their lifestyle choices." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I believe society should prioritize social safety nets." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I have a lot of patience with slow learners." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I am the person my friends call when they need advice." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I often sacrifice my own comfort for my friends." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I dislike cynical or biting comedy." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I am highly accommodating when dining out with groups." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I am an active listener when someone is expressing grief." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I believe resentment only hurts the person holding it." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I regularly express gratitude to my peers." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I rarely demand to be first in line." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I easily back down in trivial disputes." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I am deeply moved by acts of kindness." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "agreeableness", text: "I believe that empathy is a crucial leadership skill." },

    // --- Openness (24 Questions) ---
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I love exploring obscure museums." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I enjoy discussing ethical dilemmas." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I frequently read articles about scientific breakthroughs." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I enjoy trying experimental brewing methods." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I am highly creative when cooking without a recipe." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I like questioning societal norms." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I prefer documentaries over reality TV." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I am open to exploring different spiritual practices." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I enjoy writing reflective journal entries." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I am deeply curious about sociology." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I like listening to instrumental or ambient music." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I am fascinated by mythological stories." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I believe that art should challenge our perspectives." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I like finding new applications for old technologies." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I enjoy visiting botanical gardens." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I often think about the long-term impacts of climate change." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I enjoy learning about cryptography." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I prefer taking the scenic route when driving." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I am drawn to surrealist art." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I appreciate complex world-building in fantasy novels." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I believe laws should adapt to changing times." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I enjoy discussing geopolitical strategies." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I am quick to adopt alternative lifestyles." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "openness", text: "I feel intellectually stimulated by abstract concepts." },

    // --- Emotional Stability (Neuroticism Reversed) (24 Questions) ---
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I rarely express road rage." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I do not panic when my computer crashes." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I wake up feeling positive about the day ahead." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I am highly resilient when facing professional setbacks." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I don't hold onto irritation after a disagreement." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I can easily accept critical reviews of my work." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I rarely feel anxious in confined spaces." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I am able to maintain composure during emergencies." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I rarely envy the possessions of others." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I am comfortable adapting to sudden schedule changes." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I do not constantly worry about job security." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I view failure as a learning opportunity." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I maintain a stable mood even when tired." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I am not easily disturbed by unexpected interruptions." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I can easily brush off minor inconveniences like traffic." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I don't dwell on embarrassing moments from the past." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I feel secure in my long-term plans." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I rarely feel unsupported by my peers." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I do not rely on others' approval for my self-esteem." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I can practice deep breathing to calm my nerves." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I view changes in management as normal." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I avoid catastrophizing when projects are delayed." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I am generally very content with my current skills." },
    { module: "Module C: Personality", type: "likert", traitType: "big5", trait: "emotional_stability", text: "I can discuss stressful topics without getting overwhelmed." }
];